### ISSUE TITLE
Santa's Workshop

### ISSUE THREAD

**Issue by BlooketPolice** [Minesraft2/Blooket-Cheats#100]
So I downloaded the new update to the GUI and I tried to open Santa's workshop tab and it won't open at all. When I click it doesn't open and it stays in my current GUI tab.

**Comment by Wilke000** [comment]
No it works. try downloading again

**Comment by Wilke000** [comment]
YAY U HAVE #100!!!!

**Comment by BlooketPolice** [comment]
I found a bug in the code that I had. It works now.

**Comment by Minesraft2** [comment]
Make sure that you're in the gamemode too, some tabs wont open if you're not
