### ISSUE TITLE
Hide GUI does not work

### ISSUE THREAD

**Issue by Blooket000** [Minesraft2/Blooket-Cheats#104]
Ctrl+Shift+H does not hide the GUI menu on Microsoft 11

**Comment by Minesraft2** [comment]
I use Windows 11 myself, and they keybind is working.
What browser are you using and have you tried clicking on the gui and then the keybind?

**Comment by Blooket000** [comment]
Im using Google and I did click the gui then the keybind.

**Comment by Blooket000** [comment]
but it still does not work for me for some reason

**Comment by Wilke000** [comment]
Update it

**Comment by Blooket000** [comment]
Now it works, Thank You
