### ISSUE TITLE
Does not work for javascript

### ISSUE THREAD

**Issue by blixzy1** [Minesraft2/Blooket-Cheats#114]
when you updated it it stopped working for javascript i hope you can fix this because we are going to play blooket soon in class

**Comment by Minesraft2** [comment]
It's literally made in javascript

**Comment by Minesraft2** [comment]
And all the cheats are still working

**Comment by iParadoxian** [comment]
Download the bookmarklet again and try again

**Comment by blixzy1** [comment]
k

**Comment by blixzy1** [comment]
i tried it its not working

**Comment by iParadoxian** [comment]
what hack u using

**Comment by GoofyGithub** [comment]
did you try putting javascript: before pasting the script?

**Comment by blixzy1** [comment]
yes

**Comment by blixzy1** [comment]
it used to work before he updated it

**Comment by blixzy1** [comment]
or it used to work before he updated it for me

**Comment by blixzy1** [comment]
wait

**Comment by blixzy1** [comment]
nvm!

**Comment by blixzy1** [comment]
yayyyyyyyyyyyyyyyyy

**Comment by GoofyGithub** [comment]
Alright now that the issue was resolved, this can now be closed.
