### ISSUE TITLE
Blooket GUI script does not work.

### ISSUE THREAD

**Issue by Crazygird** [Minesraft2/Blooket-Cheats#116]
I tried running it but it does not work.

**Comment by Crazygird** [comment]
i used javascript: then the code

**Comment by Minesraft2** [comment]
In the url bar?

**Comment by Minesraft2** [comment]
Did you try following the importing steps [here](https://github.com/Minesraft2/Blooket-Cheats/blob/main/tutorial/readme.md)?

**Comment by Crazygird** [comment]
ok thanks
