### ISSUE TITLE
Bookmark thingy

### ISSUE THREAD

**Issue by PoptartSutart** [Minesraft2/Blooket-Cheats#126]
When I click the GUI bookmark on the blooket website it just lags and nothing happens am I doing something wrong or....

**Comment by Minesraft2** [comment]
Can you open the inspect element console and check if there are any errors?
You can open it with ctrl + shift + j

**Comment by PoptartSutart** [comment]
my school blocked inspect element😔

**Comment by Minesraft2** [comment]
School chromebook?

**Comment by PoptartSutart** [comment]
yep

**Comment by BlooketHeck** [comment]
Same it doesn't work for me either.

**Comment by GoofyGithub** [comment]
make a random bookmark then click it with 2 fingers, then click edit. After that delete the bookmark code and not the bookmark, put javascript: then paste the code with no spaces

**Comment by Wilke000** [comment]
Yep! Thats a bookmarklet!

**Comment by Crazygird** [comment]
you can also type _javascript:_ 💯

**Comment by Crazygird** [comment]
then the code

**Comment by GoofyGithub** [comment]
That's basically what i said but simpler.

**Comment by Minesraft2** [comment]
@PoptartSutart did you import the bookmarklets.html file or make them manually?

**Comment by YaBoyMH** [comment]
What do I do if they blocked javascript

**Comment by PierceMichael** [comment]
> What do I do if they blocked javascript. Im on a school chromebook btw.

ur screwed

**Comment by PoptartSutart** [comment]
i tried the javascript: and that never worked + they blocked importing bookmarklets for some reason

**Comment by codemaster123puppy** [comment]
Close The Issue

**Comment by Minesraft2** [comment]
> i tried the javascript: and that never worked + they blocked importing bookmarklets for some reason

Are you sure they blocked importing? It should be in the 3 dots at the `chrome://bookmarks` url

**Comment by MrJackWillow** [comment]
U dont have to do any of That I will put a way to get it now

1. Go to the GUI.JS

2. do Ctrl+A and copy it

3. open a bookmark and select more

4. Type Javascript:

5. Paste Press Done and Enjoy!

**Comment by MrJackWillow** [comment]
> > i tried the javascript: and that never worked + they blocked importing bookmarklets for some reason
> 
> Are you sure they blocked importing? It should be in the 3 dots at the `chrome://bookmarks` url

Can you make a school chromebook method or just make my Steps Above more easier to understand?

^^^^^^^^^^^^

**Comment by Crazygird** [comment]
click the star in the url bar, click more and in the URL section, type _javascript:_ and your code.

**Comment by PoptartSutart** [comment]
i managed to import all of the bookmarks but when I tried to use one of the hacks nothing happened

**Comment by Minesraft2** [comment]
Which one and where did you run it

**Comment by PoptartSutart** [comment]
the bookmarks.html

**Comment by Minesraft2** [comment]
which bookmark did you run

**Comment by Minesraft2** [comment]
and what page did you run it on

**Comment by bohrium2b** [comment]
> > What do I do if they blocked javascript. Im on a school chromebook btw.
> 
> ur screwed

That is difficult because many sites (like Github and Blooket itself) rely on javascript. Thus many sites, most of them that would be used for school purposes, like Google Classroom, everything else Google, Schoology, Moodle, Canvas, etc. will also break.

**Comment by Minesraft2** [comment]
Gone stale
