### ISSUE TITLE
I only can do it once

### ISSUE THREAD

**Issue by EZFN7557** [Minesraft2/Blooket-Cheats#149]
i thought every 24h u can do it but how many times can i do it bc i did it only worked then

**Comment by Greenlio** [comment]
To add rewards? Yes, there is a serverside token and XP limit.

**Comment by EZFN7557** [comment]
i only did it once and i cant do it again?

**Comment by Minesraft2** [comment]
The daily limit resets at midnight UTC everyday

**Comment by EZFN7557** [comment]
waited yesterday and still it did not work tday it is midnight for me tho

**Comment by Minesraft2** [comment]
No, not midnight for you, midnight in the UTC timezone

**Comment by EZFN7557** [comment]
ohh ok

**Comment by Minesraft2** [comment]
It even tells you when it'll reset in the stats page
