### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by eletrickball** [Minesraft2/Blooket-Cheats#150]
So I use these hack on iPad by adding a website to favorites and changing the address to “JavaScript:(paste hacks here).” Everything works except for the GUI. Whenever I try to drag the hack box where it says “Click and drag here,” it doesn’t drag, and I also can’t scroll through all of the hacks if it’s a long list. This shouldn’t take that long to fix, so if you have any spare time, please make this compatible with iPad.

**Comment by PierceMichael** [comment]
> So I use these hack on iPad by adding a website to favorites and changing the address to “JavaScript:(paste hacks here).” Everything works except for the GUI. Whenever I try to drag the hack box where it says “Click and drag here,” it doesn’t drag, and I also can’t scroll through all of the hacks if it’s a long list. This shouldn’t take that long to fix, so if you have any spare time, please make this compatible with iPad.

Im pretty sure its for computer
