### ISSUE TITLE
Unlock All Blooks

### ISSUE THREAD

**Issue by FoxyLuca** [Minesraft2/Blooket-Cheats#151]
So I was having some trouble with this. It works but whenever I try to use it (let's say public match) It just doesn't works.

**Comment by Minesraft2** [comment]
What blook do you generally use?

**Comment by PierceMichael** [comment]
i just used it it works fine

**Comment by thebossjeff** [comment]
> What blook do you generally use?

hello, is there a way to actually keep a book unlocked even after a game?
like with the simulate unblock, would it be within the realm of feasibility to keep the book?

**Comment by Wilke000** [comment]
Nope there is no way. If there was it would already be added
