### ISSUE TITLE
gold quest tab doesnt work

### ISSUE THREAD

**Issue by peepoostpin** [Minesraft2/Blooket-Cheats#152]
when i tap gold quest on the gui, it doesnt do anything

im not using my javascript invention either
it just doesnt work

**Comment by peepoostpin** [comment]
same for crypto hack and santas workshop

**Comment by Minesraft2** [comment]
It has to do with getting all the players ingame

**Comment by peepoostpin** [comment]
ok

**Comment by GoofyGithub** [comment]
Issue Resolved?
