### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by eletrickball** [Minesraft2/Blooket-Cheats#153]
It won’t let me scroll through the hacks. It lets me scroll through the game modes, but the hacks in it I can’t scroll through. It scrolls through the real Blooket website instead of the hacks. I use iPad please fix it.

**Comment by eletrickball** [comment]
I also can’t click and drag it on iPad because it just scrolls on my Blooket page again.

**Comment by VillainsRule4000** [comment]
Use a computer :skull: iPad is an ok device for Blooket, but terrible for hacks.

**Comment by cph101** [comment]
> Use a computer 💀 iPad is an ok device for Blooket, but terrible for hacks.

Very true. :/

**Comment by eletrickball** [comment]
But is there any way for Minescraft2 to fix it? Please… I use my iPad for school and nothing else.

**Comment by GoofyGithub** [comment]
Is your school's revenue that low??

**Comment by Wilke000** [comment]
Lol

**Comment by iParadoxian** [comment]
im not sure of ipad browesrs that support the javascript: protocol, so i dont think that this is possible, at least to my knowledge

**Comment by VillainsRule4000** [comment]
> im not sure of ipad browesrs that support the javascript: protocol, so i dont think that this is possible, at least to my knowledge

I believe Chrome would but there's a different way to inject scripts on iPads.

**Comment by VillainsRule4000** [comment]
> Is your school's revenue that low??

:skull: let's be nice, an iPad is prob. more expensive than a chromebook.

**Comment by Wilke000** [comment]
Kinda true. I mean it depends on what year of iPad and what kinds

**Comment by Wilke000** [comment]
Then who does

**Comment by VillainsRule4000** [comment]
> Kinda true. I mean it depends on what year of iPad and what kinds

True that.

**Comment by Greenlio** [comment]
scripts aren't supported on mobile devices or tablets

**Comment by cph101** [comment]
> > i dont think the school owns the ipad tho...
> 
> 💀 what

Joe mama owns it 🤣

**Comment by iParadoxian** [comment]
> > > i dont think the school owns the ipad tho...
> > 
> > 
> > 💀 what
> 
> Joe mama owns it 🤣

how funny

**Comment by Greenlio** [comment]
no more issues - this has turned into a discussion, and it doesn't even meet the requirements for a discussion. closing
