### ISSUE TITLE
Contribute?

### ISSUE THREAD

**Issue by cph101** [Minesraft2/Blooket-Cheats#154]
Dear Minesraft2 (Aerell),

I am writing to enquire about whether you would be interested in allowing me to contribute? I am working on a Chrome / Safari / Edge extension for the cheats, as well as numerous other cheats I have made. Please RSVP via email at cph101@icloud.com, or on my Discord: cph101#5326.

Kind Regards,
cph101

**Comment by GoofyGithub** [comment]
It's not a bad idea, but i heard that he likes to keep his code original. Just keep that in mind...

**Comment by VillainsRule4000** [comment]
> It's not a bad idea, but i heard that he likes to keep his code original. Just keep that in mind...

Pull Requests are generally accepted.

**Comment by GoofyGithub** [comment]
fair enough, but @cph101 you should put this in pull requests next time and just wait it out.

**Comment by cph101** [comment]
> fair enough, but @cph101 you should put this in pull requests next time and just wait it out.

Okay.

**Comment by fowntain** [comment]
> > fair enough, but @cph101 you should put this in pull requests next time and just wait it out.
> 
> Okay. You have to edit it to pull request, and I cannot do that at the moment because it is obfuscated :/

Why do you need to change scripts? You can just add them.

**Comment by Jude-Gideon** [comment]
> Dear Minesraft2 (Aerell),
> 
> I am writing to enquire about whether you would be interested in allowing me to contribute? I am working on a Chrome / Safari / Edge extension for the cheats, as well as numerous other cheats I have made. Please RSVP via email at [cph101@icloud.com](mailto:cph101@icloud.com), or on my Discord: cph101#5326.
> 
> Kind Regards, cph101

You've commented on so many Blooket hack repos, even repos that have stolen code it's obvious you just want to take the source code.

**Comment by cph101** [comment]
> > Dear Minesraft2 (Aerell),
> > I am writing to enquire about whether you would be interested in allowing me to contribute? I am working on a Chrome / Safari / Edge extension for the cheats, as well as numerous other cheats I have made. Please RSVP via email at [cph101@icloud.com](mailto:cph101@icloud.com), or on my Discord: cph101#5326.
> > Kind Regards, cph101
> 
> You've commented on so many Blooket hack repos, even repos that have stolen code it's obvious you just want to take the source code.

I have a very powerful deobfuscator, and I also know of plenty of ways to do illegal things. If I wanted to steal the code and market it as my own, I would, thank you.

**Comment by cph101** [comment]
> Why do you need to change scripts? You can just add them.

You are right now that I think of that. Good idea @fowntain
