### ISSUE TITLE
Script?

### ISSUE THREAD

**Issue by Crazygird** [Minesraft2/Blooket-Cheats#157]
Could you make a script to flood a blooket  lobby?

**Comment by GoofyGithub** [comment]
It takes time for him to code stuff, Can't Rush Art.

**Comment by iParadoxian** [comment]
Already addressd https://github.com/Minesraft2/Blooket-Cheats/discussions/122 

Also, use discussions for script suggestions, use issues for, well, issues

**Comment by GoofyGithub** [comment]
Ok. This issue can be handled in two ways, Closed or Converted to a discussion.

**Comment by Greenlio** [comment]
Already being discussed in #122 
duplicate suggestion + misuse of issues

**Comment by iParadoxian** [comment]
why is it closed as completed if its a not-done task?
