### ISSUE TITLE
Ban?

### ISSUE THREAD

**Issue by Vitlyr** [Minesraft2/Blooket-Cheats#159]
Hello, dear scripters, I have a few notices and questions for these scripts, those questions are the following...

 1. Could you get banned for using these scripts?
 2. Are there other ways to use these scripts without bookmarking them or downloading them?

**Comment by VillainsRule4000** [comment]
> Hello, dear scripters, I have a few notices and questions for these scripts, those questions are the following...
> 
> 1. Could you get banned for using these scripts?
> 2. Are there other ways to use these scripts without bookmarking them or downloading them?

1. Could you get banned? Probably not. If you're worried, test on an alt to be safe.
2. You could right click, open the Inspect tool, open the Console, and put the script in. (probably disabled on school device)

**Comment by VillainsRule4000** [comment]
> > > Hello, dear scripters, I have a few notices and questions for these scripts, those questions are the following...
> > > 
> > > 1. Could you get banned for using these scripts?
> > > 2. Are there other ways to use these scripts without bookmarking them or downloading them?
> > 
> > 
> > 
> > 1. Could you get banned? Probably not. If you're worried, test on an alt to be safe.
> > 2. You could right click, open the Inspect tool, open the Console, and put the script in. (probably disabled on school device)
> 
> Yes, since I'm using a school device it's blocked. I was thinking of making a screen share-like website for the hacks since I can't really use them.

Bookmarklets are fine, no?

**Comment by Vitlyr** [comment]
> > > > Hello, dear scripters, I have a few notices and questions for these scripts, those questions are the following...
> > > > 
> > > > 1. Could you get banned for using these scripts?
> > > > 2. Are there other ways to use these scripts without bookmarking them or downloading them?
> > > 
> > > 
> > > 
> > > 1. Could you get banned? Probably not. If you're worried, test on an alt to be safe.
> > > 2. You could right click, open the Inspect tool, open the Console, and put the script in. (probably disabled on school device)
> > 
> > 
> > Yes, since I'm using a school device it's blocked. I was thinking of making a screen share-like website for the hacks since I can't really use them.
> 
> Bookmarklets are fine, no?

What do you mean?

**Comment by VillainsRule4000** [comment]
> > > Yes, since I'm using a school device it's blocked. I was thinking of making a screen share-like website for the hacks since I can't really use them.
> > 
> > 
> > Bookmarklets are fine, no?
> 
> What do you mean?

You mentioned that you "can't really use" the hacks. Don't bookmarklets work fine?

**Comment by Vitlyr** [comment]
> > What do you mean?
> 
> You mentioned that you "can't really use" the hacks. Don't bookmarklets work fine?

I'm sorry, I don't really know much about "bookmarklets" could you please explain that method to me further?

**Comment by VillainsRule4000** [comment]
> > > What do you mean?
> > 
> > 
> > You mentioned that you "can't really use" the hacks. Don't bookmarklets work fine?
> 
> I'm sorry, I don't really know much about "bookmarklets" could you please explain that method to me further?

sadly im lazy, please google it

**Comment by Vitlyr** [comment]
> > > What do you mean?
> > 
> > 
> > You mentioned that you "can't really use" the hacks. Don't bookmarklets work fine?
> 
> I'm sorry, I don't really know much about "bookmarklets" could you please explain that method to me further?

Oh wait, isn't that javascript? Oh, I forget to mention, our school blocked that too.

**Comment by Vitlyr** [comment]
> Oh wait, isn't that javascript? I forget to mention, our school blocked that too.

Any other ways to use them?

**Comment by VillainsRule4000** [comment]
> > > > What do you mean?
> > > 
> > > 
> > > You mentioned that you "can't really use" the hacks. Don't bookmarklets work fine?
> > 
> > 
> > I'm sorry, I don't really know much about "bookmarklets" could you please explain that method to me further?
> 
> Oh wait, isn't that javascript? I forget to mention, our school blocked that too.

you're out of luck. I would use the blooket utility when it's fixed.

**Comment by Vitlyr** [comment]
> you're out of luck. I would use the blooket utility when it's fixed.

Alright then.
