### ISSUE TITLE
The hotkey to open and close the GUI

### ISSUE THREAD

**Issue by NachoConsumer69** [Minesraft2/Blooket-Cheats#165]
I'm suggesting this because I find it annoying to press Ctrl + Shift + H everytime to open or close the gui. My suggestion is to make the hotkey "E" since it will be easier to open and close

**Comment by Eastonsharp** [comment]
deal with it because I like it

**Comment by 29TB** [comment]
not an issue, please change it to a discussion, but i say good idea, think there should be a hotkey editor in a settings tab

**Comment by NachoConsumer69** [comment]
> deal with it because I like it

shut up no you don't it sucks. Especially for some with small hands

**Comment by Minesraft2** [comment]
I put out a poll in the support server on which hotkey to use

**Comment by Minesraft2** [comment]
I'll change it to that until i find a way to setup a custom keybind
