### ISSUE TITLE
enable hosting is pointless, unlock plus gamemodes already solves it

### ISSUE THREAD

**Issue by TheBobCreator** [Minesraft2/Blooket-Cheats#17]
oof

**Comment by Minesraft2** [comment]
Yea but people are stupid and didn't know that so I made the script to be clear with people

**Comment by TheBobCreator** [comment]
wait
autobuy doesnt work

**Comment by TheBobCreator** [comment]
it says 0ms: Results (nothing)

**Comment by Minesraft2** [comment]
are you using the gui?

**Comment by Minesraft2** [comment]
if you are i found the problem and im fixing it rn

**Comment by Minesraft2** [comment]
This should be fixed now
