### ISSUE TITLE
Some cheats in GUI stopped working...

### ISSUE THREAD

**Issue by MariannaCat** [Minesraft2/Blooket-Cheats#170]
Crypto hack and gold quest in GUI don't open when I click on them (I been using them for 3 months now and this never hapend)

**Comment by Minesraft2** [comment]
Are you in the gamemode when you use them?

**Comment by NachoConsumer69** [comment]
> Crypto hack and gold quest in GUI don't open when I click on them (I been using them for 3 months now and this never hapend)

oml

**Comment by NachoConsumer69** [comment]
> Are you in the gamemode when you use them?

That happened for me too but I realized how to use it. Oh and can you look at my gui hotkey idea

**Comment by MariannaCat** [comment]
no.....

**Comment by MariannaCat** [comment]
but it usally works

**Comment by Minesraft2** [comment]
Fixed in commit [9160a68](https://github.com/Minesraft2/Blooket-Cheats/commit/9160a68446a508ec43ad5e68968829ee5d1f15ad)

**Comment by MariannaCat** [comment]
Ok!
