### ISSUE TITLE
firefox support?

### ISSUE THREAD

**Issue by ThatOneOcto** [Minesraft2/Blooket-Cheats#182]
foxfire support?

**Comment by GoofyGithub** [comment]
pending?

**Comment by Minesraft2** [comment]
i have no idea how to properly import bookmarklets into firefox

**Comment by GooseterV** [comment]
jod youre not supposed to tell them that

**Comment by GooseterV** [comment]
![image](https://user-images.githubusercontent.com/82774618/210029034-829bc61e-2fa9-4758-8c78-175bd5422841.png)

![image](https://user-images.githubusercontent.com/82774618/210029024-b206b81b-8654-4b32-af07-19eb574d96fb.png)
![image](https://user-images.githubusercontent.com/82774618/210029049-b5da1216-88a3-4744-856e-95cbdf323689.png)

![image](https://user-images.githubusercontent.com/82774618/210028992-9badd496-5581-47be-bf62-bbd5028459c2.png)

**Comment by Minesraft2** [comment]
that doesn't show in the toolbar tho

**Comment by GooseterV** [comment]
what toolbar

**Comment by GooseterV** [comment]
![image](https://user-images.githubusercontent.com/82774618/210029175-36bcd620-99df-4155-b31b-4d419abc3be5.png)
