### ISSUE TITLE
BUG: Instant kill & Double XP

### ISSUE THREAD

**Issue by GoofyGithub** [Minesraft2/Blooket-Cheats#185]
## Script
Monster Brawl

## The Problem
The instant kill button doesn't give you the instant kill upgrage and The instant kill used to work before one of the updates, did you change it in some way?

**Comment by Minesraft2** [comment]
Instant kill isn't setting the enemy hop to 1?

**Comment by Minesraft2** [comment]
Both of these scripts are working on my end, do you have access to console?

**Comment by GoofyGithub** [comment]
to the console, no. but i can still use bookmarks.

**Comment by Minesraft2** [comment]
Does the script just do nothing for you? It should make all the enemy hp 1

**Comment by GoofyGithub** [comment]
ill double check

**Comment by GoofyGithub** [comment]
its ether i'm leveling up too fast or the script works, i think it works.
