### ISSUE TITLE
BUG: Script MobileGui.js

### ISSUE THREAD

**Issue by UmbraAstro** [Minesraft2/Blooket-Cheats#197]
My other issue is deleted For Crypto hack mobile gui the hacks for crypto hack don’t show

**Comment by UmbraAstro** [comment]
And the tower defence fill deck and the monster brawl kill all enemies don’t work it might be something on my end idk cause it’s not like that with the other gui and I checked and there the same code

**Comment by Minesraft2** [comment]
Kill enemies doesn't seem broken, but I fixed the other 2
