### ISSUE TITLE
Someone is reobfuscating your code, and reuploading your GUI.

### ISSUE THREAD

**Issue by Jude-Gideon** [Minesraft2/Blooket-Cheats#204]
https://github.com/JaydenTD500/Blooket-cheatsss Is using some of your code, he's reobfuscated your unobfuscated scripts https://github.com/JaydenTD500/Blooket-cheatsss/blob/main/scripts%20(console)/Global/Add%20rewards.js

**Comment by UmbraAstro** [comment]
I know a lot of people who copy his gui and paste it

**Comment by JaydenTD500** [comment]
HEY, THE ADD REWARDS WAS ACTUALLY MADE BY ME

**Comment by JaydenTD500** [comment]
I CAN SEND YOU THE UNOFUSCATED CODE

**Comment by Minesraft2** [comment]
i have every cheat ever made unobfuscated

**Comment by JaydenTD500** [comment]
I made the add rewards

**Comment by Minesraft2** [comment]
Talk on discord

**Comment by Jude-Gideon** [comment]
> Talk on discord

Got a new acc.
