### ISSUE TITLE
Proof i  made my version of add rewards

### ISSUE THREAD

**Issue by JaydenTD500** [Minesraft2/Blooket-Cheats#205]
heres the unobfuscated code:
let i = document.createElement('iframe');
document.body.append(i);
window.alert = i.contentWindow.alert.bind(window);
i.remove();
var token = Object.values(webpackJsonp.push([[], { ['']: (_, a, b) => { a.cache = b.c }, }, [['']],]).cache).find((x) => x.exports?.a?.get).exports.a;
token.get("https://dashboard.blooket.com/api/users").then(({ data: { user } }) => {
    token.get("https://play.blooket.com/api/users/bonuses").then(({ data: { tokensAvailable: addedTokens, xpAvailable: addedXP } }) => {
        token.put("https://play.blooket.com/api/users/add-rewards", { user, addedTokens, addedXP })
            .then(() => alert(`Added rewards!
                Added rewards: $(addedTokens)
                Added XP: $(addedXP)`))
            .catch(() => alert('err'));
    }).catch(() => alert("err"));
}).catch(() => alert('err'));

**Comment by Minesraft2** [comment]
You know how I know you didn't make that?

**Comment by VillainsRule4000** [comment]
naw bro this is goose

**Comment by Minesraft2** [comment]
It's just mine but you switch out some strings and your string formatting is wrong too

**Comment by JaydenTD500** [comment]
here then

**Comment by JaydenTD500** [comment]
![IMG_1320](https://user-images.githubusercontent.com/94601497/211124167-9ddbcb62-d10d-481d-9db7-5d01877d1afa.jpeg)

**Comment by JaydenTD500** [comment]
I SWEAR TO GOD I  MADE THE CODE

**Comment by Minesraft2** [comment]
💀 bro lied on god

**Comment by JaydenTD500** [comment]
How can i proof i  made the code?

**Comment by Minesraft2** [comment]
try not stealing and modifying it

**Comment by Minesraft2** [comment]
it's really crazy, how people can just take it and then repeatedly claim they didn't

**Comment by JaydenTD500** [comment]
…

**Comment by JaydenTD500** [comment]
I MADDE THE CODE

**Comment by Minesraft2** [comment]
I want you to go look at the one in the repo, and really tell me

**Comment by Minesraft2** [comment]
that you didn't copy it

**Comment by Minesraft2** [comment]
https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/getDailyRewards.js

**Comment by JaydenTD500** [comment]
I DIDN’T COPY IT

**Comment by GooseterV** [comment]
bros on github.dev with "his code"

**Comment by GooseterV** [comment]
> I DIDN’T COPY IT

it is literally an exact copy of jods script

**Comment by JaydenTD500** [comment]
HOW CAN I PROOF IT’S MINE

**Comment by Minesraft2** [comment]
First, stop asking how to prove a false statement

**Comment by Minesraft2** [comment]
Second, maybe learn how to code next time

**Comment by JaydenTD500** [comment]
I know how to code

**Comment by JaydenTD500** [comment]
I made a  calculator

**Comment by JaydenTD500** [comment]
and a website using html

**Comment by Minesraft2** [comment]
💀 

> ![IMG_1320](https://user-images.githubusercontent.com/94601497/211124167-9ddbcb62-d10d-481d-9db7-5d01877d1afa.jpeg)

look at lines 10 and 11

**Comment by Minesraft2** [comment]
that doesn't work

**Comment by JaydenTD500** [comment]
Why

**Comment by JaydenTD500** [comment]
wait, let me try it

**Comment by GooseterV** [comment]
just block this JaydenTD500 kid :skull:

**Comment by Minesraft2** [comment]
ah yes, test the code that you wrote

**Comment by Minesraft2** [comment]
because you _totally_ made it

**Comment by JaydenTD500** [comment]
It works  just fine

**Comment by JaydenTD500** [comment]
look

**Comment by Minesraft2** [comment]
well yea it'll give the tokens, but that's what i wrote it to do

**Comment by Minesraft2** [comment]
but i also made it tell you how many tokens it added

**Comment by Minesraft2** [comment]
unlike "yours"

**Comment by cph101** [comment]
Lol
