### ISSUE TITLE
I can't use GUI in live games

### ISSUE THREAD

**Issue by Beep404-Boop404** [Minesraft2/Blooket-Cheats#21]
I don't know if the bug is only in fishing frenzy because I just tried that, but pls fix it.

**Comment by Beep404-Boop404** [comment]
Doesn't work in games, too!

**Comment by TheBobCreator** [comment]
is working

**Comment by TheBobCreator** [comment]
wait nvm :(

**Comment by arabbbbb** [comment]
This should be fixed.
![image](https://user-images.githubusercontent.com/106283388/195725830-8549d1ef-7ee9-4cc7-bd05-8bb5efa5b25f.png)
