### ISSUE TITLE
How did you use them

### ISSUE THREAD

**Issue by UmbraAstro** [Minesraft2/Blooket-Cheats#213]
When you unobfuscated it how did you use them?

**Comment by Minesraft2** [comment]
Same way you'd use it normally, copy all the code paste it in console, or in the url bar put "javascript:" and then paste the code there

**Comment by UmbraAstro** [comment]
With the // in them

**Comment by Minesraft2** [comment]
ok yea good point i'll fix that

**Comment by UmbraAstro** [comment]
Ty

**Comment by UmbraAstro** [comment]
I used a obfuscator and added async at the beginning to make it a book mark but that dosent seem to work idk if I’m stupid or something

**Comment by UmbraAstro** [comment]
I tested it Dosent work
