### ISSUE TITLE
this sounds stupid 

### ISSUE THREAD

**Issue by UmbraAstro** [Minesraft2/Blooket-Cheats#215]
Can you just make a version that’s obfuscated or show us how to obfuscate it like you did before because they seem to only work when it’s obfuscated

**Comment by UmbraAstro** [comment]
I think a tutorial on how to obfuscate would be better

**Comment by UmbraAstro** [comment]
So we could still edit to code but not distribute

**Comment by Minesraft2** [comment]
I found the issue, and I'm working on fixing it

**Comment by Minesraft2** [comment]
Try them now

**Comment by UmbraAstro** [comment]
Broken how do u want me to try them url? Or book mark

**Comment by UmbraAstro** [comment]
Bookmark broken I’ll try url

**Comment by UmbraAstro** [comment]
Both are broken

**Comment by Minesraft2** [comment]
I just tried both myself
