### ISSUE TITLE
Lmafo this is so funny 

### ISSUE THREAD

**Issue by UmbraAstro** [Minesraft2/Blooket-Cheats#216]
Check my previous idea it dosent work lmafo

**Comment by UmbraAstro** [comment]
There both broken Url and bookmark

**Comment by UmbraAstro** [comment]
Try them before publishing them

**Comment by Minesraft2** [comment]
I did try them before publishing this time.

**Comment by Minesraft2** [comment]
And I just reconfirmed that both are working

**Comment by UmbraAstro** [comment]
How did u use them?

**Comment by Minesraft2** [comment]
I copied the script, pasted it into the url bar, went to the start of it and added `javascript:` and that worked
I pasted the script into console, and that worked
I imported the bookmarklets.html file, and that worked

**Comment by UmbraAstro** [comment]
How do u make a html file on iOS

**Comment by UmbraAstro** [comment]
Cause I think it dosent work on it or I don’t know how to use it u got a phone u can try it in?

**Comment by Minesraft2** [comment]
💀 ios

**Comment by UmbraAstro** [comment]
Stfu That’s what my school iPad uses I have a pc with a 3080 but I’m not playing blooket at home 💀

**Comment by UmbraAstro** [comment]
I mean it is called mobile gui :

**Comment by Minesraft2** [comment]
Because it worked best on mobile

**Comment by UmbraAstro** [comment]
Try it on your phone?

**Comment by UmbraAstro** [comment]
Can you show me how to obfuscate ?

**Comment by UmbraAstro** [comment]
I know how to but like make it begin with (async isn’t of const

**Comment by UmbraAstro** [comment]
Btw why did you unobfuscate?

**Comment by UmbraAstro** [comment]
How do u obfuscate cheats?

**Comment by Minesraft2** [comment]
I put the obfuscated folder back go use those
