### ISSUE TITLE
BUG: Script name

### ISSUE THREAD

**Issue by JuggyHucklebuck** [Minesraft2/Blooket-Cheats#219]
Almost all of the scripts are not working.

They have a license thing on all of them and it causing them to not work.

**Comment by Minesraft2** [comment]
how are you running them? The license doesn't affect either bookmarklets or pasting in console

**Comment by JuggyHucklebuck** [comment]
> how are you running them? The license doesn't affect either bookmarklets or pasting in console

I am using javascript

**Comment by Minesraft2** [comment]
All the scripts are in javascript

**Comment by Minesraft2** [comment]
Did you import bookmarklets.html, javascript: in the URL bar, or paste in console?

**Comment by VillainsRule4000** [comment]
he is running them in javascript omg why you no understand stupid!!!!111!
🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 🤓 

~~this is a joke, dummies~~

**Comment by Minesraft2** [comment]
Fixed i hope
