### ISSUE TITLE
GUI.js

### ISSUE THREAD

**Issue by Animosity2** [Minesraft2/Blooket-Cheats#220]
When I copy-paste the js it simply doesn't show the GUI, Unlike the other times it has worked. I see no visible license that would tamper with the js and I am unsure of the issue. (I'm using a desktop device-Chromebook).

**Comment by Minesraft2** [comment]
If you could check the console for errors, for now try using the obfuscated one

**Comment by Animosity2** [comment]
I tried to use the obfuscated one and it didn't work either. I don't think I mentioned that is use js not console? (that might be the issue.)

**Comment by Minesraft2** [comment]
Im at school rn

**Comment by Animosity2** [comment]
Same. Thank you.

**Comment by Animosity2** [comment]
Ill leave this open just in case.

**Comment by Animosity2** [comment]
I go to the url and type "javascript:insert code here". Thats the only way I've done it so far.

**Comment by Minesraft2** [comment]
and both guis aren't working? obfuscated and unobfuscated?

**Comment by Animosity2** [comment]
Yes, they both are unresponsive as i know of.

**Comment by Minesraft2** [comment]
Ok, well I'll try and fix that when I get home, for now just import the bookmarklets.html file and use those cuz they're working

**Comment by Animosity2** [comment]
Ok, Would you prefer if i leave this open?

**Comment by Minesraft2** [comment]
Yes, I haven't fixed the issue yet

**Comment by Minesraft2** [comment]
Should be working now, reopen if still buggy
