### ISSUE TITLE
Factory Idea.

### ISSUE THREAD

**Issue by Animosity2** [Minesraft2/Blooket-Cheats#221]
This may be time-consuming but there could be a "Select factory worker" Where you can replace or add one of the books in the factory game mode. (ex if I wanted a cow I would go to the console and input the js etc.. and a drop-down menu would appear allowing me to select "cow" to use for my factory).

**Comment by Animosity2** [comment]
Assuming this is implemented i wonder if the GUI would be easier to implement.

**Comment by Minesraft2** [comment]
Yea because with the GUI I can add a dropdown for all the valid blooks, for the other ones I have to tell the user if that blook isn't valid

**Comment by Animosity2** [comment]
Yeah, I figured. Also wouldn't it be basically the same thing as the "simulate blook unlock" menu?

**Comment by Minesraft2** [comment]
No, some blooks don't have a factory blook

**Comment by Minesraft2** [comment]
Added 👍
