### ISSUE TITLE
Blooket race game idea

### ISSUE THREAD

**Issue by defensec** [Minesraft2/Blooket-Cheats#223]
Just a thought, what if you add auto answer with a timer thing? Pretty much, all you would do is it would be you put the code into the console, and it would ask, "how long do you want it to take to get to the finish" (Input time.) or something like "How many questions do you want to be answered per second?"

**Comment by defensec** [comment]
Let me know if this is already a thing.

**Comment by Animosity2** [comment]
This is not a thing yet but if it's used it may need some revision to be compatible.

**Comment by Greenlio** [comment]
Added to content branch in #a013e9e
