### ISSUE TITLE
Tower defense Idea.

### ISSUE THREAD

**Issue by Animosity2** [Minesraft2/Blooket-Cheats#224]
To summarize, A loadout system that is unique for each map. (For example, the code takes available open space next to the track an enemy would run on and would places a unit unique to the said map there and rinse and repeat for a user input-ed amount of times) (Example 2-Since the mine map is very compact, close-range units would be placed instead of long-range ones) (More stuff on user input, basically the user put let's say 3 into the drop-down and then 2 units specific to said map are placed down in previously stated spots).

**Comment by GooseterV** [comment]
elaborate more please, i dont fullu understand ehat you are trying to suggest

**Comment by Animosity2** [comment]
apologies but I'm afraid I stated everything in my idea above and can't elaborate or make anything better than I have already said.

**Comment by Animosity2** [comment]
The most I can do is say that its basically like a setup unit but they are unique to each map.

**Comment by Greenlio** [comment]
not possible without extensive user interface invasion

**Comment by Minesraft2** [comment]
Lmao yes it is

**Comment by Minesraft2** [comment]
Just too confusing to understand

**Comment by Greenlio** [comment]
> Just too confusing to understand

unfortunately I don't want to go to event.state.function.tower.buyTower.function() for a script that will look cool but be used by few

**Comment by Minesraft2** [comment]
> > Just too confusing to understand
> 
> unfortunately I don't want to go to event.state.function.tower.buyTower.function() for a script that will look cool but be used by few
🤓  actually it would just be stateNode.buyTower() 🤓

**Comment by Greenlio** [comment]
ok jod have it your way

**Comment by Minesraft2** [comment]
No I don't wanna do it you do it

**Comment by GooseterV** [comment]
ok jod have it yoir way

**Comment by Minesraft2** [comment]
no it's my birthday you have to do it
