### ISSUE TITLE
Bookmarklets.

### ISSUE THREAD

**Issue by Animosity2** [Minesraft2/Blooket-Cheats#225]
Not very dire but when I open bookmarklets (The folder) my compute lags a lot and my mouse freezes up. could be my computer is garbage but idk.

**Comment by Animosity2** [comment]
I did get the new ones with the new factory update that's when it started lagging.

**Comment by Minesraft2** [comment]
I'm not exactly sure what the issue here is

**Comment by Animosity2** [comment]
From my stand-point, I belive the issue is maybe something in the code is too big perhaps?

**Comment by Animosity2** [comment]
Basically a check-up on the code perhaps, then again I can do that myself...I don't know then this might not be an issue.

**Comment by Animosity2** [comment]
just my garbage computer.

**Comment by Minesraft2** [comment]
I put the scripts into a minifier before putting into the bookmark

**Comment by Animosity2** [comment]
Im not sure then, Probably a problem on my end.

**Comment by Animosity2** [comment]
Im just going to close this because I checked and the only conclusion is that my computer is garbage.

**Comment by Animosity2** [comment]
Only conclusion as in the only one I found*
