### ISSUE TITLE
Jayden is stealing your code again.

### ISSUE THREAD

**Issue by Jude-Gideon** [Minesraft2/Blooket-Cheats#226]
https://github.com/JaydenTD500/Blooket-token-69/issues/1

**Comment by Animosity2** [comment]
Here we go again.

**Comment by Minesraft2** [comment]
Greenlio sent a dmca

**Comment by Jude-Gideon** [comment]
> Greenlio sent a dmca

Ok good, I'm sick of that dude stealing people scripts, he commented on a issue on my repo and asked how to deobfuscate my code 💀

**Comment by fowntain** [comment]
> > Greenlio sent a dmca
> 
> Ok good, I'm sick of that dude stealing people scripts, he commented on a issue on my repo and asked how to deobfuscate my code 💀

no wayyyyy LMAOOOO 💀 💀 💀

**Comment by Jude-Gideon** [comment]
> > > Greenlio sent a dmca
> > 
> > 
> > Ok good, I'm sick of that dude stealing people scripts, he commented on a issue on my repo and asked how to deobfuscate my code 💀
> 
> no wayyyyy LMAOOOO 💀 💀 💀

https://github.com/Jude-Gideon/Blooket/issues/72#issuecomment-1378699988

**Comment by VillainsRule4000** [comment]
> > > > Greenlio sent a dmca
> > > 
> > > 
> > > Ok good, I'm sick of that dude stealing people scripts, he commented on a issue on my repo and asked how to deobfuscate my code 💀
> > 
> > 
> > no wayyyyy LMAOOOO 💀 💀 💀
> 
> [Jude-Gideon/Blooket#72 (comment)](https://github.com/Jude-Gideon/Blooket/issues/72#issuecomment-1378699988)

NO WAY HE ACTUALLY 💀 💀 ☠️ 💀 💀
