### ISSUE TITLE
Send glitch idea.

### ISSUE THREAD

**Issue by Animosity2** [Minesraft2/Blooket-Cheats#228]
This is one of my more "Out of pocket" Ideas, Instead of sending one glitch at a time It sends all of them in a row (I'm assuming that all of them at once wouldn't work/would crash the game). This can be implemented for any, I did not have any specific "Send glitch" In mind.

**Comment by Animosity2** [comment]
From how i phrased it i belive this would be more troll than function.

**Comment by VillainsRule4000** [comment]
I did spoof all of these once (on myself).
It was incredibly laggy.

Maybe put this in the content branch.

**Comment by Minesraft2** [comment]
I could probably do it, not sure

**Comment by Minesraft2** [comment]
Because firebase might not see some of them if I do it too fast

**Comment by Minesraft2** [comment]
I tried doing this, but only 2 glitches would activate when I try, even with a delay between each one.
