### ISSUE TITLE
Make a script that lets you edit the amount of a blook you have

### ISSUE THREAD

**Issue by Sadlittlelad** [Minesraft2/Blooket-Cheats#229]
Describe idea here
Like lets say I have a Toast blook and use the script. It asks me what blook I want to duplicate and the number of the blook, and it sets the dupe number to that number. Or anything similar where you can sell a blook and still keep it or something.

**Comment by Minesraft2** [comment]
I already would've done this if it was possible

**Comment by Sadlittlelad** [comment]
Oh. Well thank you for informing me.
