### ISSUE TITLE
DMCA takedown of rxzyx/blooket-hacks

### ISSUE THREAD

**Issue by Angelio-Mustachio-Coder** [Minesraft2/Blooket-Cheats#234]
Why did you DMCA takedown rxzyx's repo?

**Comment by Minesraft2** [comment]
Because those cheats were made by me

**Comment by Minesraft2** [comment]
Rzx stole the method from gliz's original cheats before he got the c&d and i took over

**Comment by rxzyx** [comment]
Nice fake. Russophobic?

**Comment by rxzyx** [comment]
The hack methods are the same ... I know how to do React, which is how I made them?

**Comment by VillainsRule4000** [comment]
> Nice fake. Russophobic?

salty you got a dcma? L skid

**Comment by Minesraft2** [comment]
> The hack methods are the same ... I know how to do React, which is how I made them?

You should've done that instead of stealing gliz's code

**Comment by rxzyx** [comment]
Lol. Salty mice, while you all are focused on skidding of real creators, I am focused on new projects )) It's funny how 'coders' r tryna call me a skid. L.

**Comment by Minesraft2** [comment]
Deny all you want, I don't care about your other "projects" you most like also stole. We asked you in the beginning to take down your skidded cheats and you refused. Plus the fact that you're here right now trying to argue shows you really are salty

**Comment by VillainsRule4000** [comment]
> Lol. Salty mice, while you all are focused on skidding of real creators, I am focused on new projects )) It's funny how 'coders' r tryna call me a skid. L.

fix your old projects first 🥱 gimkit hacks don't work, neither do prodigy

**Comment by VillainsRule4000** [comment]
oh wait

**Comment by VillainsRule4000** [comment]
they're not your projects 🤣
