### ISSUE TITLE
Different hack website idea

### ISSUE THREAD

**Issue by FennecFoxer** [Minesraft2/Blooket-Cheats#235]
Here me out but i have been searching for gimkit hacks for years and i was wondering since you have the best blooket hacks  mabye you can have the best/only working gimkit hacks gimkit is such a fun game when i host still super fun when my teachers do but i hate when i run out of money and energy and snowballs and getting the questions wrong so i thought why not ask you for some good gimkit hacks. If you can't do it i understand.

**Comment by Unsspeakable** [comment]
Oh and if/when you do give me a link please.

**Comment by Minesraft2** [comment]
painbow said he might release his, but i'll look into gimkit at a later date

**Comment by Unsspeakable** [comment]
ok thanks
