### ISSUE TITLE
BUG: Everything

### ISSUE THREAD

**Issue by j3lf** [Minesraft2/Blooket-Cheats#236]
## Script
Which script is causing the problem

## The Problem
Blooket bans you if     you use it

## How I ran it
bookmarklets.htm;l

**Comment by Minesraft2** [comment]
By using which one

**Comment by Minesraft2** [comment]
They wont ban you for using cheats, at most they'll suspend you for using the daily rewards cheat

**Comment by j3lf** [comment]
Bro none the cheats work and the gui dont open

**Comment by Minesraft2** [comment]
And you imported the bookmarks properly?

**Comment by shejialai** [comment]
the add rewards does not work, in fact i tried to open the gui but it did not open on play.blooket.com

**Comment by Minesraft2** [comment]
I'll look into it later, I'm busy today

**Comment by Jude-Gideon** [comment]
> I'll look into it later, I'm busy today

Ben fucked with user requests.

**Comment by Jude-Gideon** [comment]
![image](https://user-images.githubusercontent.com/113489420/212572365-0bb2548d-a4e9-4206-ae68-d3a56b7fe415.png)

**Comment by Minesraft2** [comment]
Should be a one word fix

**Comment by Minesraft2** [comment]
ok i fixed daily rewards, but i can't seem to get the gui to not open, it works everytime

**Comment by Minesraft2** [comment]
nevermind, i will fix that

**Comment by Minesraft2** [comment]
Fixed 👍
