### ISSUE TITLE
BUG: Reset play(S) gold does not reset the gold, and trying to swap gold brigns you to a page saying "There was an issue"

### ISSUE THREAD

**Issue by defensec** [Minesraft2/Blooket-Cheats#238]
## Script
Which script is causing the problem

## The Problem
The problem with the script

## How I ran it
Bookmarklets.html import, javascript: in url bar, or paste in console.

**Comment by defensec** [comment]
Not sure what the problem is fully.

**Comment by Minesraft2** [comment]
unable to reproduce
