### ISSUE TITLE
BUG: GUI no longer working

### ISSUE THREAD

**Issue by thebossjeff** [Minesraft2/Blooket-Cheats#239]
I have used these for months, and appreciated them. i had the GUI, and it worked like a charm.
however, the bookmarklet just stopped working.
and no matter what I make the bookmarklet, it does not work
please help!

**Comment by Minesraft2** [comment]
Have you made sure that you're using the latest version?

**Comment by Greenlio** [comment]
unable to reproduce

**Comment by Wilke000** [comment]
Ayo

**Comment by SnesLover22** [comment]
yeah, on my site: sneslover22.github.io/Mathews-Collection , i put your hack there with instructions (creds will be put on there soon, when they start working again) and it didn't work today after it working for a while. I went to the main blooket page with the stats and stuff, and it worked kinda? idk can you help?

**Comment by GooseterV** [comment]
hey @SnesLover22 i am going to kindly give you 24 hours and ask you politely to remove our scripts from your "site" as it expresslh violates the terms of the stewart license. We will not hesitate to issue a dmca takedown if you do not want to abide.

**Comment by SnesLover22** [comment]
Im sorry, but It technically... isnt your code????? I originally found it on some other repository, and It took me a while to find the original creator (minesraft2) JUST so I can tell them the problem. So idk tbh if the other guy deleted the license since I don't remember there being one there. I took it off their repository, not yours.

**Comment by VillainsRule4000** [comment]
> Im sorry, but It technically... isnt your code????? I originally found it on some other repository, and It took me a while to find the original creator (minesraft2) JUST so I can tell them the problem. So idk tbh if the other guy deleted the license since I don't remember there being one there. I took it off their repository, not yours.

goose works with minesraft...you fucked up badly
i'd reccomend you take them down
minesraft is serious about this.

**Comment by Minesraft2** [comment]
Goose and greenlio also own the license, they have full permission to request takedowns on my behalf

**Comment by SnesLover22** [comment]
I took it off a different repository, not yours! and idk which one its in a mass pile of other starred repositories so idk what to do now!

**Comment by Wilke000** [comment]
Yea Minecraft has already taken down like 2 different repos that are blooket hacks one of which is ryx's

**Comment by Minesraft2** [comment]
> hey @SnesLover22 i am going to kindly give you 24 hours and ask you politely to remove our scripts from your "site" as it expresslh violates the terms of the stewart license. We will not hesitate to issue a dmca takedown if you do not want to abide.

don't have to take down the whole thing just the files with our scripts

**Comment by SnesLover22** [comment]
idk if he made any changes though. I wanna take it down if I must, if it IS your original code. I remember the repository saying something about it having some changes made to it, which, wouldn't it be, due to your hacks being open source, fall under the creative commons license?

**Comment by SnesLover22** [comment]
and technically your hacks go against Blooket so a DMCA against me would do nothing since your code goes against bookets license.

**Comment by GooseterV** [comment]
you really wanna die on this hill? you arent the first arrogant kid we've dealt with

**Comment by Wilke000** [comment]
NOTHING!?
https://github.com/rxzyx/Blooket-Hacks
Used to be blooket hacks. I good collection of them I may say so myself. (Minescraft yours is still better)

**Comment by Wilke000** [comment]
Lol yea @SnesLover22 get out of this before it's too late. Trust me.

**Comment by GooseterV** [comment]
and no just because they are open source does NOT mean they fall under creative commons. It is expressly licensed under the terms listed in the stewart private license

**Comment by Wilke000** [comment]
He/she will take it down. And it will be taken down. Proof is ryx's repo

**Comment by GooseterV** [comment]
@SnesLover22 kindly remove the scripts and give up or we may be forced to take action

**Comment by GooseterV** [comment]
another point: it doesnt matter which repository you found them from, if you took code from a repository violating our license, you are also now violating the license

**Comment by VillainsRule4000** [comment]
this entire thing is stupid. why does this kid think he can just skid.
just replace the bad shit with a link to the repo.

**Comment by Greenlio** [comment]
lmao.. one of his repos featuring him saying "fuck dmca" in the repo description.

he has 2 hours to remove the infringing content or we will be issuing a dmca request to GitHub.

**Comment by Greenlio** [comment]
in continuum, the issue that this was created for is **un-reproducable** with current code and can be considered stale.

**Comment by SnesLover22** [comment]
like I said, it was on a different repository with no license

**Comment by Minesraft2** [comment]
And like we said, that repository violated our license

**Comment by Minesraft2** [comment]
By taking code from there, you are also violating our license

**Comment by Minesraft2** [comment]
Remove the script from your site, and all will be good

**Comment by SnesLover22** [comment]
also im not an arrogant child im 15, i know what I'm doing.

**Comment by Minesraft2** [comment]
If you know what you're doing remove the script

**Comment by Minesraft2** [comment]
You have 58 minutes

**Comment by VillainsRule4000** [comment]
> You have 58 minutes

bro actually set a timer :rofl: 💀

**Comment by VillainsRule4000** [comment]
@SnesLover22 back out now.
i've seen minesraft dcma.
he's serious about it.

**Comment by Greenlio** [comment]
i dont care imo, im submitting the dmca now @Minesraft2 @GooseterV

**Comment by SnesLover22** [comment]
blooket hacks go against blooket policy... I could just tell blooket now bout it...

**Comment by GooseterV** [comment]
fine w/ me

**Comment by SnesLover22** [comment]
your license means nothing against a larger company

**Comment by SnesLover22** [comment]
ok ill make a deal: I'll change the link to go to this repository. Good or not?

**Comment by Minesraft2** [comment]
They know about us, very aware infact. You in the other hand are not a larger company

**Comment by Wilke000** [comment]
Thats what you think

**Comment by SnesLover22** [comment]
More people from my school actually use your hacks when located to my site, so I'm actually funneling more people to you

**Comment by Wilke000** [comment]
Ben’s so mad at you rn 😆

**Comment by SnesLover22** [comment]
plus im pretty sure your license is for the newest hack, as I'm using what seems to be the old/og hack

**Comment by SnesLover22** [comment]
they are going to his repo, as the hack stopped working I directed them to this repository for the less effective separate bookmarklets

**Comment by Wilke000** [comment]
Bookmarklets are good for easy access to the gui

**Comment by Wilke000** [comment]
Speaking of the gui the sell cheap blooks isn't on it

**Comment by Greenlio** [comment]
![image](https://user-images.githubusercontent.com/62725108/213495099-769c8af9-82d0-4df7-aff7-44072370a764.png)

**Comment by Minesraft2** [comment]
Ok, let me just say this and get it over with. I know some cheats may be buggy right now, I'm working on fixing them. You violated the stewart private license meaning we can dmca takedown you repository unless changed. Any older version of said cheats are also protected by the license. Any other repository with the cheats are also violating the license, and will be taken down when identified (aside from forks of this repo)

**Comment by Minesraft2** [comment]
> Speaking of the gui the sell cheap blooks isn't on it

Yea someone brought that up to me before, ig i forgor to fix it
