### ISSUE TITLE
multiple people modifying or reobfuscating your code

### ISSUE THREAD

**Issue by Jude-Gideon** [Minesraft2/Blooket-Cheats#240]
https://github.com/SwiftGuard1/Blooket-Hacks https://github.com/GhostestN/Blooket-Hacks

swift is using rxz and your codes and reobfuscating then, and ghostest is plain out stealing all of your code also can you unban me from your discord?

**Comment by Minesraft2** [comment]
Not long after I sent an issue to the first guy he removed it lmao, and Greenlio already sent a dmca to the other guy
