### ISSUE TITLE
Simulate unlock not working

### ISSUE THREAD

**Issue by Sadlittlelad** [Minesraft2/Blooket-Cheats#244]
How do I use simulate unlock? I did it on the game id page, the blook page, the stat page, but never even gave a alert.

**Comment by Minesraft2** [comment]
Market page

**Comment by Minesraft2** [comment]
Just tested the most recent version, the only issue is that some blooks don't work, I'll see what I can do about it

**Comment by Sadlittlelad** [comment]
okay, thank you
