### ISSUE TITLE
unlock all blooks

### ISSUE THREAD

**Issue by mrunit69** [Minesraft2/Blooket-Cheats#248]
unlock all the blook skins

**Comment by mrunit69** [comment]
unlock all blook skins

**Comment by Minesraft2** [comment]
[useAnyBlook](https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/useAnyBlook.js) and [useAnyBlookPart](https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/useAnyBlookPart.js)
Getting all blooks permanently isn't possible
