### ISSUE TITLE
make auto win? or another idea is being able to set ur own amount of tokens

### ISSUE THREAD

**Issue by mrunit69** [Minesraft2/Blooket-Cheats#249]
Describe idea here
automatically win blooket game. or another idea is being able to set ur own amount of tokens so u can buy as many blooks and other stuff as you want?

**Comment by mrunit69** [comment]
?

**Comment by Minesraft2** [comment]
You can't get infinite tokens

**Comment by Minesraft2** [comment]
And you can't end games on the client side

**Comment by mrunit69** [comment]
> You can't get infinite tokens

aw that sucks, u never answerd abt automatically winning blooket game tho?
