### ISSUE TITLE
BUG: GUI not appearing

### ISSUE THREAD

**Issue by davidiguess** [Minesraft2/Blooket-Cheats#250]
## Script
Which script is causing the problem
GUI.js
## The Problem
The problem with the script
It doesn't appear when I run it
## How I ran it
 javascript: in url bar

**Comment by Minesraft2** [comment]
Obfuscated or unobfuscated

**Comment by davidiguess** [comment]
Obfuscated

**Comment by Minesraft2** [comment]
Are you running it on a school chromebook?

**Comment by davidiguess** [comment]
yes

**Comment by Minesraft2** [comment]
Have you tried importing the bookmarklets.html file? You might be pasting it wrong

**Comment by davidiguess** [comment]
i'll try that real fast

**Comment by davidiguess** [comment]
it worked, i guess i was just having a skill issue moment
