### ISSUE TITLE
Pop-Ups not showing up (Could be my computer, idk)

### ISSUE THREAD

**Issue by MalwareMason** [Minesraft2/Blooket-Cheats#251]
I've tried multiple scripts with this, most of them work, but the ones that need you to answer in a pop-up don't since the pop-up never appears. I do get the blue circle notification next to the tab picture, so it may just be my side.
MacBook Air btw

**Comment by Minesraft2** [comment]
Can you tell me one of the cheats? You could also just use the gui

**Comment by MalwareMason** [comment]
Literally any cheats where you have to do something with the pop-up; I guess spam open boxes since you have to type the box and amount in the popup

**Comment by Minesraft2** [comment]
I'm pretty sure it's on your end, and I'm not quite sure what to do about it
