### ISSUE TITLE
IDEA: A cheat to combat cheaters

### ISSUE THREAD

**Issue by pazza2234** [Minesraft2/Blooket-Cheats#253]
cheating is fine if it is just for fun, but when somone in the class gets a bunch of school curency then it becomes outragous. somthing in the hacks, to make it where a teacher can click a button, or run a hack of there own to make the cheaters be kicked, reported (to the teacher) or nothing happens.

**Comment by Minesraft2** [comment]
Lmao i probably could do smth for that, but chaos is sort of what we want.
And I'm not bouta change every sigle cheat to do it

**Comment by VillainsRule4000** [comment]
i love chaos
lo
