### ISSUE TITLE
guis.js its not working 

### ISSUE THREAD

**Issue by blooketadmin** [Minesraft2/Blooket-Cheats#260]
## Script
Which script is causing the problem

## The Problem
The problem with the script

## How I ran it
Bookmarklets.html import, javascript: in url bar, or paste in console.

**Comment by Minesraft2** [comment]
Make a new issue and actually fill out the information in the template, I can't determine the problem by just "guis.js its not working"

**Comment by blooketadmin** [comment]
> Make a new issue and actually fill out the information in the template, I can't determine the problem by just "guis.js its not working"

mb I will
