### ISSUE TITLE
gui.js

### ISSUE THREAD

**Issue by blooketadmin** [Minesraft2/Blooket-Cheats#261]
## Script
idk

## The Problem
it'doesnt work

## How I ran it
JavaScript:

**Comment by Wilke000** [comment]
Did u use the obfuscated or the unobfuscated

**Comment by blooketadmin** [comment]
> Did u use the obfuscated or the unobfuscated
> […](#)

unobfuscated

**Comment by Minesraft2** [comment]
Try importing the bookmarklets.html file or using the obfuscated version instead.
There are some things in the unobfuscated versions like missing semicolons that stop javascript: methods from working that I fixed by minifying the versions in the bookmarklet files

**Comment by blooketadmin** [comment]
> Try importing the bookmarklets.html file or using the obfuscated version instead.
> There are some things in the unobfuscated versions like missing semicolons that stop javascript: methods from working that I fixed by minifying the versions in the bookmarklet files

ok tysm

**Comment by Wilke000** [comment]
Use obfuscated if ur gonna use bookmarklets. Or import the bookmarklets file like minescraft said

**Comment by blooketadmin** [comment]
> Use obfuscated if ur gonna use bookmarklets. Or import the bookmarklets file like minescraft said
> […](#)

as javascript do I use : that symbol for bookmarklets.html

**Comment by Wilke000** [comment]
No look at the tutorial for how to import bookmarklets

**Comment by blooketadmin** [comment]
> No look at the tutorial for how to import bookmarklets
> […](#)

okk thank y'all so muchhhh

**Comment by Wilke000** [comment]
Np :D

**Comment by blooketadmin** [comment]
soo I look at it and it says how to import bookmarks not bookmarklets
and also im so confused

**Comment by Wilke000** [comment]
Just do that its the same thing

**Comment by blooketadmin** [comment]
it shows red tho and won't let me save it

**Comment by blooketadmin** [comment]
it still won't let me

**Comment by blooketadmin** [comment]
> Just do that its the same thing
> […](#)

if you know how to do it do you think you could give me a tutorial on it

**Comment by Minesraft2** [comment]
Bookmarklets are bookmarks

**Comment by Minesraft2** [comment]
We add the let to distinguish between ones that go to websites and ones that run javascript

**Comment by StarbuckLovers** [comment]
The computer gui works with JavaScript: bookmarks not the mobile one if your using the mobile one that might be the issue

**Comment by StarbuckLovers** [comment]
Because the semicolons are placed correctly in that one to make the other one work just use a website that changes the JavaScript code to bookmark code for it to read

**Comment by blooketadmin** [comment]
> The computer gui works with JavaScript: bookmarks not the mobile one if your using the mobile one that might be the issue

I haven't been using the moble but idk im on my school computer

**Comment by blooketadmin** [comment]
> We add the let to distinguish between ones that go to websites and ones that run javascript

English please?

**Comment by Minesraft2** [comment]
> > We add the let to distinguish between ones that go to websites and ones that run javascript
> 
> English please?

Bookmarklets are bookmarks that run javascript instead of going to a website

**Comment by StarbuckLovers** [comment]
If ur on your school computer just use inspect element and copy it and paste in the terminal don’t type JavaScript

**Comment by StarbuckLovers** [comment]
Btw the unobfuscated code works on mobile because of (async

**Comment by StarbuckLovers** [comment]
That’s why it works with bookmarks even though I just use a school chrombook

**Comment by VillainsRule4000** [comment]
> If ur on your school computer just use inspect element and copy it and paste in the terminal don’t type JavaScript

retarded ass
most schools block inspect

**Comment by blooketadmin** [comment]
> If ur on your school computer just use inspect element and copy it and paste in the terminal don’t type JavaScript

they blocked us from using it

**Comment by blooketadmin** [comment]
> > If ur on your school computer just use inspect element and copy it and paste in the terminal don’t type JavaScript
> 
> retarded ass most schools block inspect

it sucks honestly

**Comment by blooketadmin** [comment]
> > > We add the let to distinguish between ones that go to websites and ones that run javascript
> > 
> > 
> > English please?
> 
> Bookmarklets are bookmarks that run javascript instead of going to a website

gotcha

**Comment by SnesLover22** [comment]
> > > > We add the let to distinguish between ones that go to websites and ones that run javascript
> > > 
> > > 
> > > English please?
> > 
> > 
> > Bookmarklets are bookmarks that run javascript instead of going to a website
> 
> gotcha

if this might help you: a lot of times, schools block imports of bookmarks. if you wanna go through the hard way, copy each of the js codes and make each bookmarklet separately. In my case, the way shown by the Blooket Cheats team doesn't work for me. My school doesn't accept bookmarklets 100%. I go around it by making a bookmark, clicking out, then going back and changing the link to the code. if I do it by making a bookmark and before clicking out I replace the link, but It doesn't work. Try different ways to get the markets working, as the import method might not be an option according to your school's policy :)

**Comment by Minesraft2** [comment]
I don't actually think school can block importing bookmarks. You just go to [chrome://bookmarks](chrome://bookmarks) and import it there

**Comment by Minesraft2** [comment]
Though they _can_ block javascript:

**Comment by SnesLover22** [comment]
My old school did block importing bookmarks, and I did some...umm.. shiz at my new school and they kinda blocked JS bookmarklets. But they did it ineffectively since I explained how I still do it in my above comment. But can't you maybe, in theory, make a site, embed the blooket.com/play page on there, and then have buttons that run the JS code for those who don't have access to bookmarklets? You have to be on the site, and technically embedding blooket on a page means being on blooket... I'll test that theory later...

**Comment by Minesraft2** [comment]
I tried doing that, won't be able to get past the login page due to "too many redirects"

**Comment by SnesLover22** [comment]
aww that sucks...  Wait I have another idea: kahoot.rocks . Thats my idea. It's kinda like a Minecraft client, its Minecraft but with different features! Kahoot.rocks is like that, with its own auto answer and bot flooder! Its kahoot, but a new kahoot, so maybe a mod of the blooket API would work! It would have its own site and everything! would that be a possible idea?

**Comment by SnesLover22** [comment]
oh shiz wait they just updated their ToS

**Comment by SnesLover22** [comment]
ima do it anyway >:D

**Comment by blooketadmin** [comment]
> I tried doing that, won't be able to get past the login page due to "too many redirects"

ok so I got it it took me 2 days but yk time is time and finally I figured how to do it I had to hack the schools computerrr but anyway yea thanks for trying to help

**Comment by SnesLover22** [comment]
np??? r u sure you aren't doing something slightly illegal here? Hacking your school computer??

**Comment by blooketadmin** [comment]
> np??? r u sure you aren't doing something slightly illegal here? Hacking your school computer??

ummmm, SHHHHHHHHH!!!!!!!!!

**Comment by Wilke000** [comment]
FBI open up!!!

**Comment by blooketadmin** [comment]
> FBI open up!!!
> […](#)

fu--

**Comment by Wilke000** [comment]
:)

**Comment by blooketadmin** [comment]
this "issue" turned into a play chat

**Comment by blooketadmin** [comment]
I thought this was gonna be unopened bur it has 45 comments :0

**Comment by StarbuckLovers** [comment]
Close it or convert to discussion you got it fixed right?

**Comment by blooketadmin** [comment]
> Close it or convert to discussion you got it fixed right?
so long soldiers
