### ISSUE TITLE
IDEA: PLEASE MAKE THE SELECT ANY BLOOK PERMANENT!

### ISSUE THREAD

**Issue by eletrickball** [Minesraft2/Blooket-Cheats#265]
Please make it so that you can select any Blook any time you want, and the Blooks save to your account, so you never have to click it again, and you can still select any Blook.

**Comment by SnesLover22** [comment]
that would most likely go against the blooket Terms of Service even MORE beyond what this repo already does. idk you might get banned if Minesraft2 does it. would be cool though.

**Comment by Minesraft2** [comment]
It's just straight up not possible as of now

**Comment by Wilke000** [comment]
Minescraft u should really put that on the read-me that select any blook and simulate unlock permanently are impossible

**Comment by StarbuckLovers** [comment]
It’s not possible if it’s in console the console will refresh every time you reload the page with the original code and not the code Minecraft uses even if it was client side
