### ISSUE TITLE
Custom CUSTOM blooks

### ISSUE THREAD

**Issue by SnesLover22** [Minesraft2/Blooket-Cheats#266]
So i had an idea to where maybe you can make custom CUSTOM blooks, so like replace with images/gifs. I saw a hack one time with gold rush that either deleted/ made the chests invisible so maybe my idea could work in some weird way. I think it'd be cool to have a rick astley gif as a blook lol

**Comment by Wilke000** [comment]
No impossible

**Comment by j3lf** [comment]
It would be cilent side

**Comment by blooketadmin** [comment]
> It would be cilent side

yea true but at least you can see it by you I mean yourself

**Comment by StarbuckLovers** [comment]
It might be possible but it would be client side and only you could see it if you hosted a blooket I don’t think you would be able to see it

**Comment by VillainsRule4000** [comment]
@Minesraft2 to explain this, they're talking about changing the custom blooks (like these)
![image](https://user-images.githubusercontent.com/101288516/214637951-8dee9601-0938-4537-8a3b-a8ffa9032771.png)
into an image/gif to join a game with.

**Comment by VillainsRule4000** [comment]
not sure if this is possible @Wilke000, it's not as simple as make your own blook.

**Comment by Wilke000** [comment]
Ik I said No, it’s impossible

**Comment by Wilke000** [comment]
I didn't mean it's possible to be clear
