### ISSUE TITLE
BUG: Bookmarklets.html

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#267]
## Script
Bookmarklets (Unobfuscated)

## The Problem
The bookmarklets inside the folder are these 2 pages: 

https://user-images.githubusercontent.com/85253703/214058804-f84ca8b6-ba98-43b4-9d2f-d5da59f5f278.mov

**Comment by Minesraft2** [comment]
Are you sure you imported the bookmarks right?

**Comment by Wilke000** [comment]
Yes I’ve been doing it since you released your bookmarklets
