### ISSUE TITLE
BUG: getDailyRewards.js

### ISSUE THREAD

**Issue by Jisenku** [Minesraft2/Blooket-Cheats#269]
## Script
unobfuscated > global > _getDailyRewards.js_

## The Problem
After pasting (multiple times w/ refresh) it still says "There was an error getting bonus data."

## How I ran it
Pasting into Console

## Additional Info
Running Windows 10, Chrome 109.0.5414.75 (Official Build) (64-bit) (cohort: Stable)

**Comment by VillainsRule4000** [comment]
must be an api change, not an issue for you.
@Minesraft2 will fix as soon as possible.

**Comment by Wilke000** [comment]
"Along with this update, we've also reworked the way tokens are rewarded at the end of games. Instead of having to choose a token multiplier, we now just always give you the x3! Also, each day instead of getting 10 free tokens, you'll get to spin the Daily Wheel for a chance at a whole bunch more!"

**Comment by Wilke000** [comment]
This is gonna be funnnnnnnnnn :)
Ben look out u just messed up

**Comment by Wilke000** [comment]
They still have token limit :(
<img width="783" alt="Screenshot 2023-01-24 at 9 01 13 AM" src="https://user-images.githubusercontent.com/85253703/214314452-93cffbd4-7aca-4ccd-b480-058828ce9fdc.png">

**Comment by Wilke000** [comment]
<img width="219" alt="Screenshot 2023-01-24 at 9 01 37 AM" src="https://user-images.githubusercontent.com/85253703/214314546-90eaec99-e4ce-4443-847c-10d822c8bc7a.png">

**Comment by Jisenku** [comment]
> They still have token limit :( <img alt="Screenshot 2023-01-24 at 9 01 13 AM" width="783" src="https://user-images.githubusercontent.com/85253703/214314452-93cffbd4-7aca-4ccd-b480-058828ce9fdc.png">

Itś still a good amount higher though 😲

**Comment by Minesraft2** [comment]
I'll fix the script when I'm home, and no I can't do anything with the wheel. It's entirely server sided. When you get tokens normally the server tells the client how many tokens the wheel gave and then it shows that.

**Comment by Wilke000** [comment]
No it's not
It's still 500

**Comment by VillainsRule4000** [comment]
how does the wheel give 1k tho
like
find the endpoint for that and rip blooket!

**Comment by Jisenku** [comment]
> how does the wheel give 1k tho like find the endpoint for that and rip blooket!

yeah find an arbritary api endpoint 🤨

**Comment by Minesraft2** [comment]
The endpoint is the same as the daily rewards endpoint. The tokens from the wheel are chosen on the server and sent back

**Comment by Wilke000** [comment]
k ig that would make sense

**Comment by VillainsRule4000** [comment]
> The endpoint is the same as the daily rewards endpoint. The tokens from the wheel are chosen on the server and sent back

alright
well ben is smarter
ig

**Comment by Minesraft2** [comment]
Fixed

**Comment by Jisenku** [comment]
hell yeah :D
