### ISSUE TITLE
BUG: Script name

### ISSUE THREAD

**Issue by ColeCat119** [Minesraft2/Blooket-Cheats#272]
## Script
GUI both obfuscated and not

## The Problem
GUI not working

## How I ran it
javascript:

**Comment by Minesraft2** [comment]
Import bookmarks with the instructions in the tutorial folder. If that doesn't work then your school blocked javascript bookmarklets

**Comment by blooketadmin** [comment]
> Import bookmarks with the instructions in the tutorial folder. If that doesn't work then your school blocked javascript bookmarklets

we need javascript or our program goes down:)

**Comment by ColeCat119** [comment]
it worked, thx

**Comment by Minesraft2** [comment]
> > Import bookmarks with the instructions in the tutorial folder. If that doesn't work then your school blocked javascript bookmarklets
> 
> 
> 
> we need javascript or our program goes down:)
> 
> 

They can block javascript:
