### ISSUE TITLE
BUG: GUI.js daily coins

### ISSUE THREAD

**Issue by davidiguess** [Minesraft2/Blooket-Cheats#273]
## Script
Daily coins inside of the GUI
(Obfuscated)
## The Problem
It says failed to fetch extra user info

## How I ran it
Bookmarklets.html import

## Extra info
![image](https://user-images.githubusercontent.com/116284904/214348937-27f12572-d49b-43bf-85c0-5ca6a790ef3c.png)

**Comment by Minesraft2** [comment]
Fixed
