### ISSUE TITLE
IMPORTANT: CHEATS MAY NOT WORK!

### ISSUE THREAD

**Issue by VillainsRule4000** [Minesraft2/Blooket-Cheats#274]
Blooket is publishing several new updates.
This creates some issues.

**Known Broken Scripts**:
- add tokens/get daily rewards

Minesraft will fix these as soon as he can.
Do NOT open issues for any of the listed scripts.

**Comment by davidiguess** [comment]
ok

**Comment by VillainsRule4000** [comment]
close because minesraft has fixed
