### ISSUE TITLE
the rewards one is not working

### ISSUE THREAD

**Issue by thedoghey** [Minesraft2/Blooket-Cheats#276]
## Script
Which script is causing the problem?

## The Problem
The problem with the script (ie console errors):

## Method
(Bookmarks.html, javascript:, Console):

## Screenshots
Add any applicable screenshots (ie console if you have access):

**Make sure that no one else has already opened an issue about this script!**

**Comment by VillainsRule4000** [comment]
someone has already opened an issue.
learn to read, retard.

**Comment by Wilke000** [comment]
VILLIANS IS BACK! HES CALLING PEOPLE RETARDS AGAIN! YAY!

**Comment by Minesraft2** [comment]
Issue format not filled in + duplicate
