### ISSUE TITLE
BUG: All blooks 

### ISSUE THREAD

**Issue by StarbuckLovers** [Minesraft2/Blooket-Cheats#277]
Idk if u know but solos added the feature where you can choose your blook I only tested it in monster brawl if you use the all blook chest all the blooks apart from the normal common ones disappear kinda the opposite of the script name if that’s a better example

**Comment by Minesraft2** [comment]
Ah damn I actually made a fix and forgot to push it, I'll have to do it in the morning

**Comment by StarbuckLovers** [comment]
Oh that’s alright thanks! How does the blooket part work Im confused how to use it?
