### ISSUE TITLE
Use any blooket part 

### ISSUE THREAD

**Issue by StarbuckLovers** [Minesraft2/Blooket-Cheats#278]
Idk if I don’t know how to use it but it dosent seem to be working

**Comment by Minesraft2** [comment]
Stats page

**Comment by StarbuckLovers** [comment]
Didn’t work is there a specific part to go to

**Comment by Minesraft2** [comment]
It's for your custom blooks

**Comment by StarbuckLovers** [comment]
I know but it still dosent t like give me everything for the custom blook what’s meant to happen?

**Comment by Minesraft2** [comment]
Removed it because it got patched
