### ISSUE TITLE
BUG: Simulate Unlock Does not work

### ISSUE THREAD

**Issue by Blooket000** [Minesraft2/Blooket-Cheats#289]
## Script
Simulate Unlock

## The Problem
It does not work for some blooks

## How I ran it
Bookmarklets.html import

**Comment by StarbuckLovers** [comment]
It works fine it’s just that stuff like Tim the alien or chromas that aren’t in the box like purple astronaut won’t show up that could be a issue

**Comment by Minesraft2** [comment]
I know, those blooks will crash the page because they dont have a pack in the market
