### ISSUE TITLE
hi there is no question option so i went here so for add tokens what are wheel tokens

### ISSUE THREAD

**Issue by ThePineappleMan2013** [Minesraft2/Blooket-Cheats#290]

**Comment by Jisenku** [comment]
Blooket updated their daily token system, so now it is based on a wheel as well as daily tokens via games. For the average user this means you're probably going to get a bunch more tokens than normally. Refer to issue #269 for more technical info

**Comment by Minesraft2** [comment]
Daily wheel is done entirely on the server
