### ISSUE TITLE
IDEA: Custom Daily Amount?

### ISSUE THREAD

**Issue by Jisenku** [Minesraft2/Blooket-Cheats#291]
Could there be a way to completely ignore the Daily Bonus API and set a custom amount for it?

I remember a project from Astrum-Project that would completely ignore API webhooks to allow force cloning of avatars in VRChat, [https://github.com/Astrum-Project/AstralClone] would that be possible to ignore Blooket's API and trick the client-side to possibly giving whatever random amount you would want, or at least the maximum amount possible?

**Comment by Wilke000** [comment]
Dont think so

**Comment by Minesraft2** [comment]
When you get tokens at the end of a game, the api response gives an amount for the wheel. Even if you did change the value it wouldn't do anything
