### ISSUE TITLE
Website?

### ISSUE THREAD

**Issue by SnesLover22** [Minesraft2/Blooket-Cheats#292]
You all would do better if you had a website. It would lead more people to you, meaning more users. Even if its a github pages site it would be cool. maybe make a new account, so (Blooketcheats, blookhacks, whatever new account name you choose).github.io.

**Comment by Minesraft2** [comment]
bro what do you think im working on

**Comment by VillainsRule4000** [comment]
you got a domain?

**Comment by Minesraft2** [comment]
screw domains github pages 👍

**Comment by VillainsRule4000** [comment]
I assume you'll use the base for your acc
https://minesraft2.github.io

**Comment by Wilke000** [comment]
Lol

**Comment by SnesLover22** [comment]
> screw domains github pages 👍

yeahhhhhhhh github is the best

**Comment by Wilke000** [comment]
Ya GitHub!

**Comment by Wilke000** [comment]
The only problem with GitHub pages is that some schools block .io websites, like my school

**Comment by SnesLover22** [comment]
well too bad man

**Comment by VillainsRule4000** [comment]
github W
there's a way to use roots for your name (or org)

**Comment by Minesraft2** [comment]
https://minesraft2.github.io/Blooket-Cheats

**Comment by Wilke000** [comment]
YES!
