### ISSUE TITLE
BUG: gui.is

### ISSUE THREAD

**Issue by Blooket-hacker1002** [Minesraft2/Blooket-Cheats#293]
## Script
Which script is causing the problem

## The Problem
The problem with the script
## How I ran it
Bookmarklets.html import

the gui does not open

**Comment by Wilke000** [comment]
Skill issue

**Comment by Wilke000** [comment]
Works for me

**Comment by Blooket-hacker1002** [comment]
I am on a chromebook but it worked 2 days ago

**Comment by Blooket-hacker1002** [comment]
how did you upload it

**Comment by Wilke000** [comment]
Did u update it?

**Comment by Blooket-hacker1002** [comment]
yes

**Comment by Blooket-hacker1002** [comment]
I reinstalled it

**Comment by Wilke000** [comment]
Same as always, 2 finger tap view raw, save link as, import it

**Comment by Blooket-hacker1002** [comment]
do I use obfuscated or unobfuscated

**Comment by Wilke000** [comment]
Obfuscated

**Comment by Blooket-hacker1002** [comment]
ok

**Comment by Blooket-hacker1002** [comment]
the gui stiil does not work

**Comment by Blooket-hacker1002** [comment]
I click it when I go into blooket

**Comment by Wilke000** [comment]
Are the other hacks working?

**Comment by Blooket-hacker1002** [comment]
let me check

**Comment by Blooket-hacker1002** [comment]
no they are not

**Comment by Wilke000** [comment]
Try them with the console

**Comment by Blooket-hacker1002** [comment]
ok

**Comment by Blooket-hacker1002** [comment]
how do I do that?

**Comment by Blooket-hacker1002** [comment]
I am not that good with a computer

**Comment by Blooket-hacker1002** [comment]
nvm I opened it

**Comment by Wilke000** [comment]
Go to the code, copy it, and paste in in the console on blooket

**Comment by Blooket-hacker1002** [comment]
ok

**Comment by Wilke000** [comment]
Then your school probably blocked inspect, javascript, and bookmarklets

**Comment by Blooket-hacker1002** [comment]
ya ok thanks for the help

**Comment by Wilke000** [comment]
Np :)
