### ISSUE TITLE
BUG: Daily Coins is not working

### ISSUE THREAD

**Issue by AppiesWasTaken** [Minesraft2/Blooket-Cheats#294]
## Script
Get Daily Rewards

## The Problem
When I run the Daily Rewards script, it says error and doesn't work.

## How I ran it
Bookmarklets.html import, javascript: in url bar

**Comment by Minesraft2** [comment]
Make sure you use the latest version

**Comment by Wilke000** [comment]
Update it

**Comment by SnesLover22** [comment]
it works on the GUI (It finally works again)

**Comment by monkxy** [comment]
false issue couldn't reproduce
