### ISSUE TITLE
BUG: Script name every answer corect

### ISSUE THREAD

**Issue by wyatt3456** [Minesraft2/Blooket-Cheats#297]
## Script
Which script is causing the problem

## The Problem
The problem with the script

## How I ran it
Bookmarklets.html import, javascript: in url bar, or paste in console.

**Comment by wyatt3456** [comment]
when i do this it does not work and when it works when hosting it freezes your screen when you are in the game and breaks the game.

**Comment by wyatt3456** [comment]
can you pls fix it

**Comment by Minesraft2** [comment]
Remake the issue but actually fill in the information
