### ISSUE TITLE
Spoof doesn't work for spooky box or winter box

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#30]
Maybe this is impossible to do?
One last thing do the bookmarklets and GUI auto-update?

**Comment by fowntain** [comment]
No, they don't auto update. Refer to issue #27.

**Comment by fowntain** [comment]
@Minesraft2 Close

**Comment by Minesraft2** [comment]
bro didn't even let me comment

**Comment by Minesraft2** [comment]
bro had spidey sense that i was typing

**Comment by fowntain** [comment]
lmfaoo
