### ISSUE TITLE
Hacks not working

### ISSUE THREAD

**Issue by HiProGamingYT** [Minesraft2/Blooket-Cheats#318]
I know how to get the hacks to work but whenever I type "javascript: and code" in the URL and hit enter it shows nothing. I have no idea how to fix this and if its something just for me. Plz help

**Comment by urmom345** [comment]
I also have the same issue I am not sure how to fix. I thought it was a copy paste error but its not. The gui just does not open anymore.

**Comment by Minesraft2** [comment]
using the javascript: method won't work for the unobfuscated cheats. There's three things you can do:
1.  do it with the obfuscated ones
2. go to https://minesraft2.github.io/Blooket-Cheats and click on a cheat to copy the script or drag one into your bookmarks bar
3. import a bookmarklets.html file in your bookmarks manager.
If none of these work and you're on a school computer then they blocked bookmarklets and there's nothing we can do
