### ISSUE TITLE
Max tower stats doesn't work (Tower Defense)

### ISSUE THREAD

**Issue by davidiguess** [Minesraft2/Blooket-Cheats#32]
Whenever I try to use the max tower stats, the game breaks. I can't place anything, and the map breaks too.  The towers disappear as well.

Image of the map below if that helps

![download](https://user-images.githubusercontent.com/116284904/197429753-547ebe21-14a6-4e0a-82dd-dd44e3d1fd17.png)

**Comment by Minesraft2** [comment]
Fixed 👍
