### ISSUE TITLE
BUG: GUI

### ISSUE THREAD

**Issue by Lobster925** [Minesraft2/Blooket-Cheats#325]
## Script
[Blooket-Cheats](https://github.com/Minesraft2/Blooket-Cheats)/[unobfuscated](https://github.com/Minesraft2/Blooket-Cheats/tree/main/unobfuscated)/gui.js

## The Problem
I don't know if I'm doing something wrong with the new GUI script or if it's just not working.

## How I ran it
I copied the javascript in the URL bar for making a bookmark. Next, I tried to open the GUI in blooket but it did not open.

**Comment by muyahamadi** [comment]
why unobfuscated

**Comment by StarbuckLovers** [comment]
Device iOS or Laptop

**Comment by Minesraft2** [comment]
Don't use the unobfuscated versions with javascript: in the url bar, the lack of some semicolons will break it. Use the obfuscated version, import one of the bookmark files, or drag/copy the script from https://minesraft2.github.io/Blooket-Cheats

**Comment by Wilke000** [comment]
Yep

**Comment by Lobster925** [comment]
Thanks!!
