### ISSUE TITLE
AntiSuspend

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#33]
Does this prevent or undo? If it prevents could you make one to undo? Or is it impossible

**Comment by Minesraft2** [comment]
Undoing is not possible

**Comment by Hacker14674** [comment]
> Undoing is not possible

why is undoing not possible

**Comment by VillainsRule4000** [comment]
@Hacker14674
Wow, back it on up there. You call yourself a hacker and you don't understand simple API logic?

Bans are server-sided and managed by Ben. Editing these Bans would require database access which is not possible with any script. AntiSuspend simply blocks it from sending any requests TO ban, once the request has been sent, there's nothing you can do.

github is the best place to find dumb idiots

**Comment by Hacker14674** [comment]
honestly i just needed a name

**Comment by VillainsRule4000** [comment]
@l2vy7 you might find this funny

**Comment by Wilke000** [comment]
Undoing is not possible because it is server-sided
