### ISSUE TITLE
BUG: Gui

### ISSUE THREAD

**Issue by SuperBlazee** [Minesraft2/Blooket-Cheats#331]
## Script
Which script is causing the problem?

## The Problem
The problem with the script (ie console errors):

## Method
(Bookmarks.html, javascript:, Console):

## Screenshots
Add any applicable screenshots (ie console if you have access):

**Make sure that no one else has already opened an issue about this script!**

**Comment by SuperBlazee** [comment]
Gui is not loading i tried javascript are tell me what to put are how to put it

**Comment by Minesraft2** [comment]
Make a new issue and actually fill out the information, We can't find the problem if you don't tell us
