### ISSUE TITLE
getdailyrewards not working

### ISSUE THREAD

**Issue by LilKIngScripts** [Minesraft2/Blooket-Cheats#333]
## Script
Which script is causing the problem?

## The Problem
The problem with the script (ie console errors):

## Method
(Bookmarks.html, javascript:, Console):

## Screenshots
Add any applicable screenshots (ie console if you have access):

**Make sure that no one else has already opened an issue about this script!**

**Comment by Minesraft2** [comment]
Next time, actually fill out the issue template. And getDailyRewards is working, update your cheats
