### ISSUE TITLE
BUG: Script name     

### ISSUE THREAD

**Issue by Kevdagoa** [Minesraft2/Blooket-Cheats#341]
## Script
Which script is causing the problem?

## The Problem
The problem with the script (ie console errors):

## Method
(Bookmarks.html, javascript:, Console):

## Screenshots
Add any applicable screenshots (ie console if you have access):

**Make sure that no one else has already opened an issue about this script!**

**Comment by Kevdagoa** [comment]
It doesn't let me use the script it wont open

**Comment by Minesraft2** [comment]
Invalid issue, fill out the template so we know what to fix
