### ISSUE TITLE
BUG: gui

### ISSUE THREAD

**Issue by Kslithers** [Minesraft2/Blooket-Cheats#343]
## Script
Which script is causing the problem?

## The Problem
The problem with the script (ie console errors):

## Method
(Bookmarks.html, javascript:, Console):i type javascript:  then paste in the gui but it does not open the gui the old one works fine tho idk whats wrong it just wont open i do it thee same as the old version but it just don't work

## Screenshots
Add any applicable screenshots (ie console if you have access):

**Make sure that no one else has already opened an issue about this script!**

**Comment by Dparkmkdkkk** [comment]
Stop emailing

**Comment by Dparkmkdkkk** [comment]
But please stop I didn't mean to comment

**Comment by Believaboat** [comment]
what lol
