### ISSUE TITLE
SKID: jayden is still stealing your code

### ISSUE THREAD

**Issue by monkxy** [Minesraft2/Blooket-Cheats#344]
https://github.com/JaydenTD500/Blookett 

lmao

**Comment by monkxy** [comment]
https://github.com/DestroyerBlocked/Blooket-hacks-48

**Comment by monkxy** [comment]
also that
he disables issues

**Comment by Minesraft2** [comment]
DMCA sent 👍

**Comment by monkxy** [comment]
> DMCA sent 👍

Consider reporting his profile, I've sent over 6 DMCA takedowns to Jayden alone, he also posts malicious code on his repo.

**Comment by VillainsRule4000** [comment]
> > DMCA sent 👍
> 
> Consider reporting his profile, I've sent over 6 DMCA takedowns to Jayden alone, he also posts malicious code on his repo.

He is actually an idiot, either he's underage w/o an understanding of shit or he actually is serious about stealing code and knows what he's doing.
I'm guessing the former, but I wouldn't be too shocked if he turned out to be someone else.
