### ISSUE TITLE
Answer Points

### ISSUE THREAD

**Issue by GoUDino** [Minesraft2/Blooket-Cheats#345]
### Gamemode

Global

### Function

It makes 1 answer = 400 for easy tokens and grinding stats.

**Comment by Floragato** [comment]
add daily rewards exists tho

**Comment by Minesraft2** [comment]
I'll make it if you give a good reason not to use [getDailyRewards](https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/getDailyRewards.js) instead

**Comment by Minesraft2** [comment]
Gone stale in favor for [getDailyRewards](https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/getDailyRewards.js)
