### ISSUE TITLE
BUG: YOUR REMINDER

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#347]
### Script

gui.js

### Problem

Sell cheap duplicates
Also you should add a looping sell cheap duplicates

### Method

- [ ] Imported Bookmarklets.html
- [ ] Put 'javascript:(code)' in the url bar or a bookmark
- [ ] Pasted script into console

**Comment by Minesraft2** [comment]
not even a bug wth

**Comment by Wilke000** [comment]
Bro you told me to remind you in “6 and a half hours"

**Comment by Wilke000** [comment]
This is your reminder

**Comment by Minesraft2** [comment]
oh

**Comment by Wilke000** [comment]
Could you do an auto sell cheap blooks on open?

**Comment by Wilke000** [comment]
Ah cool cool
