### ISSUE TITLE
Sim Unlock won't let me type in a pack name

### ISSUE THREAD

**Issue by Zinx12** [Minesraft2/Blooket-Cheats#351]
### Script

simulateUnlock.js

### Problem

If I use Simulate Unlock it will pop up "What pack do you wanna simulate opening? (Case Sensitive)" Every time I type in Space Pack it doesn't work and just puts the pop up back again.  

### Method

- [ ] Imported Bookmarklets.html
- [ ] Put 'javascript:(code)' in the url bar or a bookmark
- [X] Pasted script into console

**Comment by Minesraft2** [comment]
You're supposed to put in a blook

**Comment by Minesraft2** [comment]
Simulate unlock is a bit buggy, I'll remove the re-ask thing

**Comment by Zinx12** [comment]
Oh I was confused, Thank You!

**Comment by Minesraft2** [comment]
I made a new simulate pack script for this
