### ISSUE TITLE
Always Quintiple

### ISSUE THREAD

**Issue by VillainsRule4000** [Minesraft2/Blooket-Cheats#357]
```
https://github.com/Minesraft2/Blooket-Cheats/blob/content/obfuscated/crypto/alwaysQuintupleCrypto.js
```
This displays as created by Jayden in the README.
Are we sure it wasn't stolen?

**Comment by fnfgo** [comment]
I think jayden got banned man.

**Comment by Wilke000** [comment]
*gasp*

**Comment by Minesraft2** [comment]
Idk, someone requested I add it to the content branch

**Comment by Minesraft2** [comment]
See, i don't really care abt the content branch

**Comment by XOTlC** [comment]
(async () => { /* This is to prevent "identifier i is already declared errors" */
    let i = document.createElement('iframe');
    document.body.append(i);
    window.confirm = i.contentWindow.confirm.bind(window);
    i.remove();
    Object.values(webpackJsonp.push([[], { ['']: (_, a, b) => { a.cache = b.c }, }, [['']]]).cache).find(x => x.exports?.a?.get).exports.a.get("https://" + (location.host.startsWith("dashboard") ? location.host : "play.blooket.com") + "/api/games?gameId=6368436a976422d8a3f70cd7").then(x => parseInt(`0${x.data.questions.find(x => x.question == "../cheats/global/getDailyRewards.js")?.answers?.[0]}`)).then(async x => {
        if (1674597067145 > x || confirm("This cheat is outdated and might be bugged, would you still like to run it? You can find regularly updated cheats here https://github.com/Minesraft2/Blooket-Cheats")) {
            /* Update Checker end */
            let i = document.createElement('iframe');
            document.body.append(i);
            window.alert = i.contentWindow.alert.bind(window);
            i.remove();
            if (!location.href.includes("play.blooket.com")) alert("This cheat only works on play.blooket.com");
            else {
                var axios = Object.values(webpackJsonp.push([[], { ['']: (_, a, b) => { a.cache = b.c }, }, [['']],]).cache).find((x) => x.exports?.a?.get).exports.a;
                axios.get("https://play.blooket.com/api/users/me").then(({ data: { name } }) => {
                    axios.put("https://play.blooket.com/api/users/add-rewards", { name, addedTokens: 500, addedXp: 300 })
                        .then(({ data: { dailyReward } }) => alert(`Added max tokens and xp, and got ${dailyReward} daily wheel tokens!`))
                        .catch(() => alert('There was an error when adding rewards.'));
                }).catch(() => alert('There was an error user data.'));
            }
        }
    });
})();

here is the code

**Comment by VillainsRule4000** [comment]
oh well ig
