### ISSUE TITLE
BUG: gui.js

### ISSUE THREAD

**Issue by SuperBlazee** [Minesraft2/Blooket-Cheats#359]
### Script

gui.js

### Problem

It does not show the gui 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Extra Info

I try it some many times and it dosent work

**Comment by SuperBlazee** [comment]
gui dont pop up

**Comment by Minesraft2** [comment]
Are you using the unobfuscated version? You can't paste that into a bookmarklet

**Comment by Kevdagoa** [comment]
Yes i also faced the same thing

**Comment by somerandompersonhere** [comment]
For me its still working fine with the obfuscated (bookmark)

**Comment by LeozaCEO2** [comment]
In obfuscated it does not work for me when I put javascript:(code) in the url bar

**Comment by Blooketetc** [comment]
works for me

**Comment by LeozaCEO2** [comment]
Which method did you use?

**Comment by LeozaCEO2** [comment]
Only the bookmarklets version is currently working for me.

**Comment by LeozaCEO2** [comment]
If the javascript:(code) is not working I recommend using bookmarklets.

**Comment by SuperBlazee** [comment]
javascript

**Comment by SuperBlazee** [comment]
no im not

**Comment by SuperBlazee** [comment]
wait yes i am

**Comment by SuperBlazee** [comment]
but still no wrok

**Comment by Greenlio** [comment]
unable to repro
