### ISSUE TITLE
BUG: gui.js

### ISSUE THREAD

**Issue by Kevdagoa** [Minesraft2/Blooket-Cheats#360]
### Script

Gui.js

### Problem

Doesn't open when i go on to blooket

### Method

Put 'javascript:(code)' in the url bar or a bookmark

**Comment by Kevdagoa** [comment]
Please fix it your the only person i sub because you actually have blooket hacks

**Comment by Minesraft2** [comment]
Dont use unobfuscated with javascript: method

**Comment by Kevdagoa** [comment]
No I'm using obfuscated with the javascript: method I don't use unofuscated

**Comment by Kevdagoa** [comment]
it still doesn't work, but I'm in school rn i can't talk all the time but il try to see your messages

**Comment by Kevdagoa** [comment]
no

**Comment by Minesraft2** [comment]
Try dragging the GUI from https://minesraft2.github.io/Blooket-Cheats/#Default to your bookmarks bar

**Comment by Kevdagoa** [comment]
I just tried it it doesn't work

**Comment by Minesraft2** [comment]
Try typing `javascript:alert('test')` in the url bar on this github page, tell me what happens

**Comment by Kevdagoa** [comment]
hmmm, it dose nothing

**Comment by Kevdagoa** [comment]
i tried it again it dose not work

**Comment by Minesraft2** [comment]
That means your school blocked javascript:, which is pretty much the only way aside from inspect element console to run the cheats

**Comment by Kevdagoa** [comment]
hmmm, let me see another i can use

**Comment by Kevdagoa** [comment]
il tell u if it works

**Comment by Kevdagoa** [comment]
oh man

**Comment by Kevdagoa** [comment]
i guess it did block

**Comment by Kevdagoa** [comment]
well, thanks for your help I appreciate it I'll still follow you and subscribe to you

**Comment by fnfgo** [comment]
> well, thanks for your help I appreciate it I'll still follow you and subscribe to you
you can use erudas inspect element to do it

**Comment by huds631** [comment]
were is the GUI?

**Comment by Kevdagoa** [comment]
> > well, thanks for your help I appreciate it I'll still follow you and subscribe to you
> > you can use erudas inspect element to do it

i can't use inspect mode

**Comment by Minesraft2** [comment]
I'll try to find some way eventually, but the chances of it are really low, sorry.

**Comment by fnfgo** [comment]
> > > well, thanks for your help I appreciate it I'll still follow you and subscribe to you
> > > you can use erudas inspect element to do it
> 
> i can't use inspect mode

no this bookmarklet
javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })();
