### ISSUE TITLE
BUG: (Get Daily Rewards)

### ISSUE THREAD

**Issue by cupcake2048** [Minesraft2/Blooket-Cheats#362]
### Script

getdailyreward.js

### Problem

It just does nothing

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

**Comment by Minesraft2** [comment]
Unobfuscated doesn't work for javascript:<code>

**Comment by Minesraft2** [comment]
Follow one of the methods in the [How to use drodown](https://github.com/Minesraft2/Blooket-Cheats#how-to-use)
