### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by somerandompersonhere** [Minesraft2/Blooket-Cheats#365]
### Script

resetPlayersGold.js and resetAllGold.js

### Problem

when I use either of them it wont work. I tired to reset all gold. wont work. tried to reset one persons gold with resetPlayersGold. wont work. Im not sure if its just me tho. Everything else works great. 

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by Minesraft-Is-Best** [comment]
yeah its buggy

**Comment by Greenlio** [comment]
both are still in beta and use at your own risk

**Comment by Minesraft2** [comment]
resetAllGold is in testing still, but resetPlayersGold shouldn't be broken, I'll look into it later today.

**Comment by somerandompersonhere** [comment]
ok. thanks

**Comment by mungK11** [comment]
Minesraft, Glixzy doesn't live in Russia or Germany

**Comment by mungK11** [comment]
he just is making a "vpn"

**Comment by Minesraft2** [comment]
I know

**Comment by Wilke000** [comment]
Wrong issue
