### ISSUE TITLE
BUG: (simulate unlock)

### ISSUE THREAD

**Issue by arazzy** [Minesraft2/Blooket-Cheats#378]
### Script

simulateunlock.js

### Problem

I cant simulate chromas yet

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

nope

**Comment by Minesraft2** [comment]
You can only simulate blooks you can get from a pack in the market that day, meaning the only chromas you can simulate are the colored astronaut of the day, teal platypus, the ice chromas, and the rainbow panda

**Comment by arazzy** [comment]
oh thank you!
