### ISSUE TITLE
Just a question - Obfuscation

### ISSUE THREAD

**Issue by CharaTheFallen** [Minesraft2/Blooket-Cheats#383]
How do you do the Obfuscation?
Is there a way to reverse it?
I'm asking bc I have some obfuscated code I'm trying to translate it.

**Comment by VillainsRule4000** [comment]
Obfuscation is with [javascript-obfuscator](https://github.com/javascript-obfuscator/javascript-obfuscator) @ [npmjs](https://npmjs.com/package/javascript-obfuscator).
In the future, for questions, go to the Discussions.

In my opinions, reversing obfuscation is disrespectful to the hack creator, who has chosen to keep it private for a reason.

**Comment by CharaTheFallen** [comment]
Alright thank you!
