### ISSUE TITLE
Write: ('Only blooks that are in the Blooket shop at the current time can be simulated')

### ISSUE THREAD

**Issue by LeozaCEO2** [Minesraft2/Blooket-Cheats#385]
### Gamemode

global

### Function

Some blook unlock simulations do not work because they are not in the Blooket shop. You should write: (The only blooks that can be simulated are the ones that are in the item shop at the current time because some people will think that the hack is broken.

**Comment by VillainsRule4000** [comment]
@Wike000 opened #388 for this.
You can close this issue and await results of the PR.
