### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by EliteManKindTheFirst** [Minesraft2/Blooket-Cheats#387]
### Script

getDailyRewards.js

### Problem

Both of them do not work at all after one time.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by LeozaCEO2** [comment]
Blooket only allows you to get 500 tokens at a time. If you save your tokens, you can add up more tokens and buy anything you want.

**Comment by LeozaCEO2** [comment]
you should probably close this issue as it isn't much of an issue.

**Comment by EliteManKindTheFirst** [comment]
No, got 500 then after they were spent it wouldn't let me get more.

**Comment by VillainsRule4000** [comment]
@Minesraft2 close
you can earn max 500 tokens per day. It's not called addTokens.js, it's called getDailyRewards.js.

**Comment by VillainsRule4000** [comment]
once your daily rewards have been claimed, wait until the next day lmfao
you're blind
