### ISSUE TITLE
BUG: (resetplayersgold.js)

### ISSUE THREAD

**Issue by arazzy** [Minesraft2/Blooket-Cheats#390]
### Script

resetplayergold.js

### Problem

It wont work when i try to reset one persons gold and everyones but it might be just me

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by MommyMcblooket** [comment]
try his obfuscated gui

**Comment by MommyMcblooket** [comment]
[https://github.com/Minesraft2/Blooket-Cheats/blob/main/obfuscated/gui.js]

**Comment by MommyMcblooket** [comment]
[https://github.com/Minesraft2/Blooket-Cheats/blob/main/obfuscated/gui.js](url)

**Comment by frantene** [comment]
The Link You Provided Wasnt Available.
plus, that code was in mobilegui? right?

**Comment by LeozaCEO2** [comment]
his method was obfuscated

**Comment by LeozaCEO2** [comment]
Let me check if the gui.js vversion works.

**Comment by Minesraft2** [comment]
And I can deobfuscate it

**Comment by LeozaCEO2** [comment]
i know some ways to deobfuscate too

**Comment by LeozaCEO2** [comment]
join my blooket game. code:2325189

**Comment by Wilke000** [comment]
No delete that and never advertise a code again

**Comment by LeozaCEO2** [comment]
I tested it myself on gui.js. I don't see how it would change anything anyway, but it did not work.

**Comment by LeozaCEO2** [comment]
I posted that code to test resetplayersgold.js

**Comment by Greenlio** [comment]
Inactive
