### ISSUE TITLE
IDEA: Host Scripts; End game, Kick player(s), & Flood game [again

### ISSUE THREAD

**Issue by SharkyMantisGD** [Minesraft2/Blooket-Cheats#393]
### Gamemode

Global

### Function

Here are the ideas:

End Game- End live Blooket game.

Kick player(s)- Kicks a player participating in the live Blooket game.

Flood game- Floods live Blooket game with x amount of bots (player choice) and the bots name (player choice).

**Comment by Greenlio** [comment]
Host scripts are simply not good as they require the teacher / host to run them
