### ISSUE TITLE
IDEA: bring back use any blook parts

### ISSUE THREAD

**Issue by dvrkiexkayla56** [Minesraft2/Blooket-Cheats#394]
### Gamemode

global

### Function

it was in global 2 i think and it was very handy it would be nice to bring it back

**Comment by dvrkiexkayla56** [comment]
For the gui

**Comment by Wilke000** [comment]
I don’t think you can do it anymore
I think it sends a confirmation to the blooket servers to check to see if you have the blook parts

**Comment by Minesraft2** [comment]
It got patched.
That or it never worked and I checked it wrong

**Comment by dvrkiexkayla56** [comment]
It worked

**Comment by arazzy** [comment]
![Screenshot 2023-02-10 15 32 20](https://user-images.githubusercontent.com/124743468/218203021-1be9459f-5178-45c1-b718-9db8bd4093a2.png)
 still working

**Comment by Greenlio** [comment]
Doesn't work, returns 'Invalid Custom Blook' if you don't own the part
