### ISSUE TITLE
What happened to the support server?

### ISSUE THREAD

**Issue by Yerthesweat** [Minesraft2/Blooket-Cheats#398]

**Comment by monkxy** [comment]
A user named Barcode reported Jod's server and sadly got it removed from Discord.

**Comment by Minesraft2** [comment]
Not gone, just hidden until I get my account back

**Comment by Minesraft2** [comment]
ok discord said no so I just made another one

**Comment by VillainsRule4000** [comment]
> ok discord said no so I just made another one

wow
discord is an L
wasn't it on the community page?

**Comment by Minesraft2** [comment]
yea it was

**Comment by Minesraft2** [comment]
the discord was just for support tho, if anyone needs any they can just join again

**Comment by VillainsRule4000** [comment]
> yea it was

shesh
discord is an L
ill make confidence advertise your new server fr

**Comment by VillainsRule4000** [comment]
> the discord was just for support tho, if anyone needs any they can just join again

it was also for my dank memer robbing !!
