### ISSUE TITLE
autobuy doesnt work :(

### ISSUE THREAD

**Issue by DummyPotato** [Minesraft2/Blooket-Cheats#4]
basically the title, doesnt give the error, but at the same time does nothing

**Comment by DummyPotato** [comment]
all it does, is says this:  (0ms) Results:  Im doing it all correctly, openning the console and pasting it in.

**Comment by Minesraft2** [comment]
What box and amount are you putting in?

**Comment by DummyPotato** [comment]
im just putting 1 or 2 to test it

**Comment by Minesraft2** [comment]
And you have enough tokens?

**Comment by Minesraft2** [comment]
And using the newest version?

**Comment by DummyPotato** [comment]
yup

**Comment by Minesraft2** [comment]
Is it saying anything in the networt tab?

**Comment by DummyPotato** [comment]
justhttps://api.blooket.com/api/users

**Comment by Minesraft2** [comment]
and what box?

**Comment by DummyPotato** [comment]
i tried space, ice monster, and dino

**Comment by Minesraft2** [comment]
are you running it on the dashboard.blooket.com domain?

**Comment by DummyPotato** [comment]
ye

**Comment by Minesraft2** [comment]
are you using the one on the gui or the stand alone cheat?

**Comment by DummyPotato** [comment]
alone

**Comment by Minesraft2** [comment]
Join the support server it'll be easier for me to talk there

**Comment by DummyPotato** [comment]
ill do it after school tho, i get out soon

**Comment by DummyPotato** [comment]
I'm quite buddy today so I'll be able to msg u  later today

**Comment by DummyPotato** [comment]
*bussy
