### ISSUE TITLE
UI Contents cut off

### ISSUE THREAD

**Issue by wilburcoding** [Minesraft2/Blooket-Cheats#40]
I am unable to view part of the UI Contents 
Please make it so I can scroll in the UI
![image](https://user-images.githubusercontent.com/66228004/197889945-d1cd7b48-6445-4081-ba8e-ebaa37baec8b.png)

**Comment by fowntain** [comment]
I'm having the same issue

**Comment by Minesraft2** [comment]
For now try just zooming out of the page a bit

**Comment by Wilke000** [comment]
im on a 13.3 inch it is fine for me but @Minesraft2 you might want to add a scrolling thing if you can

**Comment by Wilke000** [comment]
Fixed!
