### ISSUE TITLE
gui.js not working

### ISSUE THREAD

**Issue by ThePineappleMan2013** [Minesraft2/Blooket-Cheats#401]
### Script

gui.js

### Problem

just says nothing

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

h

**Comment by LeozaCEO2** [comment]
works fine for me

**Comment by LeozaCEO2** [comment]
are u using the most recent version?

**Comment by darknight413** [comment]
i can not get it to work nether

**Comment by Minesraft2** [comment]
Unable to reproduce, try another method to run the scripts
