### ISSUE TITLE
Simulating Blooks

### ISSUE THREAD

**Issue by LeozaCEO2** [Minesraft2/Blooket-Cheats#404]
### Script

simulateunlock.js

### Problem

None of the chromas simulate, including the ones inside the item shop at the current time.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

There was another issue for this but I thought only the chromas in the item shop at the current time work. Unfortunately, none of them do.

**Comment by BrandonBman12313** [comment]
You have to make sure that both words have the first letter capital. And if there is two words put a space.

**Comment by Minesraft2** [comment]
Unable to reproduce, try another method of running the script.

**Comment by OGBlooketCheater** [comment]
#699 funne 69
