### ISSUE TITLE
IDEA: ADD FOR TOWER DEFENCE 2 AND I GIVE 25 $$$$$

### ISSUE THREAD

**Issue by amkoolok** [Minesraft2/Blooket-Cheats#411]
### Gamemode

tower defence 2

### Function

e

**Comment by amkoolok** [comment]
I bet 25$$$ you cant make hacks for it!!!!!!!!!!!!!!

**Comment by Minesraft2** [comment]
I already am, you're like the 7th person

**Comment by rbcoder117** [comment]
@Minesraft2 at this point they are just begging to give you money lol
