### ISSUE TITLE
IDEA: Find Pin

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#416]
### Gamemode

Global

### Function

Finds a game pin and automatically goes to the play.blooket.com with the pin entered

**Comment by VillainsRule4000** [comment]
this would go into the content branch and likely be a nodejs project lol
blooket pin finders HAVE existed in the past

**Comment by Minesraft2** [comment]
I wont do it

**Comment by Minesraft2** [comment]
And i doubt it's even possible now thanks to the new game joining changes

**Comment by VillainsRule4000** [comment]
> And i doubt it's even possible now thanks to the new game joining changes

what changed?

**Comment by Minesraft2** [comment]
You make a request to firebase everytime you join, host, or update a game

**Comment by Wilke000** [comment]
> I wont do it

Why not

**Comment by Minesraft2** [comment]
I have a pin finder already, but it's too slow

**Comment by Wilke000** [comment]
Well put it on the content branch, people don't care how fast it is. I don't care how fast it is, I just want to join random people and troll 😁

**Comment by BlooketLover1** [comment]
Yeah I agree

**Comment by Wilke000** [comment]
> I have a pin finder already, but it's too slow

So no putting it on the content branch?
