### ISSUE TITLE
Frenzy

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#42]
When I click frenzy in the fishing, nothing happens

**Comment by Wilke000** [comment]
Still broken... sorry for reminding and sounding impatient

**Comment by Minesraft2** [comment]
No I understand, I've been looking at this multiple times and procrastinating it.

**Comment by Wilke000** [comment]
Ok lol thank you for telling me that

**Comment by codemaster123puppy** [comment]
LOL

**Comment by Minesraft2** [comment]
Fixed 👍
