### ISSUE TITLE
Fishing Frenzy Always Frenzy

### ISSUE THREAD

**Issue by Yerthesweat** [Minesraft2/Blooket-Cheats#421]
### Gamemode

Fishing frenzy

### Function

A toggleable option to continuously start frenzy

**Comment by LeozaCEO2** [comment]
Why can't you just spam the frenzy thing in the hacks?

**Comment by VillainsRule4000** [comment]
implemented in #443

**Comment by Greenlio** [comment]
[Implemented](https://github.com/Minesraft2/Blooket-Cheats/commit/c322c7a1e8b509536a3cabeac05bb12ebbfd5d38) to [Content](https://github.com/Minesraft2/Blooket-Cheats/blob/content) [in this commit.](https://github.com/Minesraft2/Blooket-Cheats/blob/content/unobfuscated/fishing/alwaysFrenzy.js)
