### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by Noahissobad** [Minesraft2/Blooket-Cheats#423]
### Script

Bookmarklets.html

### Problem

I've saved the code and in your tutorial it says the import it into a bookmark using setting and shit, ( am on chrome ) Doesn't show up as that thing you had in yours, all it says is save as again, copy, and inspect, So fix ur tutorial for the newest 2023 chrome updates

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by Minesraft2** [comment]
In the tutorial it says OR do ctrl shift o and then import

**Comment by Minesraft2** [comment]
Tutorial isn't broken, just read through it properly
