### ISSUE TITLE
BUG: TD2 cheats

### ISSUE THREAD

**Issue by Wsy1524** [Minesraft2/Blooket-Cheats#425]
### Script

all

### Problem

None of the td2 cheats work

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

**Comment by Wilke000** [comment]
What a failure.

**Comment by Wilke000** [comment]
Use the obfuscated cheats for the javascript:(code)
use the unobfuscated cheats in the console
