### ISSUE TITLE
BUG: Monster Brawl

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#426]
### Script

all monster brawl scripts

### Problem

When you run the cheats, later on in the game it just pauses and you can't unpause it. You lose your progress and thats it.

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by CrypticLucid** [comment]
it happens when the game runs out of upgrades to give you i think

**Comment by Blooket000** [comment]
When the game runs out of upgrades to give y ou it will just pause and you cant move anymore.

**Comment by Minesraft2** [comment]
that's why you shouldn't give yourself every ability

**Comment by Wilke000** [comment]
> When the game runs out of upgrades to give y ou it will just pause and you cant move anymore.

yep that's what happens

**Comment by HiProGamingYT** [comment]
yep you can have everything but when they are all maxed it glitches and dies

**Comment by orangemonkey01** [comment]
It used to work cause i did it

**Comment by Wilke000** [comment]
So you're just not going to fix it? Also, that happens even if you just use one hack

**Comment by Minesraft2** [comment]
It happens when there's no abilities for you to upgrade, there's nothing I can do about it rn
