### ISSUE TITLE
IDEA: get all answers correct 

### ISSUE THREAD

**Issue by FennecFoxer** [Minesraft2/Blooket-Cheats#427]
### Gamemode

any

### Function

all answers correct should be all answers correct I do not want to have to keep reentering the code just to get one answer correct literally all answers correct just put by putting the code in one time

**Comment by VillainsRule4000** [comment]
ill look at this

**Comment by VillainsRule4000** [comment]
you can find this in the intervals folder of global already, use autoAnswer

**Comment by Greenlio** [comment]
autoAnswer in GUI or Intervals
