### ISSUE TITLE
anti suspend 

### ISSUE THREAD

**Issue by Hacker14674** [Minesraft2/Blooket-Cheats#43]
anti suspend does not work

**Comment by Minesraft2** [comment]
elaborate

**Comment by Hacker14674** [comment]
wuz elabarate mean

**Comment by VillainsRule4000** [comment]
@Hacker14674 :skull: are you more than 5 years old?

**Comment by Hacker14674** [comment]
yessir

**Comment by Hacker14674** [comment]
how old u

**Comment by Minesraft2** [comment]
what do you mean anti suspend isn't working

**Comment by Minesraft2** [comment]
cuz anti suspend just prevents suspensions, not undoes them

**Comment by Hacker14674** [comment]
bruh im dum

**Comment by Wilke000** [comment]
Yes u are

**Comment by Hacker14674** [comment]
ima be honest i just wanted to troll so i made a account. and really i dont know a single thing about coding and stuff, and im currently in school
