### ISSUE TITLE
They just dont work

### ISSUE THREAD

**Issue by Camgames1256** [Minesraft2/Blooket-Cheats#430]
### Script

gui.js

### Problem

Even after I do javascript: Code in bookmark bar it doesn't work. It has been working until I got the TD2 Cheats

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Minesraft2** [comment]
The gui is still working, so it's likely an issue on your end, maybe the way you're running it because javascript:(code) isn't really reliable

**Comment by Greenlio** [comment]
they do; skill issue (stale, cant repro)
