### ISSUE TITLE
IDEA: Battle Royale Hacks overall.

### ISSUE THREAD

**Issue by shibetheinu** [Minesraft2/Blooket-Cheats#432]
### Gamemode

Battle Royale

### Function

Instantly answer questions, or get back all energy.

**Comment by Wilke000** [comment]
Minescraft can't find the code to change for battle royale so for now, it can't be hacked
Also next time, LOOK AT PREVIOUS ISSUES

**Comment by Greenlio** [comment]
Not possible - stateNode is very restrictive in Battle Royale.
