### ISSUE TITLE
IDEA: Simulate Unlock Update

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#438]
### Gamemode

Global

### Function

Update that finds if you have the blook you simulate unlocked, then changes it to say new or not

**Comment by VillainsRule4000** [comment]
as well as accurate rates, all rates display 0%

**Comment by Wilke000** [comment]
> as well as accurate rates, all rates display 0%

Huh? What does that mean

**Comment by VillainsRule4000** [comment]
> > as well as accurate rates, all rates display 0%
> 
> Huh? What does that mean

at the bottom of the unlock, it shows the drop rate
all drop rates in the sim show 0%

**Comment by Wilke000** [comment]
> > > as well as accurate rates, all rates display 0%
> > 
> > 
> > Huh? What does that mean
> 
> at the bottom of the unlock, it shows the drop rate all drop rates in the sim show 0%

No, like it will fetch your blooks, see if you have the one you simulated, then say new or not

**Comment by Wilke000** [comment]
OHHHHHHHH sry I didn’t get that

**Comment by Greenlio** [comment]
![image](https://user-images.githubusercontent.com/62725108/219551370-cfaa92c1-66a1-41a3-9165-3e8236f07446.png)
?
