### ISSUE TITLE
Phantom king

### ISSUE THREAD

**Issue by Ghhuyft** [Minesraft2/Blooket-Cheats#439]
### Gamemode

Getting the phantom king

### Function

What Blook will you choose to see open?

**Comment by Ghhuyft** [comment]
Gfggjzg

**Comment by VillainsRule4000** [comment]
not possible
stop being retarded
'

**Comment by germanSEA** [comment]
The get daily rewards button on the GUI doesn't work for some reason.

**Comment by Greenlio** [comment]
> The get daily rewards button on the GUI doesn't work for some reason.

Read the README and related files - it only works on specific URLs.

> What Blook will you choose to see open?

You can spoof the blook by using the spoofUnlock script (I think it's called that), but you can't choose the outcome of a pack.

**Comment by xxclipso** [comment]
We’re is it

**Comment by LeozaCEO2** [comment]
It works for me. Maybe u just tried it multiple times in a day. Blooket only allows 500 tokens per day with extra daily wheel tokens.
