### ISSUE TITLE
IDEA: Targeted Use Any Blook

### ISSUE THREAD

**Issue by hello799** [Minesraft2/Blooket-Cheats#445]
### Gamemode

Global

### Function

Use any blook except it is targeted to single or multiple selected blooks.

**Comment by VillainsRule4000** [comment]
wdym lmfao

**Comment by VillainsRule4000** [comment]
this kid makes as much sense as your mother on 🌱

**Comment by hello799** [comment]
choose which blook to unlock

**Comment by VillainsRule4000** [comment]
> choose which blook to unlock

for exactly what purpose lmfao

**Comment by VillainsRule4000** [comment]
just unlock them all; no issue

**Comment by Lukedawg86** [comment]
Can you unblock all blooks

**Comment by Wilke000** [comment]
no.
