### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by vipira** [Minesraft2/Blooket-Cheats#448]
### Script

Unknown, Though i assume its one of the monster brawl cheats.

### Problem

After using the monster brawl cheats a couple times, it turns the font size on the website incredibly small. It gets progressively smaller every time I use a cheat, but it only happens when i use one of the monster brawl subscript.

The font size only gets smaller when i try playing monster brawl. It doesn't happen to any other part of the site; It just makes that specific game virtually unplayable.

### Method

Imported Bookmarklets.html

### Type

Obfuscated

### Extra Info

![image](https://user-images.githubusercontent.com/125693569/219760088-a76b5019-b25a-435b-958c-f12ccb7898ce.png)
![image](https://user-images.githubusercontent.com/125693569/219760905-d3c41236-f21a-4518-9c82-adfdfc62aec3.png)

**Comment by Wilke000** [comment]
I have a comment: MR CLEAN MR CLEAN

**Comment by Minesraft2** [comment]
are you sure you're not just zooming out on accident?

**Comment by Blooketetc** [comment]
MR Cleast
