### ISSUE TITLE
BUG: Readme

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#449]
### Script

readme.md

### Problem

Look at screenshot

### Type

Unobfuscated

### Extra Info

<img width="790" alt="Screenshot 2023-02-17 at 3 21 06 PM" src="https://user-images.githubusercontent.com/85253703/219785359-548e7ddc-9481-40b3-b21b-a1c1024e03d2.png">

**Comment by Minesraft2** [comment]
Cry about it

**Comment by Wilke000** [comment]
Im not complaining im just saying that that’s happening
It looks weird
