### ISSUE TITLE
Blizzard Pack for simulateUnlock

### ISSUE THREAD

**Issue by marfanis788** [Minesraft2/Blooket-Cheats#45]
Is it possible to add Blizzard blooks to the cheat?

**Comment by Wilke000** [comment]
Yea I was just thinking about that

**Comment by fowntain** [comment]
You probably should have opened this in discussions under ideas

**Comment by Minesraft2** [comment]
No it's a bug

**Comment by Minesraft2** [comment]
They were supposed to be added but i guess i accidentally filtered them out too

**Comment by TheBobCreator** [comment]
wouldnt it work if the blizzard pack was in the market?

**Comment by Minesraft2** [comment]
Actually no I cannot, because the blizzard pack doesn't have a pack image yet.

**Comment by Wilke000** [comment]
Make one
