### ISSUE TITLE
Content Branch

### ISSUE THREAD

**Issue by BlooketLover1** [Minesraft2/Blooket-Cheats#453]
### Script

Always Frenzy and Auto Win Delay Unbofuscated

### Problem

it won’t work in bookmarklets because there’s missing semi colones so it won’t work in bookmarklets so I think u should make a obfuscated version so people on mobile and people who use bookmarks can use it

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

**Comment by Minesraft2** [comment]
Find a bookmarklet generator online or something

**Comment by Minesraft2** [comment]
[This one](https://mrcoles.com/bookmarklet/) seems to be working
