### ISSUE TITLE
gui.js

### ISSUE THREAD

**Issue by QuandaIeDingle** [Minesraft2/Blooket-Cheats#454]
### Gamemode

tower defense 2

### Function

lists all the hacks work for that gamemode

also, instead of having to scroll for hours (2-10 minutes) why not make the vertical scroll short (like 5-10 lines) but have the horizontal scroll go forever and add a extra line to vertical scroll so you can copy the whole thing.

this would be a massive improvement,
thanks!

**Comment by Minesraft2** [comment]
? Where?

**Comment by Blobby3892** [comment]
@Minesraft2 check your DMs on discord

**Comment by QuandaIeDingle** [comment]
uh

**Comment by QuandaIeDingle** [comment]
in the unobfuscated/obfuscated, go to gui . js and then do that.
question: where?
answer: in the code space that goes down to hell

**Comment by QuandaIeDingle** [comment]
because you know... it goes forever

**Comment by Minesraft2** [comment]
i have no idea what you're talking about

**Comment by orangemonkey01** [comment]
Just click the copy button

**Comment by BlooketLover1** [comment]
@Minesraft2 hes whining about how long it takes to copy paste the code just click the copy paste button??

**Comment by LeozaCEO2** [comment]
yeah, he's probably looking at the raw or something. Just click the copy button on top of the code on the respiratory page.

**Comment by QuandaIeDingle** [comment]
bruh

**Comment by QuandaIeDingle** [comment]
i hat lif

**Comment by QuandaIeDingle** [comment]
3 ky brokn
