### ISSUE TITLE
IDEA:Auto Answer Correct Typing Answer Question

### ISSUE THREAD

**Issue by GITHUBTRASHACCOUNT** [Minesraft2/Blooket-Cheats#459]
### Gamemode

global

### Function

![image](https://user-images.githubusercontent.com/115583890/220661653-aa91f89b-4d36-42b0-93fc-9ae423583731.png)

**Comment by Greenlio** [comment]
I'll make this in a pr later @Minesraft2

**Comment by Minesraft2** [comment]
> I'll make this in a pr later @Minesraft2

he said a week ago
I'll work on this now

**Comment by Minesraft2** [comment]
Forgot to close, already been added
