### ISSUE TITLE
Name length bypass

### ISSUE THREAD

**Issue by orangemonkey01** [Minesraft2/Blooket-Cheats#462]
### Gamemode

global

### Function

it would let u put in any length of name i dont think this is in the code

**Comment by Realswitzer** [comment]
Uses maxlength param although does not seem limited by API.
![image](https://user-images.githubusercontent.com/39711351/221711687-7eb05a39-994f-489c-a1a7-825ac4048397.png)
![image](https://user-images.githubusercontent.com/39711351/221711838-3de12906-4476-41f1-8a21-dda92f5f0de9.png)
![image](https://user-images.githubusercontent.com/39711351/221711852-4efdbb4a-89da-4a59-8c34-8a5b1b899646.png)

**Comment by orangemonkey01** [comment]
is it going to be added tho?

**Comment by Minesraft2** [comment]
sure

**Comment by Realswitzer** [comment]
Seems like there's a limit though. If I had to guess, it is limited by API to some extent.
![image](https://user-images.githubusercontent.com/39711351/221712242-8fcb6979-b891-4fd1-94c7-5a925bf1bed7.png)
I managed to get 120 characters for the name without it saying to refresh the page, which unlike implied is unnecessary.
Looks like the limit, as 121 characters will say to refresh the name.

**Comment by Minesraft2** [comment]
Yea, firebase has a 128 byte limit when storing strings or smth. it tries to store `<gameid>:<name>` and `<gameId>:` takes up 8 spaces, so 120 would be the max
