### ISSUE TITLE
Bug:(prevent suspension)

### ISSUE THREAD

**Issue by ASTHEBEST** [Minesraft2/Blooket-Cheats#467]
### Script

preventSuspension.js

### Problem

I got banned and it does not work.

### Method

Pasted script into console

### Type

Unobfuscated

### Extra Info
pls fix I need unban. 

<img width="551" alt="Screenshot 2023-02-24 at 5 45 58 PM" src="https://user-images.githubusercontent.com/77271577/221146680-68e25599-71fb-4250-bd28-1b8f4e711903.png">

_No response_

**Comment by Wilke000** [comment]
Lollllll
That prevents u from being banned not undos it
