### ISSUE TITLE
BUG: Not loading

### ISSUE THREAD

**Issue by HiProGamingYT** [Minesraft2/Blooket-Cheats#468]
### Script

Idk Im dumb

### Problem

When I click on the bookmark it does not work it works on my other computer but not for this one. It be kinda weird.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

Help

**Comment by LeozaCEO2** [comment]
what type of hack?

**Comment by Minesraft2** [comment]
Which script

**Comment by HiProGamingYT** [comment]
idk wich script it is

**Comment by LeozaCEO2** [comment]
bruh what type of hack

**Comment by LeozaCEO2** [comment]
u dont know what hack u were using?

**Comment by HiProGamingYT** [comment]
OMFG bro it wasnt a hack I cant even load up the hack menu.

**Comment by Wilke000** [comment]
They are all hacks.

**Comment by HiProGamingYT** [comment]
NOP you can close this my school disabled bookmarklets😭

**Comment by Wilke000** [comment]
Oof.

**Comment by orangemonkey01** [comment]
thats an L
