### ISSUE TITLE
BUG: Ben Stewart

### ISSUE THREAD

**Issue by RealBenStewart** [Minesraft2/Blooket-Cheats#471]
uber eats been stewart

**Comment by RealBenStewart** [comment]
![image](https://user-images.githubusercontent.com/126376022/221395402-11aca7d7-2804-4c4a-9097-d3bd6469e88e.png)

**Comment by RealBenStewart** [comment]
![image](https://user-images.githubusercontent.com/126376022/221395408-057f31f7-d15a-4423-9b36-7bf11c17d4f5.png)

**Comment by RealBenStewart** [comment]
![image](https://user-images.githubusercontent.com/126376022/221395414-6afff974-6803-44f8-b829-9349056bdb6b.png)

**Comment by RealBenStewart** [comment]
![image](https://user-images.githubusercontent.com/126376022/221395417-e8ded5d7-b012-46d5-a95d-ca7fe44bff96.png)

**Comment by RealBenStewart** [comment]
google company

**Comment by RealBenStewart** [comment]
i think i like boys now

**Comment by RealBenStewart** [comment]
me need mc donald

**Comment by LeozaCEO2** [comment]
wtf close this

**Comment by LeozaCEO2** [comment]
gayass

**Comment by LeozaCEO2** [comment]
bro ur not ben stewart tho

**Comment by LeozaCEO2** [comment]
The only good thing about him is that he crated blooket
