### ISSUE TITLE
SKID: RealBenStewart

### ISSUE THREAD

**Issue by LeozaCEO2** [Minesraft2/Blooket-Cheats#476]
### Skid

https://github.com/RealBenStewart/Blooket-Cheats/tree/patch-2

### Stolen

code

**Comment by fowntain** [comment]
As long as it's a fork, it's not a skid. Delete

**Comment by TheRealBenStewart** [comment]
![image](https://user-images.githubusercontent.com/126436332/221465656-3615d08e-ff40-4abf-b290-84ccd29ca177.png)
