### ISSUE TITLE
Does the HTML for google chrome update automatically?

### ISSUE THREAD

**Issue by ClappyXboy** [Minesraft2/Blooket-Cheats#498]
### Gamemode

Google chrome

### Function

Updating automatically

**Comment by Minesraft2** [comment]
No, I'd have to make a request to github on a blooket page, which is prevented by cors

**Comment by ClappyXboy** [comment]
> No, I'd have to make a request to github on a blooket page, which is prevented by cors

Ok that's fine I'm not too lazy to replace the file.

**Comment by Minesraft2** [comment]
https://Minesraft2.github.io/Blooket-Cheats updates automatically

**Comment by Minesraft2** [comment]
It just takes the bookmarklets file and makes buttons and stuff.
