### ISSUE TITLE
BUG: (gui.js)

### ISSUE THREAD

**Issue by darknight413** [Minesraft2/Blooket-Cheats#499]
### Script

gui.js

### Problem

the hake dose not woke we you are on a school computer when it is blocked you should make it so they can not blocked it  

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Wilke000** [comment]
He can’t. Also, it doesn’t matter if its a school computer it just matters if the school blocks javascript. Also, u spelled hack wrong
