### ISSUE TITLE
BUG: (Auto Answer)

### ISSUE THREAD

**Issue by JimmyDeansWonderfullInventions** [Minesraft2/Blooket-Cheats#500]
### Script

AutoAnswer.js

### Problem

It says "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'question')
    at <anonymous>:1:18317" whenever I put it in.

### Method

Pasted script into console

### Type

Obfuscated

**Comment by Minesraft2** [comment]
Unable to reproduce, but I'll update the auto answer later anyway

**Comment by Wilke000** [comment]
Ay 500th issue!
