### ISSUE TITLE
Battle royals auto answer

### ISSUE THREAD

**Issue by Yerthesweat** [Minesraft2/Blooket-Cheats#502]
### Script

Auto Answer.js

### Problem

After toggling the script via the gui when it answers a question it causes the website to go to a white screen and crash

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Yerthesweat** [comment]
It asks if you want to leave the site and when you click cancel it changed into a white screen

**Comment by Yerthesweat** [comment]
This is also specifically with the auto answer in the battle royals menu in the gui the normal auto answer works fine still

**Comment by Minesraft2** [comment]
I'll look into it after school today

**Comment by Minesraft2** [comment]
Can you check if the [battle royale auto answer interval](https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/royale/intervals/autoAnswer.js) works?

**Comment by Realswitzer** [comment]
Does not work. Didn't get the "if you want to leave the site" though.
https://user-images.githubusercontent.com/39711351/222013283-0cb0b0e0-3c1b-4c0f-8e6e-038f11a713fa.mp4

**Comment by Minesraft2** [comment]
alright, that means ben made changes to battle royale recently

**Comment by Minesraft2** [comment]
This should be working now, not sure about typing ones tho
