### ISSUE TITLE
BUG: (getDailyrewards.js)

### ISSUE THREAD

**Issue by CenteredCrazz33** [Minesraft2/Blooket-Cheats#506]
### Script

getDaiyrewards.js

### Problem

it isnt giving me any coins or exp and i cannot progress any further and i would like a script to disable this script please

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

i need to progress through blooket and i cannot please fix this script or make a script to disable it please

**Comment by Minesraft2** [comment]
You just hit your daily limit, wait an hour from now and it should work

**Comment by CenteredCrazz33** [comment]
ive done this already ive waited a while and i cannot get the rewards

**Comment by CenteredCrazz33** [comment]
can you make a script to disable getDailyrewards.js script

**Comment by CenteredCrazz33** [comment]
please and thank you

**Comment by Minesraft2** [comment]
You need to wait for the daily limit to reset, which is everyday at UTC midnight or 6pm CST. There is no reason to disable anything nor is that even possible

**Comment by CenteredCrazz33** [comment]
i have done that

**Comment by Minesraft2** [comment]
It's not a script you can enable

**Comment by Minesraft2** [comment]
It just runs and thats it

**Comment by CenteredCrazz33** [comment]
i mean like its been used and say i get 500 tokens and 300 exp

**Comment by CenteredCrazz33** [comment]
but nothing

**Comment by Minesraft2** [comment]
It should say it gave you the max tokens and xp and then tell you how much you got from the daily wheel

**Comment by CenteredCrazz33** [comment]
it does but it doesnt add to my tokens or exp

**Comment by Minesraft2** [comment]
Does it say this?
![image](https://user-images.githubusercontent.com/49218878/222002703-eb4fc632-936a-4fb8-b975-7b6b46d16d6a.png)

**Comment by CenteredCrazz33** [comment]
yes but i dont get the rewards

**Comment by CenteredCrazz33** [comment]
for the tokens and exp

**Comment by Minesraft2** [comment]
Then wait for the daily limit to reset. It's not a problem with the script.

**Comment by Minesraft2** [comment]
There's probably not even a problem, you might be reading your tokens wrong

**Comment by CenteredCrazz33** [comment]
ill do that and comment back if it fixes

**Comment by CenteredCrazz33** [comment]
and i read my tokens i have 184

**Comment by CenteredCrazz33** [comment]
then done

**Comment by CenteredCrazz33** [comment]
and nothing adds

**Comment by CenteredCrazz33** [comment]
but thanks for the reply i will wait
