### ISSUE TITLE
BUG: General 2

### ISSUE THREAD

**Issue by IntenseTomato2** [Minesraft2/Blooket-Cheats#511]
### Script

N/A

### Problem

Trying to simulate insanely rare drops (Yellow astronaut and Teal Platypus) Doesnt actually simulate them. It works with every character up to legendary though.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Realswitzer** [comment]
Works on my end.

https://user-images.githubusercontent.com/39711351/222016371-84e44fef-3041-449a-b48b-e98a76a715cc.mp4
