### ISSUE TITLE
BUG: All unobfuscated

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#512]
### Script

all the unobfuscated scripts

### Problem

In the script, it says Stuart Private License 2.0.0 but the current license is 2.0.1

### Type

Unobfuscated

### Extra Info

(In license)
<img width="281" alt="Screenshot 2023-02-28 at 9 10 43 PM" src="https://user-images.githubusercontent.com/85253703/222026689-8118f12f-3d6c-4385-967d-242c5c034d4e.png">
(In code)
<img width="281" alt="Screenshot 2023-02-28 at 9 11 01 PM" src="https://user-images.githubusercontent.com/85253703/222026731-bedd5fb5-aeac-47ea-b4dc-df6b9688b732.png">

**Comment by Minesraft2** [comment]
bruh

**Comment by Wilke000** [comment]
What

**Comment by AstnUgly** [comment]
love the hacks
