### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by CenteredCrazz33** [Minesraft2/Blooket-Cheats#513]
think u can add a script to add tokens to our acc? or could u make it so when we use the "useanyblook.js" script we actually keep the blooks or make a separate script to unlock all blooks and keep em forever

**Comment by Realswitzer** [comment]
impossible. all of that is done server side. same answer as #501 and most other issues of this nature.

**Comment by CenteredCrazz33** [comment]
oh thanks for the response
