### ISSUE TITLE
IDEA: Edit Values

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#514]
### Gamemode

TD 2

### Function

Makes it able so you can edit the values of the damage, range, ghost detect, max targets and reload (see below)
<img width="226" alt="Screenshot 2023-03-01 at 9 35 18 AM" src="https://user-images.githubusercontent.com/85253703/222171094-716e4a9d-4fab-4852-95e9-9c70cf2dd887.png">

**Comment by Wilke000** [comment]
Just to be clear i mean of one single tower not all

**Comment by Wilke000** [comment]
Bro do u even know what lmao means? Cuz thats not a place to use it.

**Comment by Wilke000** [comment]
Naw lol would be good there. And if ur too op it’s not fun

**Comment by LeozaCEO2** [comment]
If u don't want to be too op then don't use the hacks

**Comment by ThaatDoorsGuy** [comment]
true

**Comment by Minesraft2** [comment]
cheating is cheating, go all the way or dont go at all
