### ISSUE TITLE
BUG: Unlock Plus Gamemode

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#515]
### Script

UnlockPlusGamemode.js

### Problem

Doesn't work with TD2 (hosting)

### Method

Imported Bookmarklets.html

### Type

Obfuscated

### Extra Info

When I click it it doesn't work, for the reg bookmark and the bookmarked GUI, I haven't tried it in the console tho

**Comment by Minesraft2** [comment]
the new one?

**Comment by Wilke000** [comment]
https://user-images.githubusercontent.com/85253703/222173322-4395e474-eb89-4fe5-86a9-b1fa117174ec.mov


https://user-images.githubusercontent.com/85253703/222173466-9ade7c66-fc60-40a9-abe1-a83db04f2d69.mov

**Comment by Minesraft2** [comment]
You're probably using an outdated script, I just double checked and it's working
