### ISSUE TITLE
im fucked 

### ISSUE THREAD

**Issue by Hankypoo7** [Minesraft2/Blooket-Cheats#516]
### Script

my school

### Problem

my school disabled bookmarklets so i cangt do anything

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated

### Extra Info

f

**Comment by orangemonkey01** [comment]
there is nothing he can do

**Comment by SupernovaSamurai** [comment]
i dont know about the bookmarklets but your deffinetly screwd by saying the f word on ur school laptop
