### ISSUE TITLE
IDEA: sell all blooks

### ISSUE THREAD

**Issue by Consolehecker** [Minesraft2/Blooket-Cheats#518]
### Gamemode

Global

### Function

The script automatically sells all the blooks in your inventory.

**Comment by Minesraft2** [comment]
That would be considered a malicious cheat because it can ruin accounts accidentally. Just use sell dupe blooks and sell the rest manually

**Comment by Consolehecker** [comment]
what if the person you're trying to do it against refused to give you gum?

**Comment by Consolehecker** [comment]
> bruh your worse than me and in kindergarten I beat a kid up for cutting in front of me in line (apparently)

Yeah but he said he would and now he didn't
