### ISSUE TITLE
Adding blooket tokens

### ISSUE THREAD

**Issue by ClappyXboy** [Minesraft2/Blooket-Cheats#519]
### Gamemode

global

### Function

Give the command how many token you want added to your account.

**Comment by vipira** [comment]
This sounds easy to figure out (Im not a coder, so dont @ me), but this would surely get you banned.

**Comment by Minesraft2** [comment]
It's not possible, even trying will get you banned. And don't call people a dumbass before looking at yourself

**Comment by ClappyXboy** [comment]
> > This sounds easy to figure out (Im not a coder, so dont @ me), but this would surely get you banned.
> 
> if it was possible, idiot, we would have already done it. it's not that easy. if you don't have authority, don't give your opinion.

And don't even talk to me with your emo ass profile picture and name so stfu

**Comment by Minesraft2** [comment]
stfu
