### ISSUE TITLE
Issue with simulateUnlock while using GUI

### ISSUE THREAD

**Issue by davidiguess** [Minesraft2/Blooket-Cheats#52]
I used simulateUnlock in the Market and it doesn't work. The screen goes white and it says "Something went wrong."

**Comment by Minesraft2** [comment]
Which blook did you put in?

**Comment by TheBobCreator** [comment]
OHHH I KNOW WHY!!!!! you spelt the blook name wrong or its part of the blizzard pack or daily astronaut that isnt featured

**Comment by Minesraft2** [comment]
the blook just needs to have a box

**Comment by Minesraft2** [comment]
doesn't matter if it's currently obtainable or not, if it has a pack with a pack photo it'll work
