### ISSUE TITLE
BUG: getDailyRewards.js

### ISSUE THREAD

**Issue by Beep404-Boop404** [Minesraft2/Blooket-Cheats#524]
### Script

getDailyRewards.js

### Problem

![image](https://user-images.githubusercontent.com/103309237/222869387-96b5eeef-073f-418a-a240-8a43c298f157.png)

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Obfuscated

### Extra Info

![image](https://user-images.githubusercontent.com/103309237/222869377-354c4957-8467-4c62-a7a3-ef4ff49596ff.png)

**Comment by Beep404-Boop404** [comment]
![image](https://user-images.githubusercontent.com/103309237/222869515-84b8eca3-ac6e-44b7-b5f0-cabfed544707.png)
still, it shows that I alr added the tokens
I checked the market page and the tokens amount hasn't changed

**Comment by Minesraft2** [comment]
are you using the latest version?

**Comment by Minesraft2** [comment]
Should be fixed in 03120561b9089d439c5902d71dbf8b904be6ce20
