### ISSUE TITLE
Daily limit not working

### ISSUE THREAD

**Issue by chickenboyisthebest** [Minesraft2/Blooket-Cheats#525]
### Script

getDailyRewards.js

### Problem

The code has been blocked so it is now impossible to get the daily limit.

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

![image](https://user-images.githubusercontent.com/124620120/222894487-e9431464-fdbd-48a6-8768-8ebaf76a3e15.png)

**Comment by Minesraft2** [comment]
Should be fixed in 03120561b9089d439c5902d71dbf8b904be6ce20
