### ISSUE TITLE
BUG: getDailyRewards.js

### ISSUE THREAD

**Issue by Thing3487** [Minesraft2/Blooket-Cheats#526]
### Script

getDailyRewards.js

### Problem

It says “there was an error when adding rewards”

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Important: it was ran on ios

![76DE4656-9A71-4B32-BC26-8BB027D38EED](https://user-images.githubusercontent.com/126958686/222898480-43764756-e347-434f-ab42-a8bda9b1fbf6.jpeg)

**Comment by Thing3487** [comment]
btw,  Minesraft, I really like how you put all your effort into this repo! I just want to say thank you.

**Comment by DaRealBlooket** [comment]
Same Thing With Me Lol (STWL)

**Comment by Minesraft2** [comment]
Should be fixed in 03120561b9089d439c5902d71dbf8b904be6ce20

**Comment by Thing3487** [comment]
> Should be fixed in [0312056](https://github.com/Minesraft2/Blooket-Cheats/commit/03120561b9089d439c5902d71dbf8b904be6ce20)

😁
