### ISSUE TITLE
IDEA: Change Name During a Round

### ISSUE THREAD

**Issue by SharkyMantisGD** [Minesraft2/Blooket-Cheats#531]
### Gamemode

Global

### Function

Lets you change your name during a Blooket round of any game mode. Most likely be put in gui just to make it easier.

**Comment by MasonTheGreat123** [comment]
that might be hard since he has to edit the person pc to change your name, maybe he could use html to change it but not on the person computer hosting it

**Comment by Minesraft2** [comment]
istg where are these issues coming from, I swear I cleared out all the dumb ones yesterday

**Comment by noimno** [comment]
so you clear this one out but not and exact replica of it but different words????????????????????????????????????????????????????????????????

**Comment by noimno** [comment]
#669 EXACT SAME IDEA BUT DIFFERENT WORDS.
