### ISSUE TITLE
IDEA: Lots of good ideas (please read)

### ISSUE THREAD

**Issue by CowCowCowCowCowCow** [Minesraft2/Blooket-Cheats#532]
### Gamemode

Global

### Function

Can you make a hack that when you type javascript: and that hack in to the stats page, you will get every banner and title in Blooket and get to keep them permanently (i.e. if you refresh your page you will still have every banner and title in your inventory)
Also is there any possible way you can make the get all blooks hack permanent? Like you keep every blook forever?
Finally, can you make a hack that will allow you to bypass the daily limit and you can get any amount of tokens/XP without your account getting banned?

Thank you very much for reading and for making these amazing hacks!
Please reply if possible

**Comment by CowCowCowCowCowCow** [comment]
@Minesraft2

**Comment by Firefly1227** [comment]
@VillainsRule stfu why yo fat ass gotta act so rude shithead. Do you notice the fact that some people don't know things for the love of god.
