### ISSUE TITLE
IDEA: Script idea name

### ISSUE THREAD

**Issue by togekissboivmax** [Minesraft2/Blooket-Cheats#534]
### Gamemode

tower defense two

### Function

add tokens and put blooks over track

**Comment by togekissboivmax** [comment]
what do you mean not possible?

**Comment by togekissboivmax** [comment]
like how its a blooket game

**Comment by Minesraft2** [comment]
There's already a coin setter for td2, and we don't have any control over td2 maps

**Comment by togekissboivmax** [comment]
ok
where?
