### ISSUE TITLE
IDEA: Add a Blooket Game Flooder into global

### ISSUE THREAD

**Issue by fgrtgtrgtrgrt** [Minesraft2/Blooket-Cheats#540]
### Function

Floods blooket lobbies with any amount of bots

**Comment by SharkyMantisGD** [comment]
I’m looking forward for this one!

**Comment by fgrtgtrgtrgrt** [comment]
same

**Comment by Minesraft2** [comment]
f99194e923cd37c5b64d409f16e9f2afeaa82720
