### ISSUE TITLE
Simulate Pack

### ISSUE THREAD

**Issue by ax3ro** [Minesraft2/Blooket-Cheats#541]
### Gamemode

global

### Function

I understand that this script is already out, but can you make it so that the user can choose how many packs they want to simulate opening?

**Comment by LeozaCEO2** [comment]
can't u just do seperatly. Plus, if you're trying to trick someone it wouldn't be realistic because the game without hacks doesn't let you open packs multiple times in a row.

**Comment by Minesraft2** [comment]
Just run the script multiple times
