### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by loosor** [Minesraft2/Blooket-Cheats#543]
### Script

old scripts

### Problem

what do I do it says that the script is bugged and outdated? and may have some issues and errors

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

This cheat is outdated and might be bugged, would you still like to run it? You can find regularly updated cheats here https://github.com/Minesraft2/Blooket-Cheats is what is says.

**Comment by Minesraft2** [comment]
You just copy the script from here and replace what you had in the bookmark

**Comment by Minesraft2** [comment]
I'd recommend finding some bookmarklet generator

**Comment by Minesraft2** [comment]
[This one](https://caiorss.github.io/bookmarklet-maker/) works well
