### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by kaisummer** [Minesraft2/Blooket-Cheats#544]
### Script

gui.js

### Problem

the background color changer doesn't work

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

**Comment by Minesraft2** [comment]
it does, just put put a valid color

**Comment by kaisummer** [comment]
i have everything else works

**Comment by Minesraft2** [comment]
![image](https://user-images.githubusercontent.com/49218878/223001049-845836ee-760e-4c2d-a131-dd3aa280caa9.png)

**Comment by Minesraft2** [comment]
![image](https://user-images.githubusercontent.com/49218878/223001079-c4b0aecb-b863-422b-b514-bab5ae5d3abe.png)

**Comment by Minesraft2** [comment]
![image](https://user-images.githubusercontent.com/49218878/223001134-7915d03e-f0de-4d17-9767-fbd57f5c86e0.png)

**Comment by Minesraft2** [comment]
I'm unable to find any issues

**Comment by kaisummer** [comment]
oh ok. Is there any way to change the purple color between the buttons?

**Comment by Minesraft2** [comment]
The big dark purple background thing is the content color, probably should've named that better

**Comment by kaisummer** [comment]
idk if it's just me being stupid but I can't change it from purple
