### ISSUE TITLE
HTML File chrome broken

### ISSUE THREAD

**Issue by Caakers** [Minesraft2/Blooket-Cheats#553]
### Script

HTML Chrome import

### Problem

I followed every step to install HTML file for chrome but none of the folders have anything in them. Basically empty files were imported.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

[Screen recording 2023-03-06 08.51.31.webm](https://user-images.githubusercontent.com/127127494/223161462-7e95f195-d281-46b8-9d15-010717a0f4d2.webm)
I don' have access to discord ATM but in a  few hours I will.

**Comment by orangemonkey01** [comment]
just use the gui

**Comment by Caakers** [comment]
> just use the gui

idk how to use it and after looking around a little didn't find instructions

**Comment by Minesraft2** [comment]
Just run the gui script, the rest is self explanatory

**Comment by Caakers** [comment]
> 

my chromebook can't run the file

**Comment by orangemonkey01** [comment]
[Screen recording 2023-03-06 10.44.02 AM.webm](https://user-images.githubusercontent.com/125912712/223189963-da28b4be-7d54-4552-a6f3-520e3255b80b.webm)

**Comment by orangemonkey01** [comment]
this is how bookmark do the gui

**Comment by Minesraft2** [comment]
If that doesn't work for you, chances are your school did something to block bookmarklets.
