### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by kaisummer** [Minesraft2/Blooket-Cheats#554]
### Script

gui.js

### Problem

I am unable to change the content color

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

**Comment by Wilke000** [comment]
Oof. Skill issue.

**Comment by Minesraft2** [comment]
I'll fix this later today.

**Comment by Wilke000** [comment]
He put unobfuscated code into javascript:(code)

**Comment by Minesraft2** [comment]
No I just tried, the content box thing wont update

**Comment by Minesraft2** [comment]
Fixed
