### ISSUE TITLE
BUG: (Gui.js)

### ISSUE THREAD

**Issue by Jetnut** [Minesraft2/Blooket-Cheats#555]
### Script

Gui.js

### Problem

When i bookmark the javascript to my google,  the bookmark just disappears. I have used these in the past so i think it is a problem with the javascript.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Minesraft2** [comment]
It's working perfectly fine on multiple people's ends, so I think it is a problem with how you're doing it.

**Comment by Jetnut** [comment]
Is there a way to do it through the run tool on a windows computer using
google chrome?
