### ISSUE TITLE
All blooks doesn't work during games, only on the blooks page

### ISSUE THREAD

**Issue by marfanis788** [Minesraft2/Blooket-Cheats#56]
bottom text

**Comment by fowntain** [comment]
You sure you have the updated hack and you are using the script in the lobby? Works fine for me

**Comment by marfanis788** [comment]
Yeah it's updated

**Comment by Wilke000** [comment]
Same for me doesn’t work in lobby

**Comment by fowntain** [comment]
Yeah I just checked, doesn't work

**Comment by Glixxzzy** [comment]
I think it's only supposed to work on the blooks page.

**Comment by Glixxzzy** [comment]
Yeah it says it's supposed to work in the lobby.

**Comment by Mine-Dimensions** [comment]
> Yeah it says it's supposed to work in the lobby.

Exactly. It works on the blooks page but not the lobby

**Comment by Minesraft2** [comment]
Should be fixed now 👍
