### ISSUE TITLE
BUG: Simulate Unlock

### ISSUE THREAD

**Issue by UltraBeany011** [Minesraft2/Blooket-Cheats#562]
### Script

i think its gui.js

### Problem

I try to use simulate unlock on chromas or mythics and it doesn't work. If this is on purpose then sorry for bothering.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by orangemonkey01** [comment]
it doesnt work anymore i dont think

**Comment by Minesraft2** [comment]
Only works for blooks you're currently able to buy in the market
