### ISSUE TITLE
BUG: All Below Global-get daily rewards

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#565]
### Script

global, gold, crazy, racing, royale, blook rush, TD/TD2, Santas

### Problem

The images are all messed up

### Method

Imported Bookmarklets.html

### Type

Unobfuscated, Obfuscated

### Extra Info

<img width="375" alt="Screenshot 2023-03-07 at 10 39 57 AM" src="https://user-images.githubusercontent.com/85253703/223471729-90c06dae-b13c-4df4-986d-c3bb61ad2fe5.png">
<img width="375" alt="Screenshot 2023-03-07 at 10 40 08 AM" src="https://user-images.githubusercontent.com/85253703/223471797-67bdd707-2077-4e23-bbbf-9181ac2fc0e3.png">
<img width="375" alt="Screenshot 2023-03-07 at 10 40 20 AM" src="https://user-images.githubusercontent.com/85253703/223471853-10f615ef-1dbf-4f1d-8e28-24eb80d6008d.png">
<img width="375" alt="Screenshot 2023-03-07 at 10 40 32 AM" src="https://user-images.githubusercontent.com/85253703/223471935-9832a3c2-e438-42b8-9329-3914647df9b8.png">
<img width="375" alt="Screenshot 2023-03-07 at 10 40 43 AM" src="https://user-images.githubusercontent.com/85253703/223471991-6d6730f9-2033-4c39-af87-aadc0858c473.png">

(not all but yea)

**Comment by Wilke000** [comment]
Oof bro just closed me as not planned

**Comment by Wilke000** [comment]
The GUI and Mobile GUI also have that problem

**Comment by BlooketFanBoy12** [comment]
They don’t skill issue ngl

**Comment by ThaatDoorsGuy** [comment]
👍

**Comment by Wilke000** [comment]
Wait oof what? I tried it on my alt account and it works fine no image error… lol
