### ISSUE TITLE
The Simulate Open doesn't work!

### ISSUE THREAD

**Issue by YaBoyMH** [Minesraft2/Blooket-Cheats#57]
Yes my cheats are fully updated and after I select the blook that I want to simulate opening, I click the box then it just doesn't do anything.

**Comment by Glixxzzy** [comment]
On the UI or the simulate open code by itself?

**Comment by YaBoyMH** [comment]
The UI

**Comment by Wilke000** [comment]
Yes the GUI - Simulate unlock does not work

**Comment by Minesraft2** [comment]
I'll fix this after school

**Comment by Wilke000** [comment]
Mk… pls don’t put this off like the frenzy lol

**Comment by Minesraft2** [comment]
I thought I fixed this already, could you update and try it again?

**Comment by Minesraft2** [comment]
Ahh, nvm I found the issue

**Comment by Minesraft2** [comment]
Fixed 👍
