### ISSUE TITLE
IDEA: Custom blooks?

### ISSUE THREAD

**Issue by fard83** [Minesraft2/Blooket-Cheats#571]
### Gamemode

Global

### Function

Idk if this is possible but could you make a script that lets you get custom items for the custom blooks? This might be impossible and if so im sorry for wasting your time :/

**Comment by LeozaCEO2** [comment]
maybe he could switch around scripts and stuff from blooket idk

**Comment by Minesraft2** [comment]
It'd only be on your end, and it would be tedious. I see absolutely no point.

**Comment by fard83** [comment]
> It'd only be on your end, and it would be tedious. I see absolutely no point.

ah ok srry
