### ISSUE TITLE
Alerts

### ISSUE THREAD

**Issue by BlooketFanBoy12** [Minesraft2/Blooket-Cheats#576]
### Script

Alerts

### Problem

Don’t really see what it does and the other thread didn’t really explain it I used 3 accounts and played for a while and the alerts tab had nothing in it and this was in despetive dinos gold quest etc cafe I tried all the hostile game modes 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Minesraft2** [comment]
It puts alerts like swapping gold and stealing crypto into that tab

**Comment by Minesraft2** [comment]
The interval that checks if you're in a valid game or not runs has a 5 second delay

**Comment by BlooketFanBoy12** [comment]
You mind putting a screen shot of how it should look? When your in crypto hack or gold quest mine is just blank

**Comment by BlooketFanBoy12** [comment]
The alerts don’t pop up when you go into the game I used 2 different account and played a little and no alerts popped up if that clarifies it

**Comment by Minesraft2** [comment]
did you swap at all during your testing?

**Comment by Minesraft2** [comment]
did the message saying to join a game atleast disappear

**Comment by BlooketFanBoy12** [comment]
Yes it did

**Comment by BlooketFanBoy12** [comment]
No, during my testing I did not swap I will test it give me a min

**Comment by orangemonkey01** [comment]
put code here i wanna play im bored

**Comment by BlooketFanBoy12** [comment]
alright it works mb

**Comment by BlooketFanBoy12** [comment]
Didn’t really understand the concept I know what it does now it works

**Comment by orangemonkey01** [comment]
nvm
