### ISSUE TITLE
Question: What exactly does the “Bookmarklets” script supposed to do? Because it does nothing.

### ISSUE THREAD

**Issue by SharkyMantisGD** [Minesraft2/Blooket-Cheats#577]
Title says it all

**Comment by orangemonkey01** [comment]
then why did you open this

**Comment by SharkyMantisGD** [comment]
> then why did you open this

Wdym?

**Comment by Realswitzer** [comment]
the bookmarklets file (unobfuscated/Bookmarklets.html, I assume, which is being mistaken for a script) is a file which is imported to the browser, adding the scripts (as bookmarklets) to the browsers bookmarks to be run.
see /tutorial/GoogleChrome.md
