### ISSUE TITLE
Flood Bots

### ISSUE THREAD

**Issue by BlooketFanBoy12** [Minesraft2/Blooket-Cheats#578]
### Gamemode

All

### Function

Alright, so basically the bots bypass name limit to 120 like you can do normally, also they bypass blooket censor check if you put a bad word or something would make stuff more funny in class

**Comment by orangemonkey01** [comment]
literally, any time I get on the leaderboard people scream that I'm hacking so if I did something like flood the game in class then everyone would know it's me. this is why I don't do crazy shit like flood games

**Comment by Wilke000** [comment]
@orangemonkey01 i feel ya bro.

**Comment by orangemonkey01** [comment]
nice to know im not the only one
