### ISSUE TITLE
Simulate unlock

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#58]
Bookmarklets - gui - simulate unlock does not work. Maybe just GUI - simulate unlock but ik the Bookmarklets - gui - simulate unlock does not work.

**Comment by Wilke000** [comment]
SO pretty much
If you import bookmarklets, go to the GUI, then go to simulate unlock, put in a blook, hit simulate unlock, nothing happens

**Comment by Minesraft2** [comment]
duplicate issue
