### ISSUE TITLE
Maybe release deobfuscate source also add full ipad support (add ability to exit and hide/show on ipad) 

### ISSUE THREAD

**Issue by wendellmeset** [Minesraft2/Blooket-Cheats#59]
yay

**Comment by Minesraft2** [comment]
unlikely

**Comment by wendellmeset** [comment]
wow fastest reply ever, well maybe not deobfuscated source but ipad support, like a minimize button in the gui, and when you click it, a small plus/maximize button appears in bottom right of screen

**Comment by Minesraft2** [comment]
Will probably be added in the new UI design I'm working on, but it's a side project and won't be coming out anytime soon.
