### ISSUE TITLE
                                                                                                                                                                                      .

### ISSUE THREAD

**Issue by Iamthec** [Minesraft2/Blooket-Cheats#590]

**Comment by orangemonkey01** [comment]
you cant do this it is server sided unless you mean like simulating the unlock

**Comment by Wilke000** [comment]
@Iamthec can u even read bro? 
<img width="838" alt="Screenshot 2023-03-08 at 9 09 53 PM" src="https://user-images.githubusercontent.com/85253703/223897588-eaf2ba93-35f0-44dc-8bae-cdcc7e05de24.png">
(in the readme)

**Comment by jood112** [comment]
you are dumb
