### ISSUE TITLE
IDEA: Add A Cheat Like End and Kick the game

### ISSUE THREAD

**Issue by r3a1ty** [Minesraft2/Blooket-Cheats#591]
### Gamemode

Global

### Function

End - By Adding The Cheat You Can End The Game
Kick - You Can Kick All Players Or Kick A Player Out Of The Game

**Comment by Minesraft2** [comment]
These would only work for the host, making it useless

**Comment by r3a1ty** [comment]
like ryxz did it so can u

**Comment by Minesraft2** [comment]
They were in a folder called host scripts

**Comment by SharkyMantisGD** [comment]
I already tried opening this one, they are patched.
