### ISSUE TITLE
BUG: FloodGame not working

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#594]
### Script

floodgame.js

### Problem

When I enter the code into the console, this shows up:
<img width="579" alt="Screenshot 2023-03-09 at 9 21 44 AM" src="https://user-images.githubusercontent.com/85253703/224053487-99f3de27-a857-4bbc-a1ae-e4cd8a6af0c7.png">

### Method

Pasted script into console

### Type

Unobfuscated, Obfuscated

### Extra Info

I tried it with both unobfuscated and obfuscated, the screenshot is the unobfuscated one

**Comment by Minesraft2** [comment]
what page did you use it on

**Comment by Wilke000** [comment]
Ohh r u supposed to use it on play.blooket.com?

**Comment by Wilke000** [comment]
I got it
