### ISSUE TITLE
BUG: Freezing thing

### ISSUE THREAD

**Issue by SnesLover22** [Minesraft2/Blooket-Cheats#595]
### Script

gui.js

### Problem

So I notice at times, when using the hack, if I like do osme major updgrades like in monster brawl, or get large amounts of gold in gold rush, it freezes the player and you can't play anymore. Now in games like goldrush you can just add gold with the hack, but otherwise other games become unplayable. Is this on blookets end to stop people from cheating or is it a GUI glitch? Also the bot flooder don't work :/

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Obfuscated

### Extra Info

among of gus

**Comment by Wilke000** [comment]
Yep I have the same problem :)

**Comment by orangemonkey01** [comment]
the obfuscated gui flooder is slow not broken

**Comment by Minesraft2** [comment]
Well for monster brawl freezing is quite common at high levels when cheating because if you dont have anything to upgrade the menu wont show up and it just pauses

**Comment by Minesraft2** [comment]
But I've never seen, nor has anyone else reported any other kind of freezing. Does it just freeze as if it's lagging? Or can you not click anything?

**Comment by SnesLover22** [comment]
Like it won't let me click any option, move, or anything else. and that was on level 15. I was going kinda fast though tbh.

**Comment by Minesraft2** [comment]
Well that's common for monster brawl, but there isn't much I can do about it

**Comment by SnesLover22** [comment]
its happened in Monster Brawl, Gold Rush, Fishing, and Tower Of Doom

**Comment by Minesraft2** [comment]
What question sets?

**Comment by SnesLover22** [comment]
idk my teacher put em on...

**Comment by SnesLover22** [comment]
but they all freeze in the same way... blooket might check to see how fast an answer is clicked, and see if it is less than 2 or 1 second or something. idk but it pisses me off sometimes.

**Comment by Minesraft2** [comment]
What cheats do you run before it freezes?

**Comment by SnesLover22** [comment]
it really depends. sometimes it just freezes using highlight answer and chest ESP, sometimes it just does it randomly.

**Comment by Minesraft2** [comment]
I just played a whole gold quest game using both cheats, and another with every useful cheat activated

**Comment by Minesraft2** [comment]
What device is it happening on

**Comment by Wilke000** [comment]
Do it in monster brawl

**Comment by SnesLover22** [comment]
Chromebook 100E gen 2. But like if I answer real fast or something it like freezes my screen. Lol it still pops up messages though, like: JC took 1000000 gold from you!

**Comment by Minesraft2** [comment]
I just finished an entire monster brawl game without any freezes

**Comment by Minesraft2** [comment]
i think your chromebook is just slow

**Comment by SnesLover22** [comment]
Its not slow it like freezes the game. completely. other actions continue, and it even ends when the game does, but Gameplay wise it freezes. If it freezes in gold rush I can just keep the amount of gold going up with set gold. I think blooket is on to cheaters now. If you use a specific Blooket cheat, it asks what hack you're using: TheRealGlizz or some other one I forgot. When your GUI stopped working for me for a bit I used an alternate hack and so did my friend, and blooket showed a question asking what hack he was using, with 2 answers and a troll face gif. Its kinda scary but blooket can tell now whos hacking.

**Comment by SnesLover22** [comment]
I think it was this one: https://raw.githubusercontent.com/Blooketware/BlooketUI/main/bookmarklet.js

**Comment by SnesLover22** [comment]
yep it was that one :/ I think blooket definitely knows about you now, man.

**Comment by Minesraft2** [comment]
First, Blooket already knew about me. Second, they haven't done anything to detect cheaters yet.
If they did, they wouldn't stop at just annoying people, they'd suspend them.
Your device is the issue.

**Comment by SnesLover22** [comment]
Its happened to multiple people in my class using PC laptops and phones.

**Comment by Minesraft2** [comment]
Well until I'm able to reproduce the issue or someone else does, I can't do anything about it

**Comment by MasonTheGreat123** [comment]
i know why, its because you have too many cheats on. I did this once doing all the hacks in one game and it crashed

**Comment by SnesLover22** [comment]
I only had 2 on.... well minesraft is right if he sees nothing wrong then he can't do anything about it tbh.
