### ISSUE TITLE
BUG: (script name

### ISSUE THREAD

**Issue by rhino42811** [Minesraft2/Blooket-Cheats#605]
### Script

javascript

### Problem

flood game is not working

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

dont know obfuscated is so i put un unobfuscated

**Comment by Minesraft2** [comment]
you have to run it on play.blooket.com or in a game

**Comment by Minesraft2** [comment]
The new obfuscated should work in javascript:
But if they didn't update it wouldn't matter

**Comment by Wilke000** [comment]
Oh I didn’t know that sry
