### ISSUE TITLE
get daily rewards

### ISSUE THREAD

**Issue by benjiboy123456789** [Minesraft2/Blooket-Cheats#607]
### Script

get daily rewards

### Problem

it is javascript:(code) and on the blooket play screen to use it. I kept doing this and it is not working.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Thing3487** [comment]
> ### Script
> get daily rewards
> 
> ### Problem
> it is javascript:(code) and on the blooket play screen to use it. I kept doing this and it is not working.
> 
> ### Method
> Put 'javascript:(code)' in the url bar or a bookmark
> 
> ### Type
> Obfuscated
> 
> ### Extra Info
> _No response_

Obfuscated is no longer obfuscated

**Comment by Thing3487** [comment]
Just minified

**Comment by Thing3487** [comment]
So you need to  paste it into console

**Comment by Thing3487** [comment]
or use [this](https://drive.google.com/file/d/1mEAHPlFR1X4TVcIyUVOpHoozP0VzBNiX/view?usp=sharing) method if you’re on mobile

**Comment by Thing3487** [comment]
> or use [this](https://drive.google.com/file/d/1mEAHPlFR1X4TVcIyUVOpHoozP0VzBNiX/view?usp=sharing) method if you’re on mobile

make sure you use unobfuscated if you use this method

**Comment by orangemonkey01** [comment]
bro shut up obfuscated works so how about try before you make stupid answers

**Comment by benjiboy123456789** [comment]
thanks Thing3487

**Comment by orangemonkey01** [comment]
it does work

**Comment by benjiboy123456789** [comment]
My problem is you have to go in to inspect to put some thing into console and I would like to be able to do this on a school Chromebook.

**Comment by orangemonkey01** [comment]
i made a tut for bookmarking it in discussion

**Comment by benjiboy123456789** [comment]
I am stupid I don't even know how to bookmark a code lol I will figure it out.

**Comment by orangemonkey01** [comment]
[223189963-da28b4be-7d54-4552-a6f3-520e3255b80b.webm](https://user-images.githubusercontent.com/125912712/224458383-355c8f57-4bcd-489e-920b-02fbe47ce8ce.webm)

**Comment by benjiboy123456789** [comment]
![image](https://user-images.githubusercontent.com/127568525/224459765-1f0b5b04-c43c-4959-8432-df91e00a1a51.png)
 
this is what my code looks like. it is different from yours.

**Comment by benjiboy123456789** [comment]
![image](https://user-images.githubusercontent.com/127568525/224459816-8101e701-9507-4da1-afe2-5870df8b5432.png)

**Comment by DragonDude20** [comment]
Here try this link: https://minesraft2.github.io/Blooket-Cheats/#Global
It is the GitHub page for this repo and is currently working. Click the button that says GUI, not mobile GUI, and it will copy. two-finger click the bookmarks bar and click add page. Delete the title so it's blank, and copy and paste the code into the URL space.

**Comment by DragonDude20** [comment]
Also, this page is updated more frequently than the actual repo, so I suggest using it.

**Comment by orangemonkey01** [comment]
its blocked for me so im good

**Comment by orangemonkey01** [comment]
its the gui not mobile

**Comment by Minesraft2** [comment]
> So you need to paste it into console

no it still works in the bookmarklets

**Comment by Minesraft2** [comment]
> ![image](https://user-images.githubusercontent.com/127568525/224459765-1f0b5b04-c43c-4959-8432-df91e00a1a51.png)
> 
> this is what my code looks like. it is different from yours.

it should work the same
