### ISSUE TITLE
A Branch Called Host Hacks

### ISSUE THREAD

**Issue by DragonDude20** [Minesraft2/Blooket-Cheats#608]
### Gamemode

Global or any game

### Function

Remove player, End game, kick all players
See this repository: https://github.com/Blooket-Cheats/Blooket-Hacks/tree/bookmarklets/Global/Host

### Method

I have not the FaQ

**Comment by Minesraft2** [comment]
I won't add any host scripts. They can only be ran by the host and are already built in to Blooket

**Comment by DragonDude20** [comment]
Thanks
Can they really be only used by the host?
And is there any way to force suspension on another user?

**Comment by DragonDude20** [comment]
I have kids in my grade abusing this like crazy. For pre-tests, and things like that.

**Comment by Minesraft2** [comment]
That's why they were in a folder called Host Scripts.
Only if you can convince them to run a suspender
