### ISSUE TITLE
BUG: (Simulate Unlock)

### ISSUE THREAD

**Issue by Jetnut** [Minesraft2/Blooket-Cheats#609]
### Script

Gui.js

### Problem

So when i select the simulate unlock as rainbow astronaut, it doesn't do anything when i click it.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Minesraft2** [comment]
Only blooks you can currently get from a pack will work

**Comment by Jetnut** [comment]
Did you change your name on github?
