### ISSUE TITLE
BUG: obstufacated

### ISSUE THREAD

**Issue by EpicYTofficial** [Minesraft2/Blooket-Cheats#611]
### Script

gui.js

### Problem

The gui wont open I don't know if its a problem only I'm having or maybe others?

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

j

**Comment by mungK11** [comment]
BRO ITS NOT WOrkING FOR ME TOO

**Comment by mungK11** [comment]
any hack I use doesn't work

**Comment by Minesraft2** [comment]
Should be fixed, reopen if not

**Comment by Thehacker7990** [comment]
Nice code you made
