### ISSUE TITLE
obsucated

### ISSUE THREAD

**Issue by Thehacker7990** [Minesraft2/Blooket-Cheats#613]
### Script

Gui.js

### Problem

On booklet the bot feature in the window make the game go away not put in a bot

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by Thing3487** [comment]
> ### Script
> Gui.js
> 
> ### Problem
> On booklet the bot feature in the window make the game go away not put in a bot
> 
> ### Method
> Imported Bookmarklets.html
> 
> ### Type
> Obfuscated
> 
> ### Extra Info
> _No response_

i  Think  it’s device issue or skill issue, whenn i ran it, it worked
