### ISSUE TITLE
BUG: in obfuscated gui.js it used to be in the format for bookmarklets but now its not

### ISSUE THREAD

**Issue by feeshmaster** [Minesraft2/Blooket-Cheats#615]
### Script

GUI.js

### Problem

Can you add another thing that is for the bookmarklets?

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

None

**Comment by Minesraft2** [comment]
I guarantee, obfuscated still works in bookmarklets. It they don't you're doing something wrong
