### ISSUE TITLE
blooket banned the add daily tokens stuff on the play.blooket.com, aren't ale to lauch hack on the play page and inside a game.BUG: (script name)

### ISSUE THREAD

**Issue by AndyDgreat** [Minesraft2/Blooket-Cheats#616]
### Script

The big bot

### Problem

blooket banned the add daily tokens stuff on the play.blooket.com, aren't ale to lauch hack on the play page and inside a game.BUG: (script name)

### Method

Pasted script into console

### Type

Unobfuscated

### Extra Info

![image](https://user-images.githubusercontent.com/127714691/224611508-098f07da-9c3d-4c33-bdcc-21df7ae76cf1.png)

**Comment by DiscipleOfJava** [comment]
This doesn't work for me either

**Comment by Leoneedshax** [comment]
Yea I can't get my tokens. It worked yesterday...

**Comment by Leoneedshax** [comment]
I used blookmarklets bookmark hack with unobfuscated

**Comment by Thing3487** [comment]
> Yea I can't get my tokens. It worked yesterday...

Sorry

**Comment by Thing3487** [comment]
Skill Issue

**Comment by Thing3487** [comment]
It worked  on my end

**Comment by Minesraft2** [comment]
already fixed, update your scripts
