### ISSUE TITLE
None of them work in game

### ISSUE THREAD

**Issue by Shadowyboi** [Minesraft2/Blooket-Cheats#617]
### Script

All

### Problem

None of them work in game

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

Don’t work pretty self explanitory

**Comment by Shadowyboi** [comment]
How do I update them

**Comment by Minesraft2** [comment]
Copy them again

**Comment by Shadowyboi** [comment]
Thank you minesraft2
