### ISSUE TITLE
IDEA: Custom Tower Defense Map

### ISSUE THREAD

**Issue by MasonTheGreat123** [Minesraft2/Blooket-Cheats#622]
### Gamemode

Tower defense

### Function

make your own maps or whatever idk

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by MasonTheGreat123** [comment]
i saw it in some copyed thing of yours in the README.

**Comment by Minesraft2** [comment]
It was an old idea i had, but it'd cause a lot of issues later on for whoever uses it, so i decided against it
