### ISSUE TITLE
SKID: <Cph101 and CrazyH2>

### ISSUE THREAD

**Issue by Thing3487** [Minesraft2/Blooket-Cheats#629]
### Skid

https://github.com/Blooket-Cheats/Blooket-Hacks

### Stolen

They stole the gui and put it [here](https://github.com/Blooket-Cheats/Blooket-Hacks/blob/experimental/Global/GUI.js)

**Comment by src-ry** [comment]
This has already been noticed btw

**Comment by src-ry** [comment]
Wasn't the only thing that was skidded

**Comment by src-ry** [comment]
A good amount of the repo was stolen from various repos

**Comment by Minesraft2** [comment]
They're crazy stubborn

**Comment by Minesraft2** [comment]
CrazyH2 specifically

**Comment by Minesraft2** [comment]
We're tryna work it out

**Comment by Thing3487** [comment]
> We're tryna work it out

👍

**Comment by Thing3487** [comment]
> Wasn't the only thing that was skidded

Stop contributing to the repo

**Comment by Thing3487** [comment]
> > They're crazy stubborn
> 
> so just send a dcma if you've already warned, then dcma!

How?????

**Comment by src-ry** [comment]
> > Wasn't the only thing that was skidded
> 
> Stop contributing to the repo

I haven't contributed to the repo for a good few months?

**Comment by Thing3487** [comment]
> > > Wasn't the only thing that was skidded
> > 
> > 
> > Stop contributing to the repo
> 
> I haven't contributed to the repo for a good few months?

👍
