### ISSUE TITLE
Gui Not working

### ISSUE THREAD

**Issue by AnonymousPerson-1** [Minesraft2/Blooket-Cheats#637]
### Script

https://github.com/Minesraft2/Blooket-Cheats/blob/main/obfuscated/gui.js

### Problem

It wont work and also it has only 16 lines of code when it used to have like 600

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by benjiboy123456789** [comment]
I don't think we can do javascript:(code) anymore. we have to use inspect then go to console and put it in there.

**Comment by AnonymousPerson-1** [comment]
I got the GUI working

**Comment by Thing3487** [comment]
> I don't think we can do javascript:(code) anymore. we have to use inspect then go to console and put it in there.

Sorry, i just ccheckked, you still can do that

**Comment by Thing3487** [comment]
@AnonymousPerson-1  PPlease close this

**Comment by benjiboy123456789** [comment]
Look Thing3487 it does not work for me.  https://mail.google.com/mail/u/0?ui=2&ik=a759316c64&attid=0.1&permmsgid=msg-a:r7489056069821388458&th=186e296ee6ab4a3c&view=att&disp=safe&realattid=f_lf8x97rv0

**Comment by Thing3487** [comment]
![6730F0DC-61A2-4BFA-9536-010B2F009F8C](https://user-images.githubusercontent.com/126958686/225186525-7aed8f74-49ec-47fa-af7b-2e7e48680db6.jpeg)

Sorry but it says error, could you upload it to google drive and give me the link?

**Comment by Thing3487** [comment]
@benjiboy123456789

**Comment by Thing3487** [comment]
> it doesn't work for me either

browser?

**Comment by Dannyfryar07** [comment]
Working for me
![Screenshot 2023-03-15 6 31 29 AM](https://user-images.githubusercontent.com/127945425/225285607-8d7b3e48-b0ca-4d41-b2ca-202108ef5149.png)

**Comment by jcalelzz** [comment]
i cant do it i do everything right but still don't work i even watched a yt vid

**Comment by MasonTheGreat123** [comment]
whaaa it just opened it

**Comment by jcalelzz** [comment]
pls help

**Comment by MasonTheGreat123** [comment]
just do java script: code

**Comment by jcalelzz** [comment]
i did

**Comment by jcalelzz** [comment]
a i able to send  ascreen recording?

**Comment by MasonTheGreat123** [comment]
yea

**Comment by jcalelzz** [comment]
how

**Comment by jcalelzz** [comment]
nevermind

**Comment by jcalelzz** [comment]
i help really bad

**Comment by jcalelzz** [comment]
i found out sorry

**Comment by benjiboy123456789** [comment]
@Thing3487     here is me putting it in https://drive.google.com/file/d/19zldfKJkYb_ZKyA1vJ6MA7rzOf9weaEI/view?usp=share_link

**Comment by Thing3487** [comment]
> @Thing3487 here is me putting it in https://drive.google.com/file/d/19zldfKJkYb_ZKyA1vJ6MA7rzOf9weaEI/view?usp=share_link

@benjiboy123456789 i need access

**Comment by benjiboy123456789** [comment]
oh whats your email

**Comment by benjiboy123456789** [comment]
@Thing3487

**Comment by Thing3487** [comment]
> oh whats your email

ravensocksIsC00l@gmail.com

**Comment by LeozaCEO2** [comment]
My browser is google @Thing3487. I just use a bookmark.

**Comment by LeozaCEO2** [comment]
put it in a bookmark it's the most convienient.

**Comment by Minesraft2** [comment]
The GUI is still working, and obfuscated does still work in bookmarks and in the url bar.
