### ISSUE TITLE
IDEA: use any banner/title or a gui addition/port of https://github.com/ThatFruedDued/blooket-utility

### ISSUE THREAD

**Issue by itamar215000** [Minesraft2/Blooket-Cheats#647]
### Gamemode

Global

### Function

lets you use any banner/title for your profile

or a script injector

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Blooket's api prevents you from using any banner/title or blook on the stats page
