### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by MrGoldPotatoYT** [Minesraft2/Blooket-Cheats#648]
### Script

Gui.js

### Problem

when I enter the Gui it doesn't open the hack fix this asap pls

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

idk the type so i said somthing random

**Comment by Minesraft2** [comment]
It's not broken, you didn't run the javascript right.
