### ISSUE TITLE
BUG: getDailyRewards.js

### ISSUE THREAD

**Issue by thebiggestcow** [Minesraft2/Blooket-Cheats#651]
### Script

getDailyRewards.js

### Problem

it says: 'Added max tokens and xp, and got 0 daily wheel tokens!' but no money is added to the account after being refreshed

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Obfuscated

**Comment by Minesraft2** [comment]
That means you already got your daily limit, and need to wait for the reset

**Comment by thebiggestcow** [comment]
> That means you already got your daily limit, and need to wait for the reset

ah cool my bad bro have a good day mate
