### ISSUE TITLE
IDEA: Add a log that gives the user a list of hacks ran

### ISSUE THREAD

**Issue by Doob123123** [Minesraft2/Blooket-Cheats#656]
### Gamemode

All

### Function

Add a log that allows the user to see what hacks they ran, as well as for things like spam open, log the blooks that were opened. This log is deleted when the page is refreshed.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by LeozaCEO2** [comment]
Yeah I think that's what he means.

**Comment by Wilke000** [comment]
> would these logs be in the console?

No I think he means a new tab in the GUI like alerts and settings

**Comment by Minesraft2** [comment]
mb already added
