### ISSUE TITLE
IDEA: Make a discord option

### ISSUE THREAD

**Issue by otmfyou** [Minesraft2/Blooket-Cheats#658]
### Gamemode

gui.js

### Function

Add a iframe that opens your discord using a widget bot or something and add it  to discord tab.
![image](https://user-images.githubusercontent.com/127300019/226085104-f2fb100c-24eb-4998-bd4c-94b256fe327b.png)
something like that.
when clicked opens it

### FaQ

I have not read the FaQ, I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Blooket has a content security policy

**Comment by otmfyourandomize** [comment]
I mean for the blooket cheat add a discord option and make a server that clears the messages after 10sec of send then the ingame chat for cheaters is done (kinda)
