### ISSUE TITLE
Blacket  Cheats

### ISSUE THREAD

**Issue by Ljduley12** [Minesraft2/Blooket-Cheats#659]
### Gamemode

None

### Function

Add token

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Ljduley12** [comment]
for blacket v.2

**Comment by Ljduley12** [comment]
Minesraft2

**Comment by Minesraft2** [comment]
Yea use [blacketware](https://github.com/BlacketWare/v2)
