### ISSUE TITLE
BUG: weird

### ISSUE THREAD

**Issue by richie980** [Minesraft2/Blooket-Cheats#662]
### Script

JavaScript 

### Problem

The mobile gui isn’t working bc it’s to big

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by OGBlooketCheater** [comment]
new gui is weird tbh. because all the old things are gone. I hope this is temporary.

**Comment by Minesraft2** [comment]
What old things?

**Comment by OGBlooketCheater** [comment]
like the old Gui thing and the sort menu

**Comment by OGBlooketCheater** [comment]
and the custom color thing

**Comment by Minesraft2** [comment]
> like the old Gui thing and the sort menu

The mobile gui is the old gui

**Comment by Minesraft2** [comment]
Unable to reproduce, and unsure what to do about it
