### ISSUE TITLE
BUG: (gui.js) 

### ISSUE THREAD

**Issue by javenyt** [Minesraft2/Blooket-Cheats#664]
### Script

gui

### Problem

it wont load on my dell laptop even after i pressed the tab

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

**Comment by OGBlooketCheater** [comment]
It needs to be OBFUSCATED

**Comment by Minesraft2** [comment]
> It needs to be OBFUSCATED 

importing unobfuscated bookmarks are already minified, i wouldn't add them otherwise

**Comment by OGBlooketCheater** [comment]
Its kinda stupid people Use unobfuscated and think that will work

**Comment by Minesraft2** [comment]
stale
