### ISSUE TITLE
Change name during round

### ISSUE THREAD

**Issue by DragonDude20** [Minesraft2/Blooket-Cheats#669]
### Gamemode

General Usage

### Function

This would allow you to change your Nickname during the game to throw suspicions off your trail. 

### FaQ

I have read the FaQ

**Comment by orangemonkey01** [comment]
sup

**Comment by LightningPandaSO** [comment]
What if i told you, DragonDude20, had that dog in them.

**Comment by SharkyMantisGD** [comment]
copy of mine bruh

**Comment by LightningPandaSO** [comment]
Straight up homie.

**Comment by DragonDude20** [comment]
hey sorry I've been offline for a while

**Comment by DragonDude20** [comment]
How would @Minesraft2 do this, just wondering

**Comment by orangemonkey01** [comment]
he is

**Comment by noimno** [comment]
> ![image](https://user-images.githubusercontent.com/101288516/226679380-ffc88bc3-1372-4fe8-a694-b76ae6478805.png) then read the fucking faq retard

**Comment by noimno** [comment]
not in a offensive way

**Comment by noimno** [comment]
just copying what the sped said, :)

**Comment by noimno** [comment]
not guycoder

**Comment by OGBlooketCheater** [comment]
> What if i told you, DragonDude20, had that dog in them.

W H A t

**Comment by DragonDude20** [comment]
My reaction

**Comment by noimno** [comment]
what?

**Comment by orangemonkey01** [comment]
bro shut up

**Comment by noimno** [comment]
no one asked you monkey bet you look like one in real life thats why your name is monkey

**Comment by noimno** [comment]
monkey

**Comment by orangemonkey01** [comment]
Your are probably a fat kid who does nothing but look for hacks and moderate Discord servers for 2 bucks a week you also sit on your lazy ass and fucking watch anime while eating anything in a 30-foot radius so shut up you fat fuck

**Comment by orangemonkey01** [comment]
also I never said anything to set you off so shut up asshole

**Comment by noimno** [comment]
lets talk about you

**Comment by noimno** [comment]
fat ugly retarded monkey no life no girlfriend no mom no dad no family talking about yourself but acting like it's my life and I don't use discord and your fatass is probably stuffing your face with chips like go to the fucking treadmill fucking fatass work out for once so shut the fuck up and go to the treadmill, so talk to me when your finally not stuffing your fatass with chips.

**Comment by noimno** [comment]
Loser

**Comment by orangemonkey01** [comment]
ok why did you us only that i am fat and eat chips for 90% of your insult how about you start going to school

**Comment by orangemonkey01** [comment]
you know what ill be your teacher

**Comment by orangemonkey01** [comment]
1+1=2 2+2=4

**Comment by Minesraft2** [comment]
Probably will never get added to the repo, but will be added to the project I'm working on.
