### ISSUE TITLE
BUG: Cannot get cheats to open on a dell laptop (chrome browser)

### ISSUE THREAD

**Issue by Bl00man** [Minesraft2/Blooket-Cheats#673]
### Script

Obfuscated

### Problem

Straight up will not open, tried with the license didn't work so I deleted it and that didn't work either. Would really like some help.

**
![image](https://user-images.githubusercontent.com/128631608/226994825-890922ba-dbd6-434d-828e-d95601d4fe9d.png)
**

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by orangemonkey01** [comment]
did you put javascript: in front of it?

**Comment by Minesraft2** [comment]
If it's a school computer they likely blocked javascript:
