### ISSUE TITLE
IDEA: Auto answer

### ISSUE THREAD

**Issue by igenoxnos** [Minesraft2/Blooket-Cheats#674]
### Gamemode

all

### Function

basicly so we all know a way to get a lot of blooket tokens is to answer questions and spin the daily wheel and no one is that crazy to spend an hour answering questions to get a lot of tokens but i found out that if you make a script that targets the answers inside of the set itself and then create a script to make the game think that you clicked the answer but the computer did then you can achieve this goal, but as for the code, i dont know how to make but i think its possible and seeing what all this person did to make this i think he can do it. and also can you make a version of the code to also have the "javascript:" in front of it? because that would make it easyier then to just put it in my search and then just type it in only for it to be deleted.  And i know that this has already been asked by "can yall make infinite tokens" and it being impossible but **THIS** is possible, if you know how to do it right so please consider doing this, i may not check back for another month or 2 but please

### FaQ

I have not read the FaQ

**Comment by Minesraft2** [comment]
You mean an auto answer? We already have that, and if you just want tokens just use getDailyRewards.js

**Comment by orangemonkey01** [comment]
"earlyer" is not a word go to school instead of GitHub kid
