### ISSUE TITLE
IDEA: Fetch script straight from page for bookmarklet 

### ISSUE THREAD

**Issue by Nitroandaccounts** [Minesraft2/Blooket-Cheats#679]
### Gamemode

Whole bookmarklet

### Function

Allows you to not need to fetch latest version.

Implement a similar way to fetch the script as Eruda `javascript:(function () { var script = document.createElement('script'); script.src="//cdn.jsdelivr.net/npm/eruda"; document.body.appendChild(script); script.onload = function () { eruda.init() } })(); `

as you can see, this fetches the script at runtime (click on bookmarklet), so no need to manually update.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Blooket content security policy prevents fetching from sites not in a whitelist.

**Comment by Nitroandaccounts** [comment]
Awww. Great idea, can’t excite :(

**Comment by Minesraft2** [comment]
no
