### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by darkloyd255** [Minesraft2/Blooket-Cheats#686]
### Script

idk.js

### Problem

sometimes ui from the cheat menu will make other UI not work...

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

one example is the next round button in tower defense 2

**Comment by darkloyd255** [comment]
ill do it l

> send a video minesraft check classes of divs and yea

ill do it out of class

**Comment by darkloyd255** [comment]
> send a video minesraft check classes of divs and yea

it's very unreliable, I can't get a good example
all I can say is that if you lined it up in a convenient place in the corner of the tower defense map it would block a button

**Comment by darkloyd255** [comment]
![image](https://user-images.githubusercontent.com/103001982/227341456-843f4fb8-7760-4c54-a577-1366544aad44.png)

**Comment by orangemonkey01** [comment]
what button

**Comment by MasonTheGreat123** [comment]
yea this happed to me before it mean you can't click a button cause it blocked by the gui

**Comment by Minesraft2** [comment]
> yea this happed to me before it mean you can't click a button cause it blocked by the gui

then move the gui

**Comment by orangemonkey01** [comment]
what button tho????

**Comment by MasonTheGreat123** [comment]
> what button tho????

Like any button ex:Start next round

**Comment by darkloyd255** [comment]
> what button tho????

start button

**Comment by darkloyd255** [comment]
im gonna close this now
