### ISSUE TITLE
Can’t find aquatic box to spam buy

### ISSUE THREAD

**Issue by Shensinwu** [Minesraft2/Blooket-Cheats#687]
### Script

Spam buy blooks

### Problem

I’m typing “Aquatic” and it says it can’t find it, did you list it as something else?

### Method

Other (described in Extra Info section)

### Type

Obfuscated

### Extra Info

Mobile GUI so maybe that broke it

**Comment by Minesraft2** [comment]
Make sure you don't put any spaces or punctuation, just the box name. Except for "Ice Monster" you need a space there
