### ISSUE TITLE
IDEA: remove alert box for sending distraction on fishing frenzy

### ISSUE THREAD

**Issue by peepoostpin** [Minesraft2/Blooket-Cheats#688]
### Gamemode

Fishing Frenzy

### Function

its self explanatory, i dont like it and when i send loads, i have to go back and forth

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by darkloyd255** [comment]
> I really don't think you're dumb enough to be unable to remove the alert() line of code.

actually he probably has no idea if that would mess anything up. i am not familiar with the bookmarked version of this and i don't think he would understand how it works either

**Comment by peepoostpin** [comment]
i will do it

**Comment by peepoostpin** [comment]
im not sure about the gui btw
but i can do the separate javascript file

**Comment by Minesraft2** [comment]
Done in the GUI
