### ISSUE TITLE
IDEA: add to the frickin faq

### ISSUE THREAD

**Issue by VillainsRule** [Minesraft2/Blooket-Cheats#689]
### Function

add smth about name changing to the faq

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
what name changing

**Comment by Minesraft2** [comment]
> > what name changing
> 
> being able to change your name in the middle of a game

but I'm not done making it

**Comment by Minesraft2** [comment]
not as long as the simulate scripts
