### ISSUE TITLE
bug: make it so you can copy and paste it on a school device

### ISSUE THREAD

**Issue by MastarMuntai** [Minesraft2/Blooket-Cheats#691]
### Script

everyone

### Problem

make it so u can copy it on a school device pls.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by orangemonkey01** [comment]
it works on mine

**Comment by Blooket000** [comment]
Your school might have blocked every code that starts with javascript: so thats why it doesnt work.

**Comment by benjiboy123456789** [comment]
My teacher somehow did that. gosh dang
