### ISSUE TITLE
BUG: 

### ISSUE THREAD

**Issue by hackthegamezjj** [Minesraft2/Blooket-Cheats#692]
### Script

all of them

### Problem

nothing works stupid

### Method

Pasted script into console

### Type

Obfuscated

**Comment by orangemonkey01** [comment]
you use unobfuscated for console stupid

**Comment by Minesraft2** [comment]
> you use unobfuscated for console stupid

they should both work

**Comment by Minesraft2** [comment]
it's javascript you think obfuscating it would make it not work in the console

**Comment by orangemonkey01** [comment]
i don't code idk

**Comment by orangemonkey01** [comment]
so mb
