### ISSUE TITLE
IDEA: floodGame.js

### ISSUE THREAD

**Issue by Blooket000** [Minesraft2/Blooket-Cheats#695]
### Gamemode

global

### Function

In the gui.js hack, you can choose the amount of bots you want, blook and banner that you want the bot to have. But in the bookmarklet, you can only choose the amount of bots you want in the game but you cannot choose the blook and banner that you wants the bot to have.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by ibe79** [comment]
Cool

**Comment by MasonTheGreat123** [comment]
whys this an idea

**Comment by MasonTheGreat123** [comment]
update your bookmarks

**Comment by orangemonkey01** [comment]
its already a thing how about you check the script lmao

**Comment by Minesraft2** [comment]
Use the GUI, I'm not adding 5 prompts to the other script.
