### ISSUE TITLE
Frenzy hack isnt working

### ISSUE THREAD

**Issue by TheBobCreator** [Minesraft2/Blooket-Cheats#7]
idk

**Comment by TheBobCreator** [comment]
also why does the ESP (tested on gold only), auto answer, and highlight answer work for 1 question only? auto answer doesnt seem to work either. another thing is that once I use a hack, i cant use it again. oof

**Comment by Minesraft2** [comment]
What set are you using these on?

**Comment by TheBobCreator** [comment]
oops i meant all answer correct instead of repeating auto second time

**Comment by Minesraft2** [comment]
yea but what set

**Comment by TheBobCreator** [comment]
i used all answer on monster brawl, auto on gold, and highlight on gold too

**Comment by Minesraft2** [comment]
and the set?

**Comment by TheBobCreator** [comment]
dividing decimals lol

**Comment by Minesraft2** [comment]
could you send me the set link?

**Comment by TheBobCreator** [comment]
ok

**Comment by TheBobCreator** [comment]
https://dashboard.blooket.com/set/62a24276a4ae4c3d769ed7d7

**Comment by TheBobCreator** [comment]
i think all answer is working, nvm

**Comment by Minesraft2** [comment]
Chest ESP isn't a looped cheat

**Comment by TheBobCreator** [comment]
ok

**Comment by Minesraft2** [comment]
unless you're using the gui

**Comment by Minesraft2** [comment]
then it is

**Comment by TheBobCreator** [comment]
k
