### ISSUE TITLE
Bug/idea: Numbers with "e" dont work

### ISSUE THREAD

**Issue by ScytheAwoo** [Minesraft2/Blooket-Cheats#717]
### Script

gui.js

### Problem

Considerably don't know if this would be an idea or bug so I have just done this. Numbers such as: 9e5, 9e10, etc... don't work. I am sure this is due to a letter not being allowed in the text, if possible, please add this back as it used to work.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

**Comment by peepoostpin** [comment]
what part?

**Comment by ScytheAwoo** [comment]
> what part?

like set gold and set crypto, you cant use "e" numbers.

**Comment by Minesraft2** [comment]
I just use `parseInt(prompt("amount:"))`, and you can just get good and add all the 0s.
