### ISSUE TITLE
IDEA: Fake Tokens

### ISSUE THREAD

**Issue by LeozaCEO2** [Minesraft2/Blooket-Cheats#721]
### Gamemode

Global

### Function

Add an amount of tokens you desire that don't actually affect your account using this code: javascript:document. body. contentEditable = 'true'; document. designMode='on'; void 0

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by ijustescapedyesterday** [comment]
its easy to just change the tokens visually bro.
But then it would be up to no use

**Comment by Thing3487** [comment]
It was an idea a had some weeks ago, but villain said it was useless

**Comment by Thing3487** [comment]
If you actually want the code, heres mine:
```
https://github.com/Minesraft2/Blooket-Cheats/blob/5f62a648d6cf78710c62f58492c1e9bd73e90e6a/unobfuscated/global/spoofTokens.js
```

**Comment by Minesraft2** [comment]
@Greenlio put it in the content branch

**Comment by Thing3487** [comment]
What

**Comment by Thing3487** [comment]
I had a pull request some weeks ago, thenn you closed it

**Comment by Thing3487** [comment]
Waaaaaaa

**Comment by Thing3487** [comment]
@Minesraft2

**Comment by Minesraft2** [comment]
> I had a pull request some weeks ago, thenn you closed it

If merged it you'd be added to the contributors, and all you'd be doing is making one cheat

**Comment by Thing3487** [comment]
Ok

**Comment by Thing3487** [comment]
@Greenlio You better  put  my name there

**Comment by Thing3487** [comment]
Just add like a //Made by Thing3487 then i will be happy

**Comment by Thing3487** [comment]
…

**Comment by Thing3487** [comment]
As long as there is credit in the readme then i’m happy

**Comment by peepoostpin** [comment]
i know how to do it manually but its very useless

**Comment by peepoostpin** [comment]
just change the value of "gold" to whatever
[https://www.youtube.com/watch?v=h0xBoejuw_0](https://www.youtube.com/watch?v=h0xBoejuw_0)

**Comment by Consolehecker** [comment]
YOU CAN JUST USE INSPECT ELEMENT

> If you actually want the code, heres mine:
> 
> ```
> let i = document.createElement('iframe');
> document.body.append(i);
> window.prompt = i.contentWindow.prompt.bind(window);
> i.remove();
> 	const amount = prompt('How many tokens to spoof?')
> 	const stateNode = Object.values(document.querySelector('#app > div > div'))[1].children[0]._owner.stateNode;
> 	stateNode.setState({ tokens: amount });
> ```

**Comment by orangemonkey01** [comment]
its blocked on most school chromebooks

**Comment by orangemonkey01** [comment]
so then they cant use it
