### ISSUE TITLE
Not a suggestion but a question

### ISSUE THREAD

**Issue by SnesLover22** [Minesraft2/Blooket-Cheats#724]
### Gamemode

ads

### Function

So for about a week github didn't have your profile and you're back now. Did something happen with you and blooket, or was github being weird?

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by orangemonkey01** [comment]
he was suspended idk why

**Comment by SnesLover22** [comment]
that explains some things now

**Comment by orangemonkey01** [comment]
look in discussions

**Comment by Minesraft2** [comment]
Apparently I had a suspicious login pattern
