### ISSUE TITLE
when i hitnthe bookmark it dont pull up and i cant use it

### ISSUE THREAD

**Issue by YGDhduhsadguyasfg** [Minesraft2/Blooket-Cheats#73]

**Comment by YGDhduhsadguyasfg** [comment]
nothing will work

**Comment by timmytheman123** [comment]
are your bookmarks updated?

**Comment by YGDhduhsadguyasfg** [comment]
yes

**Comment by 9217182672** [comment]
yeah me having the same issue

**Comment by fowntain** [comment]
Your school probably has bookmarklets blocked. Unfortunately, there currently is no way around this, and you can’t use the cheats. Maybe try playing legit lol

**Comment by ZackiBoiz** [comment]
> Your school probably has bookmarklets blocked. Unfortunately, there currently is no way around this, and you can’t use the cheats. Maybe try playing legit lol

👍

**Comment by YGDhduhsadguyasfg** [comment]
they didnt block anything

**Comment by Candleknight** [comment]
Same problem for me too

**Comment by Yerthesweat** [comment]
The scripts all work but the gui dosnt

**Comment by Wilke000** [comment]
> The scripts all work but the gui dosnt

Are you using it on blooket?

**Comment by Yerthesweat** [comment]
> > The scripts all work but the gui dosnt
> 
> 
> 
> Are you using it on blooket?

Tried it on blooket and a random website with the same results

**Comment by Minesraft2** [comment]
Did you put the GUI script in the bookmark manually or did you import the [Bookmarklets.html](https://github.com/Minesraft2/Blooket-Cheats/blob/main/obfuscated/Bookmarklets.html) file?

**Comment by Minesraft2** [comment]
Bookmarklet import tutorial [here](https://github.com/Minesraft2/Blooket-Cheats/blob/main/tutorial/readme.md)
