### ISSUE TITLE
BUG: tooltip is failing

### ISSUE THREAD

**Issue by darkloyd255** [Minesraft2/Blooket-Cheats#730]
### Script

idk.js

### Problem

the tooltip for "Remove Hacks" is broken in the crypto hack section.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

![image](https://user-images.githubusercontent.com/103001982/229537778-6c480c11-cfa6-41d5-945a-ba56a5c07df7.png)

**Comment by Minesraft2** [comment]
Fixed in current version
