### ISSUE TITLE
IDEA: Anti cheat for players to kick hackers.

### ISSUE THREAD

**Issue by otmfyourandomize** [Minesraft2/Blooket-Cheats#732]
### Gamemode

gui or own its own.

### Function

make an anti cheat to kick cheaters.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by otmfyourandomize** [comment]
almost eveyone cheats.

**Comment by noimno** [comment]
what teachers do when they realize their student is hacking:

**Comment by Consolehecker** [comment]
bro kids are gonna hate me for this.

**Comment by Minesraft2** [comment]
It'll be added in the project I'm working on
