### ISSUE TITLE
BUG: (Gui)

### ISSUE THREAD

**Issue by WuzzyFuzz** [Minesraft2/Blooket-Cheats#733]
### Script

gui.js

### Problem

Doesn't work, I made sure it was updated. They might've patched it in the Easter Event.

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Other (described in Extra Info section)

### Type

Obfuscated

**Comment by orangemonkey01** [comment]
[Screen recording 2023-04-04 7.40.37 AM.webm](https://user-images.githubusercontent.com/125912712/229828571-2a6d71c4-ab54-40a0-b4f9-37aca6633b0d.webm)

**Comment by orangemonkey01** [comment]
still works

**Comment by GamerReal** [comment]
[Screen recording 2023-04-04 2.52.18 PM.webm](https://user-images.githubusercontent.com/129895450/229892189-8e22afa9-fdd2-4330-8503-cf8d0082794b.webm)

Doesnt work for me

**Comment by orangemonkey01** [comment]
update it

**Comment by GamerReal** [comment]
It is on the latest version.

**Comment by GamerReal** [comment]
I think so too, I do not know any ways on how to unblock JS if that is the case.

**Comment by GamerReal** [comment]
Also its every command / JS code in the bookmarks, all of them are broken or patched.

**Comment by WuzzyFuzz** [comment]
Yea, my school blocked bookmarklets but it works on my other computer

**Comment by Minesraft2** [comment]
Yea, it seems they did block javascript:, sorry
