### ISSUE TITLE
gives you all blooks permanently 

### ISSUE THREAD

**Issue by noimno** [Minesraft2/Blooket-Cheats#735]
### Gamemode

none

### Function

It allows people to have all blooks instead of faking it by doing it in a game. so basically gives you all blooks permanently.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by noimno** [comment]
best idea

**Comment by Minesraft2** [comment]
You didn't read the faq

**Comment by noimno** [comment]
> You didn't read the faq

sorry didn't know where the faq was.
