### ISSUE TITLE
IDEA: Script idea name (Make the flooded bots do something)

### ISSUE THREAD

**Issue by oofger69** [Minesraft2/Blooket-Cheats#737]
### Gamemode

Global/All of the modes

### Function

Global: Get every answer correct, random answer.
Make them interact like, when in gold quest, they swap gold.

### FaQ

I have not read the FaQ, I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Realswitzer** [comment]
@Minesraft2 close issue when
