### ISSUE TITLE
Luck boost

### ISSUE THREAD

**Issue by ANormalOhioan** [Minesraft2/Blooket-Cheats#740]
### Gamemode

Global

### Function

It increases the chances of hatching a chroma or legendary. Who thinks this should happen?

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Read the faq

**Comment by ANormalOhioan** [comment]
Ok

**Comment by astro34355** [comment]
pls yes

**Comment by Wilke000** [comment]
Read the faq.

**Comment by Wilke000** [comment]
ITS IMPOSSSIBBBBLLLLLELEEEEEEE
