### ISSUE TITLE
edit request

### ISSUE THREAD

**Issue by zek-c** [Minesraft2/Blooket-Cheats#742]
i dont like using ctrl E to hide can i change that to "h" i am asking i will not say the code is mine i will not release it as mine i will keep it in my fork and you can see what i change

**Comment by Minesraft2** [comment]
i already made the keybind editable

**Comment by zek-c** [comment]
i havent seen that ill look around

**Comment by orangemonkey01** [comment]
it is settings

**Comment by orangemonkey01** [comment]
close
