### ISSUE TITLE
IDEA: Get 1k tokens every time on wheel (get daily rewards)

### ISSUE THREAD

**Issue by Co1t0n** [Minesraft2/Blooket-Cheats#748]
### Gamemode

Global

### Function

Just you get the 1k tokens every time you use get daily rewards, i normally get like 40 at MOST and it would be nice to get 1k from the wheel every time if possible

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by LeozaCEO2** [comment]
yea

**Comment by Minesraft2** [comment]
Read the faq

**Comment by Co1t0n** [comment]
it isnt in the faq of getting max daily rewards

**Comment by Co1t0n** [comment]
yeah, we used to have a hack to get the 3x bonus thing so why not this

**Comment by alexleo1** [comment]
yes it is managed but so are blooks and everything and still were able to
use hacks to change stuff on so why cant we get more tokens and stuff

**Comment by orangemonkey01** [comment]
its called spoofing you don't keep the books

**Comment by alexleo1** [comment]
No kidding But hacks work in all gamemode and they do change code and more
to make blooket think you got that stuff like inf coins
