### ISSUE TITLE
IDEA: Show who is using the cheats 

### ISSUE THREAD

**Issue by Mattisgoat** [Minesraft2/Blooket-Cheats#751]
### Gamemode
global
_No response_

### Function

Show who opened the cheats

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Wilke000** [comment]
That actually might be nice to see if someone in your game is using cheats, this would be a host tool

**Comment by Wilke000** [comment]
And maybe it could show like a “!” Next to the name of whoever

**Comment by Mattisgoat** [comment]
yes I hope he does this!

**Comment by Wilke000** [comment]
<img width="1437" alt="Screenshot 2023-04-11 at 12 32 00 PM" src="https://user-images.githubusercontent.com/85253703/231229084-ef0ef2c9-197e-4706-a04a-d2b48ffc3928.png">
Might look smth like this

**Comment by Mattisgoat** [comment]
![Screenshot 2023-04-11 12 45 04 PM](https://user-images.githubusercontent.com/128957176/231232607-e5ee6c10-b69c-4dc3-b50f-c8224bd9cdca.png)

**Comment by Wilke000** [comment]
Ohh mk

**Comment by Mattisgoat** [comment]
I hope he does this

**Comment by Minesraft2** [comment]
I'll do it *if* i ever decide to actually make a gui chat

**Comment by Mattisgoat** [comment]
okay thanks bro, you are a legend for my school

**Comment by Minesraft2** [comment]
I'm not gonna do this for a long time

**Comment by Mattisgoat** [comment]
bro

**Comment by Mattisgoat** [comment]
plz
