### ISSUE TITLE
BUG: autoSellDupesOnOpen.js sells everything you obtain through spamBuyBlooks.js

### ISSUE THREAD

**Issue by SorkoEdu** [Minesraft2/Blooket-Cheats#759]
### Script

autoSellDupesOnOpen.js

### Problem

Whenever using the script in conjunction with spamBuyBlooks.js, it sells everything you obtain.

### Method

Pasted script into console

### Type

Obfuscated

**Comment by Minesraft2** [comment]
yea you probably shouldn't do that then

**Comment by Minesraft2** [comment]
So it turns out auto sell dupes on open is really buggy and shouldn't be used with spam buy blooks. Also, when I made auto sell dupes on open I made it for manually opening packs in the market.
