### ISSUE TITLE
BUG: (obfuscated scripts)

### ISSUE THREAD

**Issue by packmastermc** [Minesraft2/Blooket-Cheats#761]
### Script

all obfuscated scripts

### Problem

scirpts in the obfuscated folder are unobfuscated and modifiable

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

just to let you know that the obfuscated scripts are unobfuscated

**Comment by orangemonkey01** [comment]
no there not

**Comment by Wilke000** [comment]
Compare the obfuscated with the unobfuscated ones

**Comment by Greenlio** [comment]
skill issue

**Comment by Thing3487** [comment]
> skill issue

@Greenlio https://github.com/Minesraft2/Blooket-Cheats/issues/721
Add it
