### ISSUE TITLE
IDEA: Be able to upload your own image onto a blook during a hosted game

### ISSUE THREAD

**Issue by blooketplay** [Minesraft2/Blooket-Cheats#763]
### Gamemode

global

### Function

It just allows a picture to be uploaded (must be square, and if you need to, a specific file format) and everyone can see it not just you.

### FaQ

I have not read the FaQ, I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Not possible

**Comment by Patheticlol** [comment]
this is called making your own blooket game
