### ISSUE TITLE
BUG: Simulate opening a blook does not use the full screen

### ISSUE THREAD

**Issue by blooketplay** [Minesraft2/Blooket-Cheats#764]
### Script

simulateUnlock.js

### Problem

when you use the script, it works but it does not use the full screen when unlocked making it less believable. (Sorry if i seem annoying with these issue reports, do not mean any wrongdoing or harm to you.) Also it shows new in the blook thing but that doesnt really matter because most people will be using this for rare blooks anyways.

### Method

Pasted script into console

### Type

Obfuscated

### Extra Info

here is the normal opening with the cheats then not using the script.
![image](https://user-images.githubusercontent.com/113946410/231597619-70a7baed-e455-4bb4-8563-1e45d73725ab.png)
vs
![image](https://user-images.githubusercontent.com/113946410/231597629-eaa51a76-a19c-4633-a2c0-e8b32319a29c.png)

**Comment by alexleo1** [comment]
these images look the same

**Comment by LeozaCEO2** [comment]
nobody's gonna realize

**Comment by blooketplay** [comment]
when you use the script it looks more obvious, it looks cut off from 2 points

**Comment by Thing3487** [comment]
@Minesraft2 Close

**Comment by LeozaCEO2** [comment]
you can just minimize your screen slightly

**Comment by Minesraft2** [comment]
unable to reproduce
