### ISSUE TITLE
IDEA: Use any banner/title

### ISSUE THREAD

**Issue by blooketplay** [Minesraft2/Blooket-Cheats#765]
### Gamemode

global

### Function

Allows users to have any banner in the game, while in the waiting host to start the game page. sorta like the use any blook thing and the simulate pack thing combined, Its like it gives you that popup and you have to type the banner you want to use
Allows users to have any Title in the game, same reasoning as the banner thing, except, maybe you could type your own title????
Again, sorry if I seem annoying in giving you all these issues that have most likely been asked before.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Thing3487** [comment]
Typing  your own title could be possible with AI

**Comment by Thing3487** [comment]
Or not

**Comment by LeozaCEO2** [comment]
this gives me an idea.

**Comment by Minesraft2** [comment]
This is not possible, we tried.
