### ISSUE TITLE
blooket anyblooksBUG: (script name)

### ISSUE THREAD

**Issue by 1808000026** [Minesraft2/Blooket-Cheats#767]
### Script

All my blooks that are not unlocked yet are still not unlocked yet.

### Problem

All my blooks that are not unlocked yet are still not unlocked yet.

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by Minesraft2** [comment]
We can't give you blooks permanently, only let you use them.
Please read the faq
