### ISSUE TITLE
Update The Cheats Please

### ISSUE THREAD

**Issue by OGBlooketCheater** [Minesraft2/Blooket-Cheats#773]
### Gamemode

All Gamemodes

### Function

update

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
You're the one who's supposed to update

**Comment by OGBlooketCheater** [comment]
> You're the one who's supposed to update

What?

**Comment by Minesraft2** [comment]
> > You're the one who's supposed to update
> 
> 
> 
> What?

Everything in the repo is always the latest version, if it says a script is outdated you have to copy it from here again

**Comment by OGBlooketCheater** [comment]
> > > You're the one who's supposed to update
> > 
> > 
> > What?
> 
> Everything in the repo is always the latest version, if it says a script is outdated you have to copy it from here again

i know i have lastest one but its getting kinda boring that it hasnet had updates in 2 weeks

**Comment by Minesraft2** [comment]
> > > > You're the one who's supposed to update
> > > 
> > > 
> > > What?
> > 
> > 
> > Everything in the repo is always the latest version, if it says a script is outdated you have to copy it from here again
> 
> i know i have lastest one but its getting kinda boring that it hasnet had updates in 2 weeks

I have a life that I live and I also don't see anything that really needs updating at this current moment.

**Comment by OGBlooketCheater** [comment]
> > > > > You're the one who's supposed to update
> > > > 
> > > > 
> > > > What?
> > > 
> > > 
> > > Everything in the repo is always the latest version, if it says a script is outdated you have to copy it from here again
> > 
> > 
> > i know i have lastest one but its getting kinda boring that it hasnet had updates in 2 weeks
> 
> I have a life that I live and I also don't see anything that really needs updating at this current moment.

I mean like the suggestions like custom backgrounds/files on computer as. the background

**Comment by Nitroandaccounts** [comment]
He isn’t a machine. Why would he fix something that isn’t broken. Is he supposed to entertain you because you are getting bored? Do you pay him? He made these cheats and worked hard on them, there really are enough cheats, and very little enchantments needed. You can make a pull request, or a specific suggestion.

**Comment by Minesraft2** [comment]
Fr
