### ISSUE TITLE
IDEA: Stretchy blooks

### ISSUE THREAD

**Issue by guycoder3** [Minesraft2/Blooket-Cheats#774]
### Gamemode

global

### Function

it makes your blook stretchy

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by OGBlooketCheater** [comment]
if he could do that it would only be client side most likely

**Comment by guycoder3** [comment]
yeah
my brain comes up with sh!tty thoughts

**Comment by Thing3487** [comment]
@Minesraft2 Close, this is useless

**Comment by UsefullCoder** [comment]
Bro, close this. It is possible just code it ur self and if you don't know how to code and all you do is make issues, get some help.

**Comment by Minesraft2** [comment]
don't tell me what to do

**Comment by guycoder3** [comment]
i didnt mean for this to actually for this to be in the cheats lol

**Comment by guycoder3** [comment]
lol

**Comment by Staraner** [comment]
imagines if he does this 💀

**Comment by noimno** [comment]
so you add this which seems impossible but you cant do it to issue #784 .__.

**Comment by Minesraft2** [comment]
I don't feel like adding multiple files to the repo for a visual script, so I'll just leave it here
```js
$('style').sheet.insertRule(`.${$("[class*='_blook_']").className} { transform: scale(1, 2) }`);
```
