### ISSUE TITLE
BUG: Spamm Open Blooket pack or Auto Sell Dupe REALLY BAD BUG!!!!!! 

### ISSUE THREAD

**Issue by Razodragon136** [Minesraft2/Blooket-Cheats#777]
### Script

Spam open Blook pack

### Problem

Ok, so first things first. WONDERFUL HACKS!!! Love trolling my classmates with them. So, today I was saving up a whole lot of tokens for when I reach level 100, which I did today. I had about 2,000 tokens, so I open the GUI hack menu and start the Spam open blook pack. I want to fully HAVE the blooks, even though I do use the Use any blook code. So, I'm opening the packs, trying to get the baby shark sense I had everything else. So, after a few tries with spamming 50, I get the baby shark, and also another new one that i did not see the cause I was spamming then like a mad man, so I thought I got a chroma or something. So, I got to my Blooks, and I did not have the baby shark, and lose the boots and octopus. I head back over, think they were sold someone how, thinking that the auto sell dupe was bugged, but no money. This definitely needs to be fixed, in case someone who has a chroma or something that very hard to get like the Megalodon. That has a open chance of 0.03% and would take forever to get again. Thanks!

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by Thing3487** [comment]
@Minesraft2 Close, duplicate issue

**Comment by Minesraft2** [comment]
> @Minesraft2 Close, duplicate issue

wheres the dupe

**Comment by Minesraft2** [comment]
Spam buy doesn't sell anything. You might've had auto sell on open toggled on, but even that won't sell legendaries. I'm not exactly sure what caused the issue so I can't really fix it.
