### ISSUE TITLE
Have stats page use any blook for profile picture

### ISSUE THREAD

**Issue by Ljduley12** [Minesraft2/Blooket-Cheats#778]
### Gamemode

Global

### Function

When on stats page you can pick any blook to use for your profile picture and it will stay

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Ljduley12** [comment]
Also will there be a duplicate blooks script?

**Comment by Minesraft2** [comment]
> Also will there be a duplicate blooks script?

read the faq
