### ISSUE TITLE
Is there gonna be a way to predict your next roll from pack

### ISSUE THREAD

**Issue by Ljduley12** [Minesraft2/Blooket-Cheats#779]
### Gamemode

Global

### Function

See what get next from any pack

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Thing3487** [comment]
It’s possible

**Comment by Minesraft2** [comment]
> Could be possible

Tf no it isn't

**Comment by Realswitzer** [comment]
As far as “predicting” based off of statistical probability, I suppose
```py
x = random.randint(1,10000)
if x < y:
  print(“Predicted blook: [blook name]”)
elif…
```
(already made, “simulate open pack” script or whatever its called)

As far as seeing what you will guaranteed get, not possible (done server side)

**Comment by Thing3487** [comment]
> > Could be possible
> 
> Tf no it isn't

Ohh i see, the inspect tick only works after you open the pack

**Comment by Thing3487** [comment]
*trick

**Comment by Minesraft2** [comment]
not possible
