### ISSUE TITLE
IDEA: pick what you catch

### ISSUE THREAD

**Issue by thebigbozo** [Minesraft2/Blooket-Cheats#780]
### Gamemode

Fishing frenzy

### Function

a message in javascript  pops up and asks you to type in a book in the game then you will answer normally and you will get the blook after the question is answered correctly.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by guycoder3** [comment]
thats awesome

**Comment by Pizza0987654321** [comment]
Wow

**Comment by OGBlooketCheater** [comment]
ADD THIS!!

**Comment by Educational-hacker** [comment]
@Minesraft2 is this server side or client side

**Comment by Minesraft2** [comment]
client

**Comment by Wilke000** [comment]
Actually, this is a good idea. One of the best I’ve seen.

**Comment by CoderBoyCodes** [comment]
If it was possible to do, then we would have done it 1 year ago, or at least migrated it from generation to generation damn

**Comment by thebigbozo** [comment]
@CoderBoyCodes  damn bro

**Comment by Minesraft2** [comment]
Ok ok, it _is_ possible, I just don't feel like doing it because I would have to add in each min and max weight for each blook, and then randomly get a value from that range and a whole bunch of other stuff.
