### ISSUE TITLE
IDEA: Open Until Blook

### ISSUE THREAD

**Issue by Staraner** [Minesraft2/Blooket-Cheats#782]
### Gamemode

Market

### Function

First, type the blook you are targeting, then it will open packs until you get one or if you ran out of tokens, it will say "Failed to get blook" or whatever like that.

MESSI

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by blooketplay** [comment]
Seems interesting

**Comment by Wilke000** [comment]
Thats actually not a bad idea

**Comment by Wilke000** [comment]
Or like until you get a rarity or above for example if you entered epic it would keep everything epic and above

**Comment by noimno** [comment]
really helpful because I spent lots of coins to get all blooks so this will help instead of spending 2000 on a pack and 10000 on all 3 packs I needed

**Comment by Staraner** [comment]
> Or like until you get a rarity or above for example if you entered epic it would keep everything epic and above
