### ISSUE TITLE
IDEA: kick people out of the game

### ISSUE THREAD

**Issue by noimno** [Minesraft2/Blooket-Cheats#784]
### Gamemode

all

### Function

so, if their is someone you hate, and they are in your Blooket game you can kick them out. so you can kick out who is in first or stuff like that.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by OGBlooketCheater** [comment]
Do u mean like you can kick people when you are not the host?

**Comment by noimno** [comment]
yes

**Comment by noimno** [comment]
your teacher can join and you can kick them :)

**Comment by noimno** [comment]
probably just students you can kick cause you cant kick the host

**Comment by Minesraft2** [comment]
Not possible

**Comment by noimno** [comment]
bruh

**Comment by noimno** [comment]
could have just closed this ._.

**Comment by noimno** [comment]
ima do it just instead

**Comment by Patheticlol** [comment]
# IDEA: Shut the f*ck up
