### ISSUE TITLE
BUG: Simulate Unlock

### ISSUE THREAD

**Issue by Staraner** [Minesraft2/Blooket-Cheats#785]
### Script

SimulateUnlock.js

### Problem

The problem is I tried to use the hack and nothing happened so I open console and there was an error.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

### Extra Info

I accendently closed the idea so here it is: https://github.com/Minesraft2/Blooket-Cheats/issues/782

**Comment by Minesraft2** [comment]
what was the error

**Comment by Staraner** [comment]
Idk I dont know java

**Comment by Minesraft2** [comment]
fixed
