### ISSUE TITLE
IDEA: Force Gamemode

### ISSUE THREAD

**Issue by Razodragon136** [Minesraft2/Blooket-Cheats#787]
### Gamemode

ANY

### Function

We I think of a force game mode script, I think of it being able to choose the game mode on a player end. This probably is not possible but if it is it probably only going to work when the game is not running yet.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by noimno** [comment]
probably gonna get closed. but good idea

**Comment by J-J-D1000** [comment]
cool

**Comment by Minesraft2** [comment]
Not possible
