### ISSUE TITLE
IDEA: Script idea name

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [Minesraft2/Blooket-Cheats#788]
### Gamemode

All

### Function

A scrip that makes you stay a lit ahead of the first second place person you stay in first place.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by OGBlooketCheater** [comment]
![Screen Shot 2023-04-19 at 12 29 59 PM](https://user-images.githubusercontent.com/124519462/233154028-1096a5b2-6289-4c37-ae3a-2c47a13c6e9f.png)
WHAT-

**Comment by Greenlio** [comment]
Very specific use case

**Comment by StackMC123** [comment]
Good idea

**Comment by Minesraft2** [comment]
mid

**Comment by StackMC123** [comment]
Bruh why notThank You,ElijahOn May 4, 2023 7:32 PM, Aerell ***@***.***> wrote:
Closed #788 as not planned.

**Comment by Minesraft2** [comment]
That script would be as big as the gui

**Comment by Minesraft2** [comment]
And I'm already working on an auto play
