### ISSUE TITLE
GUI not in the package when imported

### ISSUE THREAD

**Issue by baddy153678** [Minesraft2/Blooket-Cheats#793]
### Script

gui.js

### Problem

so I imported it using the bookmarklets method and when I open the thing, all the hacks are in their folders, but the mobile GUI and the GUI are not, I tried re-importing the thing with no luck, I tried both unobfuscated and obfuscated folders both with no luck, any info will help thanks!

### Method

Imported Bookmarklets.html

### Type

Unobfuscated, Obfuscated

### Extra Info

im doing this on my personal mac and importing it into my school account on google (i cant import stuff on my chromebook so i had to do it on my mac)

**Comment by Minesraft2** [comment]
You might have to just drag the cheats from [here](https://minesraft2.github.io/Blooket-Cheats) to your bookmarks bar

**Comment by baddy153678** [comment]
How do I import them separately?

**Comment by baddy153678** [comment]
When you say drag, do you mean like just drag and drop or do I have to do something else

**Comment by Blooket000** [comment]
drag and drop

**Comment by Educational-hacker** [comment]
the hax work on chromebook, but gui dosnt work on chromebook

**Comment by Educational-hacker** [comment]
no gui tho

**Comment by Minesraft2** [comment]
The gui probably got too big for importing, you'll just have to make the bookmark manually then.
