### ISSUE TITLE
BUG: Sell Cheap Duplicates

### ISSUE THREAD

**Issue by JonJonShe** [Minesraft2/Blooket-Cheats#794]
### Script

SellCheapDuplicates

### Problem

Thank you minesraft for the wonderful hacks. I have been using for over 1 year.

I tried to use the new sell cheap duplicates hack today. Everytime I tried to do so, it said "There was an error user data."
I tried to enter it into the consol but it said a red x with "vendors~main~253ae210.6a3d95f8c6f7b972d7de.js?15c7d5f02300a8f81cf7:3     PUT https://dashboard.blooket.com/api/users/sellblook 404
(anony" as the error message.

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by fo-od** [comment]
i dont know if this has anything to do with anything but i found this
![image](https://user-images.githubusercontent.com/99752044/233450674-95b6cd41-6752-4760-a1b1-da128e38778e.png)
