### ISSUE TITLE
BUG: Simulate Unlock Not Working

### ISSUE THREAD

**Issue by SacredSorceror** [Minesraft2/Blooket-Cheats#797]
### Script

simulateunlock.js

### Problem

when you try to run the command, this error pops up in console and it does nothing.

![Screenshot 2023-04-20 161359](https://user-images.githubusercontent.com/131404614/233477856-7122e486-b4da-4891-b0ea-7fbe0a83d46d.png)

this error: 
caught TypeError: Cannot read properties of undefined (reading 'exports')
    at <anonymous>:1:49106
    at Array.reduce (<anonymous>)
    at O.global.run (<anonymous>:1:49037)
    at Object.<anonymous> (<anonymous>:1:15357)

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated

**Comment by Minesraft2** [comment]
fixed
