### ISSUE TITLE
IDEA: a legit duck

### ISSUE THREAD

**Issue by guycoder3** [Minesraft2/Blooket-Cheats#798]
### Gamemode

global

### Function

legit makes a duck spawn on screen

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Consolehecker** [comment]
what the hell

**Comment by OGBlooketCheater** [comment]
Like this?
![Screen Shot 2023-04-24 at 9 02 33 AM](https://user-images.githubusercontent.com/124519462/234019922-ba285270-e42a-4030-b4ee-6d16bbe95502.png)

**Comment by OGBlooketCheater** [comment]
"100% virus free WINIKE FACE"
NAH

**Comment by OGBlooketCheater** [comment]
> Like this? ![Screen Shot 2023-04-24 at 9 02 33 AM](https://user-images.githubusercontent.com/124519462/234019922-ba285270-e42a-4030-b4ee-6d16bbe95502.png)

@guycoder3

**Comment by OGBlooketCheater** [comment]
like that desktop goose thing?

**Comment by guycoder3** [comment]
yes
like that

**Comment by OGBlooketCheater** [comment]
> yes like that

probably not possible tbh

**Comment by OGBlooketCheater** [comment]
is*

**Comment by guycoder3** [comment]
what have i done

**Comment by peepoostpin** [comment]
loading a duck on the screen is possible, the blook or a random stock image

**Comment by Educational-hacker** [comment]
bruhhh this is sus as fudge

**Comment by peepoostpin** [comment]
might violate content security policy when loading the image

**Comment by Realswitzer** [comment]
would probably be easiest (or at least keep file size low-ish) to use svg although i guess could try loading the image as a base64 encoded image. would create massive sized script though (relative to everything else, even in the best case scenario) and depending on how it works, there could be a lot more problems not even mentioned.

**Comment by Minesraft2** [comment]
bro no
