### ISSUE TITLE
IDEA: Crypto auto choice

### ISSUE THREAD

**Issue by Heliosynthis** [Minesraft2/Blooket-Cheats#817]
### Gamemode

Crypto Hack

### Function

We have this for Gold Quest and used with auto answer it automates the game completely, we need this for Crypto Hack ASAP!!!!

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by guycoder3** [comment]
i tink its awredy dear

**Comment by Heliosynthis** [comment]
minesraft2 why is there a bruh label on this now? It's a valid point I don't see why there isn't an auto choice for Crypto Hack

**Comment by Minesraft2** [comment]
> minesraft2 why is there a bruh label on this now? It's a valid point I don't see why there isn't an auto choice for Crypto Hack

Because in crypto hack theres only one option, no matter which box you choose. Gold quest has one because the box you choose is important
