### ISSUE TITLE
First place

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [Minesraft2/Blooket-Cheats#820]
### Gamemode

ALL

### Function

The script allows you to stay in first place, but not have so much more than the second-place person so you are not suspicious. The script would auto play the game for you. 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by GITHUBTRASHACCOUNT** [comment]
a bot like cool instance

**Comment by Educational-hacker** [comment]
still possible tho

**Comment by Minesraft2** [comment]
If you can't get to first place using every other cheat on the repository, that is a major skill issue and you should probably get that checked out
