### ISSUE TITLE
QUESTION: How do you find this... please don't ignore, reason:

### ISSUE THREAD

**Issue by JavascriptCoder5400** [Minesraft2/Blooket-Cheats#828]
### Gamemode

No gamemode

### Function

@Minesraft2 This is a question, not a suggestion (unless you consider the other part to be).
I've been using your main access code for changing the state and props and other objects, which is 'var o=Object.values(document.querySelector("#app > div > div"))[1].children[0]._owner.stateNode;' for most of my own debugging and coding (like a massive answer buff that I created which gives the player up to the daily limit worth of tokens and xp, which SHOULD NOT be used in a class blooket if I post it because the teacher can look at the stats at the end, unless you delete that game history off of your account and use 2 different names. I suggest that you add it to your GUI and other hacks. It works without a lack of semicolons for bookmarklet hacks, ask for more info). But my only question is this: In the code, Blooket sets the state by using "this.setState(Object);". How did you find the value of "this" in the inspect developer console to use as the variable "o"? I would appreciate this, as I am working on other hacks. I found the scripts, I just don't know how to access "this" in the scripts. Thank you for reading this.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by JavascriptCoder5400** [comment]
I am using a chromebook by the way.

**Comment by JavascriptCoder5400** [comment]
Actually, nevermind. I just figured it out.

**Comment by peepoostpin** [comment]
like finding statenode in devtools?

**Comment by JavascriptCoder5400** [comment]
Yes. Finding stateNode in the developer console is tough for other applications that are not Blooket. I'm trying to make hacks for other apps like schooling apps so that I can
