### ISSUE TITLE
IDEA: Bot autoplay

### ISSUE THREAD

**Issue by Consolehecker** [Minesraft2/Blooket-Cheats#829]
### Gamemode

Global

### Function

Basically, a toggle button in the bot send menu where you can make it so the bots autoplay, or if they don't autoplay. Also just the ability for bots to autoplay is nice

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Im not making a script bigger than the gui itself
