### ISSUE TITLE
First place

### ISSUE THREAD

**Issue by RONAKPATELLLLLLL** [Minesraft2/Blooket-Cheats#830]
### Gamemode

ALL

### Function

The script allows you to stay in first place, but not have so much more than the second-place person so you are not suspicious. The script would auto play the game for you.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Educational-hacker** [comment]
add bruh label

**Comment by Minesraft2** [comment]
duplicate
