### ISSUE TITLE
spam open blooks dose not work

### ISSUE THREAD

**Issue by davdadev** [Minesraft2/Blooket-Cheats#831]
### Function

rspam open blooks dose not work 

### FaQ

I have not read the FaQ

**Comment by Educational-hacker** [comment]
this is a bug not enhancement are you high

**Comment by davdadev** [comment]
> this is a bug not enhancement are you high

sorry first time plzdont be rude

**Comment by iplayblooket** [comment]
i found the same issue...

**Comment by OGBlooketCheater** [comment]
![Screen Shot 2023-05-04 at 8 40 38 AM](https://user-images.githubusercontent.com/124519462/236223050-17cf6456-a63a-44c0-b279-a82502e14e7a.png)
THEN READ THE FaQ THEN

**Comment by Minesraft2** [comment]
> ![Screen Shot 2023-05-04 at 8 40 38 AM](https://user-images.githubusercontent.com/124519462/236223050-17cf6456-a63a-44c0-b279-a82502e14e7a.png)
> 
> THEN READ THE FaQ THEN

it's a bug report not a suggestion

**Comment by Blooketuser5262** [comment]
Yeah, I can confirm that it doesn't work, even with GUI and regular hacks.

**Comment by CoderBoyCodes** [comment]
Yep, I think its an variable or system issue as if it still executes the script (it says Results: 0ms) but it doesn't execute a proper hack guide, i have an restored version but im aware its from minecraft himself

**Comment by Minesraft2** [comment]
> Yeah, I can confirm that it doesn't work, even with GUI and regular hacks.

When did you last update your cheats

**Comment by CoderBoyCodes** [comment]
> > Yeah, I can confirm that it doesn't work, even with GUI and regular hacks.
> 
> When did you last update your cheats

I just updated the script, hoping it was just an outdate but it sounds that maybe the paths are deformed somehow?

**Comment by CoderBoyCodes** [comment]
The scripts are uploaded by you, maybe there's an error with the variables/consts? or incorrect paths are written?

**Comment by MyDude124** [comment]
💀

**Comment by MyDude124** [comment]
💀

**Comment by Minesraft2** [comment]
Fixed 👍

**Comment by davdadev** [comment]
still dose not work
