### ISSUE TITLE
Add 99999 tokens instead of only 500 tokens in get daily rewards

### ISSUE THREAD

**Issue by Pizza0987654321** [Minesraft2/Blooket-Cheats#832]
### Gamemode

Global

### Function

Add 99999 tokens instead of only 500 tokens in get daily rewards

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Blooket000** [comment]
Read the FaQ

**Comment by Blooket000** [comment]
Its not possible

**Comment by davdadev** [comment]
i have tried it kicks you for a mouth

**Comment by Pizza0987654321** [comment]
But it didn’t say how much is max tokens

**Comment by davdadev** [comment]
they must change the max

**Comment by Minesraft2** [comment]
Read the FAQ, infinite tokens isn't possible and doing this would just suspend your account for a month
