### ISSUE TITLE
Permission request

### ISSUE THREAD

**Issue by Hankypoo7** [Minesraft2/Blooket-Cheats#833]
Hello @Minesraft2, I am going to try to rebuild my repo from scratch. May I have permission to use [this](https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/everyAnswerCorrect.js) code and distribute it without taking any credit whatsoever. I will give you full privlages on my repo and I will invite you to colaborate. Can I use it?

**Comment by Minesraft2** [comment]
no

**Comment by Hankypoo7** [comment]
> no

ok fair enough
