### ISSUE TITLE
The Blooket cheat for daily tokens isn't working

### ISSUE THREAD

**Issue by matteoKLIP** [Minesraft2/Blooket-Cheats#84]
What's happening is, whenever you make a bookmark on google and put the code, when i go into blooket play the code doesn't work like it's not opening up a box that says tokens awarded

**Comment by Minesraft2** [comment]
How are you putting the code in?

**Comment by matteoKLIP** [comment]
im putting javascript: and then i paste the code

**Comment by matteoKLIP** [comment]
sorry i took so long to comment

**Comment by Minesraft2** [comment]
https://github.com/Minesraft2/Blooket-Cheats/blob/main/tutorial/readme.md
