### ISSUE TITLE
unlock limited time packs

### ISSUE THREAD

**Issue by Pizza0987654321** [Minesraft2/Blooket-Cheats#843]
### Gamemode

Global

### Function

Unlocks limited time packs

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Realswitzer** [comment]
pretty sure it’s impossible, server sided

**Comment by blooketplay** [comment]
just use the use any blook if you really want to use them

**Comment by Pizza0987654321** [comment]
Did Minesraft2 delete account or what

**Comment by Realswitzer** [comment]
No, his github is still there and same with discord.

**Comment by Educational-hacker** [comment]
its server side, so is impossible as server decides when pack comes out.

**Comment by CoderBoyCodes** [comment]
> just use the use any blook if you really want to use them

if thats your thought then no need for any hack we just need the any blook

**Comment by emk1900** [comment]
make an option where u can unlock all blooks permanently and sell them to make cheap tokens.
