### ISSUE TITLE
IDEA: Sell Unlimited Packs (Ex: Space, Aquatic, ...)

### ISSUE THREAD

**Issue by Staraner** [Minesraft2/Blooket-Cheats#844]
### Gamemode

Global

### Function

I have a collection of limited blooks and I don't want to sell them, sometimes I open the space pack and not getting a chroma so I want to sell the space blooks but it takes a long time because I can't use sell dupes because I will sell my limited blooks.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Blooket000** [comment]
Use sell cheap duplicates.

**Comment by Blooket000** [comment]
And only duplicate blooks from common to epic will be sold.

**Comment by Staraner** [comment]
But I also have limited uncommons to epics tho

**Comment by darkloyd255** [comment]
true but what's the point of having multiple of anything because if you get a dupe chroma then that's a free 300 tokens

**Comment by StackMC123** [comment]
Just solo sell them and stop being lazy about it. There's less than 20 blooks in the space pack it should be easy.

**Comment by Staraner** [comment]
> true but what's the point of having multiple of anything because if you get a dupe chroma then that's a free 300 tokens

Saving for trading btw I have 4 frozen fossils

**Comment by Theuprise** [comment]
2 Teal Platypuses

**Comment by Minesraft2** [comment]
I'm not gonna make a sell script for every single way you can sell blooks. Do it manually.
