### ISSUE TITLE
Don’t know how to activate with a school iPad 

### ISSUE THREAD

**Issue by peepeepoo69** [Minesraft2/Blooket-Cheats#849]
How can I use the hacks for Blooket on a school iPad.. I’m kind of stuck on how to do it..

**Comment by MasonTheGreat123** [comment]
trick is, You CAN'T

**Comment by btuyt2** [comment]
> Help

you can just copy the mobile gui and put "javascript:" and paste the cheat  and save the bookmark

**Comment by StackMC123** [comment]
I have tried previously using Blooket Hacks on A iPad. When I use the JavaScript command it does not work and takes me to a google search.

**Comment by EnderC00kiez** [comment]
use the shortcuts app then

**Comment by Its-Epsilon-Eridani** [comment]
https://www.youtube.com/watch?v=xOKupnfCEgY

worked on mine.

**Comment by Greenlio** [comment]
answered
