### ISSUE TITLE
Permanant

### ISSUE THREAD

**Issue by MrNegative99** [Minesraft2/Blooket-Cheats#85]
This doesn't work permanently im not sure if this is supposed to work like that but if it's not could u pls fix it

**Comment by Minesraft2** [comment]
It can't work permanently, that's all done on the server side

**Comment by MrNegative99** [comment]
oki thx but how do i get it permenantly

**Comment by VillainsRule4000** [comment]
> oki thx but how do i get it permenantly

you don't.
evidently you can't code, so why are you here?
to make "issues" that don't matter?
go away bro 💀 no one likes you

**Comment by Wilke000** [comment]
No one likes you either villains

**Comment by VillainsRule4000** [comment]
> No one likes you either villains

why are you here either 🤣 
you can't code 🤣

**Comment by fowntain** [comment]
> No one likes you either villains

Sided with villains here, mind your own business please Wilke.

**Comment by fowntain** [comment]
your pfp is literally the roblox logo

**Comment by VillainsRule4000** [comment]
> your pfp is literally the roblox logo

roblox fell off
so cheap they couldn't pay for a STOLEN SOUND

**Comment by Wilke000** [comment]
Villains, I do know how to code you can check my Replit account wilke000. Also, Minesraft, your hacks are awesome, but Villains is not. 😁

**Comment by fowntain** [comment]
> > your pfp is literally the roblox logo
> 
> roblox fell off so cheap they couldn't pay for a STOLEN SOUND

FRRR

**Comment by fowntain** [comment]
> Villains, I do know how to code you can check my Replit account wilke000. Also, Minesraft, your hacks are awesome, but Villains is not. 😁

bro uses replit 💀

**Comment by fowntain** [comment]
fell off
