### ISSUE TITLE
Is Blooket constantly changing up their api?

### ISSUE THREAD

**Issue by SnesLover22** [Minesraft2/Blooket-Cheats#851]
### Gamemode

all

### Function

There used to be a hack out there that let you add tokens and xp, but that was a while back, maybe around 2021, but as you said yourself, that all runs in the backend. So in theory, does this mean that your blooket cheats will stop running at all someday?

Also, are you saying there is no way to mess around with the backend? I think that there is a possibility that you can do that...

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Minesraft2** [comment]
Only the cheats that interact with the api could go down permanently at some point. And we'll likely never have full access to the backend.

**Comment by ThetruePyrobyte** [comment]
It's very possible
