### ISSUE TITLE
BUG: AlwaysQuintupleCrypto

### ISSUE THREAD

**Issue by StackMC123** [Minesraft2/Blooket-Cheats#852]
### Script

AlwaysQuintupleCrypto.js

### Problem

I have tried using it using bookmarklet instead of console. (because my school Chromebook's console is blocked.) And it doesn't work.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Educational-hacker** [comment]
half the hax don work on chromebook, its just compatibility issue

**Comment by StackMC123** [comment]
It does you just have to use mainThank You,ElijahOn May 15, 2023 7:31 AM, Educational-hacker ***@***.***> wrote:
half the hax don work on chromebook, its just compatibility issue

**Comment by Minesraft2** [comment]
Quintuple crypto is on the Content branch, and that branch is unmanaged. Fr just use set crypto
