### ISSUE TITLE
Usage Question 

### ISSUE THREAD

**Issue by Midnight3052** [Minesraft2/Blooket-Cheats#861]
Hello! I am a school student. At school me and some other kids created a google document (just for us 4 kids, not a lot of people)  which links to github pages for all of your blooket hacks. Sadly, our school blocked github meaning we can no longer access your code at school. (they have tough security) I just want to ask if I could possibly put your code up on my website (not publicly, requiring a password) so we can use it at school.

Thanks, 
Midnight3052

**Comment by Wilke000** [comment]
If they blocked it how r u here

**Comment by Midnight3052** [comment]
I am on my personal computer

**Comment by Wilke000** [comment]
Bookmarklets and sync
Ez

**Comment by Midnight3052** [comment]
there are like 500 hacks

**Comment by FuckNico** [comment]
use a unblocker

**Comment by Greenlio** [comment]
Import using bookmarklets.html
