### ISSUE TITLE
BUG: hacks dont work

### ISSUE THREAD

**Issue by guycoder3** [Minesraft2/Blooket-Cheats#868]
### Script

everything

### Problem

your hacks are broken bucko

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by Minesraft2** [comment]
Well idk what you could be doing wrong it's still working for me

**Comment by Minesraft2** [comment]
Oh nevermind I'm having the issue now, I'll look into it when I get home

**Comment by WPokeice** [comment]
alr
