### ISSUE TITLE
I can't import.

### ISSUE THREAD

**Issue by ArsonMason** [Minesraft2/Blooket-Cheats#87]
I discovered your HTML code for blooket and wanted to try it since I have never used an HTML cheat, but after I copied the code and tried to import it into Bookmarklets, there was no import button. Just none. I can send a picture VIA e-mail if you want to see what I see. Maybe this has happened to someone else too but I can't find anything online telling me how to fix this. Do you know how to fix my problem or have any alternatives? My friends say that this is the best blooket codes that they use.

**Comment by Minesraft2** [comment]
Which browser are you using?
