### ISSUE TITLE
BUG: (Getting Daily Rewards Not Working)

### ISSUE THREAD

**Issue by Zi2127** [Minesraft2/Blooket-Cheats#873]
### Script

getDailyRewards.js

### Problem

The script isn't working and I can't get the daily rewards

### Method

Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

### Extra Info

![image](https://github.com/Minesraft2/Blooket-Cheats/assets/133806436/d0dd2a56-cc68-4531-8bd4-e585ef1bd4ba)

**Comment by ruger2714** [comment]
its not working for me either

**Comment by Zi2127** [comment]
> its not working for me either

Ohh alright
