### ISSUE TITLE
Cheating is now detected

### ISSUE THREAD

**Issue by blaze137524** [Minesraft2/Blooket-Cheats#879]
Apparently as of the new bug that made it not work on 5/16/23  , blooket is now somehow(its really weird on my screen, and even weirder when switching devices) able to detect cheating. my account has been suspended for a month. I can log in on my school Chromebook no problem, but anything else it wont let me, and the cheats still don't work on the cb.  probably the part where it doesn't allow it to detect if u are cheating needs to be updated.

**Comment by Pyro77** [comment]
The Blooket police got my alt account

**Comment by Its-Epsilon-Eridani** [comment]
Just tested, definitely detects.

**Comment by CrownCreations** [comment]
so we cant hack anymore i tried it, it didnt work i also used a vpn and it didnt work

**Comment by themightyirish** [comment]
this is bullshit
