### ISSUE TITLE
Daily rewards got me SUSPENDED from blooket

### ISSUE THREAD

**Issue by Theuprise** [Minesraft2/Blooket-Cheats#881]
### Script

Getdailyrewards.js

### Problem

Was trying to use the daily rewards cheat and you got me SUSPENDED. JERKFACE.

### Method

Pasted script into console

### Type

Obfuscated

### Extra Info

Multiple reports of issues

**Comment by spamspamE** [comment]
They updated their anticheat don't use the mods until they make more hacks

**Comment by Theuprise** [comment]
Just wanted to say, I'm sorry for calling names.
