### ISSUE TITLE
Dont Actually use this

### ISSUE THREAD

**Issue by MEGladot** [Minesraft2/Blooket-Cheats#885]
### Script

Gui.js

### Problem

This code itself is great, and it works amazing, but using will get you suspended from blooket.

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

But overall, its a great idea

**Comment by Wilke000** [comment]
It used to work. Earlier today blooket updated their anticheat.

**Comment by MEGladot** [comment]
I have nothing against the creator of this code, or the code itself, but I can't use my blooket account anymore and I didn't do anything. This is happening to tons of other people too :)

**Comment by Minesraft2** [comment]
I mean you did do _something_, otherwise you wouldn't be suspended

**Comment by Nicholas3330** [comment]
> I mean you did do _something_, otherwise you wouldn't be suspended

Can you create a hack to get around the suspension
