### ISSUE TITLE
BUG: I got violation and banned

### ISSUE THREAD

**Issue by Maxtherocketguy001** [Minesraft2/Blooket-Cheats#887]
### Script

Unsure 

### Problem

Got banned

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by iw09warrior** [comment]
i was against terms of service

**Comment by javascriptvictor** [comment]
Do "Prevent Suspension" next time you try to cheat or just use alt accounts

**Comment by Issac2110** [comment]
i also but i only got suspended for 5 days.
