### ISSUE TITLE
BUG: YOU CANT CHEAT ANYMORE DONT TRY IT

### ISSUE THREAD

**Issue by Co1t0n** [Minesraft2/Blooket-Cheats#888]
### Script

all of them

### Problem

I GOT BANNED FOR TWO MONTHS AND ALL I DID WAS OPEN THE GUI, MY FRIEND INSTALLED THIS THING AND TOLD ME TO CLICK THE BOOKMARKLET AND IT BANNED MEe

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by Minesraft2** [comment]
Yea ik but i already fixed that so ¯\_(ツ)_/¯
