### ISSUE TITLE
BUG: GUI Doesn’t work

### ISSUE THREAD

**Issue by Jackson347** [Minesraft2/Blooket-Cheats#889]
### Script

GUI.js

### Problem

Yes, you fixed the problem where you don’t get insta banned, but the gui doesn’t completely work. For instance, all the games, you can’t set your gold or enable esp and on global, you can’t toggle all answers are correct. While you’re on the main screen and go to blooks, you are able to enable all blooks, but if you are in the lobby for a game, you can’t enable all blooks 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by JonJonShe** [comment]
So the hacks are not working right.

**Comment by Jackson347** [comment]
> So the hacks are not working right.
> 
> 
> 
> 

That's what it seems. Like I said, you can have all blooket as long as you are looking at all the blooks on the main page. How ever in modes like factory and crypto, none of the hacks work. And I'm the global, you can get daily rewards,  it toggle to answer questions doesn't work. But the sims and stuff work.

**Comment by JonJonShe** [comment]
huh

**Comment by Jackson347** [comment]
> huh

No, the hacks aren't working 100%
