### ISSUE TITLE
The gui just don’t work both of them and all the hacks don’t work

### ISSUE THREAD

**Issue by YourlocalFemboy** [Minesraft2/Blooket-Cheats#890]
### Script

All of them

### Problem

All the hacks and guis don’t work the guis pop up but the code don’t work

don’t give hate I’m just confused 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by BananaGuy911** [comment]
If your on mobile you can put in a bookmark and add JavaScript: at the begging of it before pasting it also most of the hacks at this moment aren’t working but the gui should be working fine

**Comment by FBIsurvalincevan15** [comment]
None of the hacks work that way and the that's the only* way.
*best (in my opinion)
