### ISSUE TITLE
Set Gold Issue

### ISSUE THREAD

**Issue by gimmy74** [Minesraft2/Blooket-Cheats#9]
When you set your gold to something like 10k when you press a chest it multiplies by 100 so it goes from 10k to 1m

**Comment by Minesraft2** [comment]
Does this happen everytime?

**Comment by TheBobCreator** [comment]
thats a good thing

**Comment by TheBobCreator** [comment]
also when you do OP towers in tower defense, the rounds skip by a lot, yay

**Comment by Toasty27** [comment]
it makes it obvious your cheating tho

**Comment by Minesraft2** [comment]
???
Then don't cheat

**Comment by gimmy74** [comment]
> Does this happen everytime?

Yes but when u press something like lose 50% gold the multiplications stop
