### ISSUE TITLE
READ THIS

### ISSUE THREAD

**Issue by Minesraft2** [Minesraft2/Blooket-Cheats#900]
I know the cheats are broken right now. I know people are getting suspended. I promise I'll have everything fixed soon I just need to make some time to work on it. For now tell people to stop using the cheats until this issue is closed.

**Comment by Jackson347** [comment]
> I know the cheats are broken right now. I know people are getting suspended. I promise I'll have everything fixed soon I just need to make some time to work on it. For now tell people to stop using the cheats until this issue is closed.

Aye thanks man. And take your time. I'm not a coder so I know this can't be easy.

**Comment by DigitalSerpant** [comment]
Thanks, dont worry I feel your pain.

**Comment by DigitalSerpant** [comment]
Also Im just curious, how did you develop it. Its quite impressive

**Comment by CoderBoyCodes** [comment]
please check my issue

**Comment by CoderBoyCodes** [comment]
> Also Im just curious, how did you develop it. Its quite impressive

The blooket suspend API has been buffed

**Comment by FBIsurvalincevan15** [comment]
thanks

**Comment by RONAKPATELLLLLLL** [comment]
Thank you so much

**Comment by guycoder3** [comment]
can i still get daily rewards

**Comment by peepoostpin** [comment]
why? what did blooket change?

**Comment by Master32rare** [comment]
Thank you! My cheats are also mostly down, and I'm working on those, too. [](https://github.com/Master32rare/Blooket-Hack) I am still a beginner, and my cheats are not very good, but if you (Arell) can please help me with these or help me update them, that would be fantastic. Thanks. maxprogg32@gmail.com

**Comment by guycoder3** [comment]
@peepoostpin blooket probably buffed moderation

**Comment by Master32rare** [comment]
https://github.com/Master32rare/Blooket-Hack

**Comment by Master32rare** [comment]
np

**Comment by Death-By-Dying** [comment]
yeah got my account suspended, only a month though.

**Comment by Master32rare** [comment]
metoo
*Max Erdmann*

**Comment by Master32rare** [comment]
i made alt
*Max Erdmann*

**Comment by Dannyfryar07** [comment]
you all think that's bad i am banned forever and i had almost all Blookets

**Comment by Wilke000** [comment]
Rip bro

**Comment by Death-By-Dying** [comment]
Damn, you can always write an appeal. I got banned on an account once I wrote an appeal saying my friend had done something to my computer and now I couldn't log in and it got accepted.

**Comment by Y3etMeBro** [comment]
The hacks aren't broken right now just use the old gui

**Comment by minecraftminecraft2** [comment]
GO minesraft2

**Comment by Wilke000** [comment]
wait did it get fixed?

**Comment by DigitalSerpant** [comment]
yes

**Comment by Patheticlol** [comment]
PAIN

**Comment by craft-o-s-project** [comment]
> I know the cheats are broken right now. I know people are getting suspended. I promise I'll have everything fixed soon I just need to make some time to work on it. For now tell people to stop using the cheats until this issue is closed.

image of me suspended on 30/5/2023 : https://imgur.com/a/UwpG5ud
