### ISSUE TITLE
Add preventSuspend.js to every obfuscated and unobfuscated script

### ISSUE THREAD

**Issue by CoderBoyCodes** [Minesraft2/Blooket-Cheats#901]
### Gamemode

non

### Function

it helps fix the error that makes suspension happen, the script should add before the hack

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Theuprise** [comment]
If you can do this please do. including after suspended.

**Comment by Minesraft2** [comment]
can't
