### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by alexleoafton** [Minesraft2/Blooket-Cheats#905]
### Script

Idk

### Problem

So i miss clicked on google docs and the blooket hacks OPENED UP ON GOOGLE DOCS PLS FIX 

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by RONAKPATELLLLLLL** [comment]
Don't use the scripts right now @Minesraft2 is fixing them
It might take awhile

**Comment by minecraftminecraft2** [comment]
yea check his post https://github.com/Minesraft2/Blooket-Cheats/issues/900
