### ISSUE TITLE
Tower defense

### ISSUE THREAD

**Issue by PierceMichael** [Minesraft2/Blooket-Cheats#907]
### Script

Tower defense

### Problem

Nothing works

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by RONAKPATELLLLLLL** [comment]
Don't use the code right now they are broken.
@Minesraft2 will fix them soon
It might take awhile

**Comment by iTzH4CKED** [comment]
@Minesraft2 is trying to fix the code... don't use them till he says its OK your just resting the code he has done

**Comment by Master32rare** [comment]
Also, it's sligtly better to paste it into Console of 
nspect.
