### ISSUE TITLE
BUG: (Account Suspension)

### ISSUE THREAD

**Issue by pabloelgato** [Minesraft2/Blooket-Cheats#908]
### Script

blooketgui.js

### Problem

it got my account suspended for some reason pls fix this i dont wanna get suspended once again

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

t
![image](https://github.com/Minesraft2/Blooket-Cheats/assets/125697744/7e27b708-0573-4c47-b9e8-c422e6d49bf2)

**Comment by RONAKPATELLLLLLL** [comment]
Don't use the code right now they are broken.
@Minesraft2 will fix them soon
It might take awhile

**Comment by Jackson347** [comment]
Maybe read before using it. He's currently trying to fix it so just don't use it for now

**Comment by pabloelgato** [comment]
it has been 4 days it maybe has been fixed or something

**Comment by Minesraft2** [comment]
yuh
