### ISSUE TITLE
Event Blooks breaking Sim Unlock

### ISSUE THREAD

**Issue by VillainsRule4000** [Minesraft2/Blooket-Cheats#91]
Uploading Screen Recording 2022-11-24 at 5.40.04 PM.mov…

**Comment by VillainsRule4000** [comment]
wow, upload fail
<img width="1440" alt="Screen Shot 2022-11-24 at 5 40 49 PM" src="https://user-images.githubusercontent.com/101288516/203871146-c67bc36c-37e5-4d9a-9faf-b36b9c61f192.png">
the minute you click sim unlock, it just does this

**Comment by Wilke000** [comment]
It’s not updated

**Comment by VillainsRule4000** [comment]
shut up
who has a replit pfp bro :skull:

**Comment by VillainsRule4000** [comment]
(this dude, btw, is annoying asf)

**Comment by Wilke000** [comment]
Yessir!

**Comment by Minesraft2** [comment]
just dont unbox them then
