### ISSUE TITLE
THANK YOU SO MUCH FOR FIXING THE HACKS 

### ISSUE THREAD

**Issue by FBIsurvalincevan15** [Minesraft2/Blooket-Cheats#913]
### Function

thanks

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Jackson347** [comment]
Are they back and working?

**Comment by orangemonkey01** [comment]
yes they are

**Comment by ThetruePyrobyte** [comment]
are you sure

**Comment by FBIsurvalincevan15** [comment]
they work tho

**Comment by Pyro77** [comment]
We need an suspension preventer

**Comment by FBIsurvalincevan15** [comment]
same

**Comment by ThetruePyrobyte** [comment]
I always get suspended

**Comment by ThetruePyrobyte** [comment]
literally my entire class got suspended

**Comment by orangemonkey01** [comment]
L bozo
