### ISSUE TITLE
BUG: Gui.js

### ISSUE THREAD

**Issue by Cutaly** [Minesraft2/Blooket-Cheats#915]
### Script

Gui.js

### Problem

Is there still a problem with the cheat? I'm currently trying to copy and paste the Gui.js into my bookmark bar, in blooket im pressing on the javascript but nothing pops up. Does anybody else have this kind of issue. The blooket cheat it not working for me still at this moment. 

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by Nicholas3330** [comment]
Go to the GitHub pages sight in the readme and take the code from there

**Comment by Cutaly** [comment]
> Go to the GitHub pages sight in the readme and take the code from there

What do you mean?

**Comment by RONAKPATELLLLLLL** [comment]
[Minesraft2.github.io/Blooket-Cheats/](https://minesraft2.github.io/Blooket-Cheats/) go to this website

**Comment by Stone6142** [comment]
Some school admins have blocked Bookmarklets,[ Article On the topic](https://xfanatical.com/blog/block-student-bookmarklets/) they blocked it at my school to

**Comment by Nicholas3330** [comment]
That article blocks JavaScript:// it may work if you remove any redundant code (// is used to write something that is not an active line of code) and you could also try just paste code straight into the url in the same format as a bookmarklet (going JavaScript: followed by the code)

**Comment by Cutaly** [comment]
>

**Comment by Cutaly** [comment]
RONAKPATELLLLLLL
How do I copy the code?
