### ISSUE TITLE
IDEA: Unban

### ISSUE THREAD

**Issue by Dannyfryar07** [Minesraft2/Blooket-Cheats#917]
### Gamemode

Global

### Function

you use it on the login in screen and it will  Unban the account please do it my account just got banned

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Thing34872** [comment]
I had the same idea, but it cannot be performed due to the reason that it is server sided

**Comment by MEGladot** [comment]
It would be amazing if it would work though ：）

**Comment by Staraner** [comment]
I also got banned :(

**Comment by reyals3** [comment]
same i got banned

**Comment by Wilke000** [comment]
You can’t unban. It’s server-sided

**Comment by AsteriskCodes** [comment]
You can't really access a server-sided api to unban yourself with a client-sided script. Technically, it's impossible about somehow unbanning yourself from suspension...

**Comment by Wilke000** [comment]
Exactly

**Comment by bloohacked** [comment]
imposible
