### ISSUE TITLE
View player blooks

### ISSUE THREAD

**Issue by hasijodfijodsijo** [Minesraft2/Blooket-Cheats#919]
### Gamemode

global

### Function

Make a script so you are able to view one another's blooks, hopefully this works, i checked faq

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Realswitzer** [comment]
if i had to guess, may not be possible since blooket is really lacking in the "social features" department.

**Comment by Thing34872** [comment]
> ### Gamemode
> global
> 
> ### Function
> Make a script so you are able to view one another's blooks, hopefully this works, i checked faq
> 
> ### FaQ
> I have read the FaQ and my suggestion has not already been asked for or isn't possible

For this i need to inspect the source code of blookets blook api

**Comment by peepoostpin** [comment]
wdym? like put in a search for a blooket username and the most recent blook they are using appears?

**Comment by peepoostpin** [comment]
api is https://dashboard.blooket.com/api/users?name=(). () is the blooket username you use to search the blooks of that user.

**Comment by Minesraft2** [comment]
You can't make GET requests to other user stats on the dashboard anymore
