### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by VillainsRule4000** [Minesraft2/Blooket-Cheats#92]
This is your code, at least the GUI is.
https://github.com/Bmincsgaming/Blooket-Mod-Menu-Gui

**Comment by fowntain** [comment]
Gotta love em

**Comment by Minesraft2** [comment]
all the scripts are exactly the same as mine

**Comment by Minesraft2** [comment]
I'll just update the update checker

**Comment by VillainsRule4000** [comment]
their discord is bmincs#8171
they made a rip-off blooket named "blueket" "made entirely in google sites"
https://sites.google.com/view/blueket
:pissonthisuser:
