### ISSUE TITLE
Code got leaked or smth bro

### ISSUE THREAD

**Issue by MM1dnight** [Minesraft2/Blooket-Cheats#922]
### Script

blooket.js

### Problem

all my friends use one of the cheats and we immediately get banned, watch out and this is more then just a problem with the script above.

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

### Extra Info

-

**Comment by Wilke000** [comment]
Wow. 
Blooket.js

**Comment by minecraftminecraft2** [comment]
https://github.com/Minesraft2/Blooket-Cheats/issues/900

**Comment by bcrhbrhcdb** [comment]
You have to "reintsall" the bookmarklet

**Comment by ASTHEBEST** [comment]
It works now(85% chance to work and if it fails you wont get banned).
