### ISSUE TITLE
SCRIPT BROKEN/PATCHED

### ISSUE THREAD

**Issue by OGBlooketCheater** [Minesraft2/Blooket-Cheats#923]
### Script

Gui.js (basically all of the cheats)

### Problem

dude ben patched it and now all my accounts are suspended fix it!!

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

**Comment by minecraftminecraft2** [comment]
https://github.com/Minesraft2/Blooket-Cheats/issues/900

**Comment by bcrhbrhcdb** [comment]
You have to "reinstall" the bookmarklet.

**Comment by OGBlooketCheater** [comment]
it works now but i still gettin banned ☠️

**Comment by Realswitzer** [comment]
L

**Comment by Minesraft2** [comment]
L indeed
