### ISSUE TITLE
BUG: (script name)

### ISSUE THREAD

**Issue by DARK25000** [Minesraft2/Blooket-Cheats#924]
### Script

/* All terms found in the following link apply: https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE */ (async()=>{console.log("%c Blooket Cheats %c\n\tBy OneMinesraft2#4560","color: #0bc2cf; font-size: 3rem","color: #8000ff; font-size: 1rem"),console.log("%c\tsimulateUnlock.js","color: #0bc2cf; font-size: 1rem"),console.log("%c\tStar the github repo!%c  https://github.com/Minesraft2/Blooket-Cheats","color: #ffd000; font-size: 1rem","");var o=document.createElement("iframe");if(document.body.append(o),window.alert=o.contentWindow.alert.bind(window),window.prompt=o.contentWindow.prompt.bind(window),o.remove(),"/market"==window.location.pathname){let g=webpackJsonp.push([[],{[1234]:(e,t,a)=>{t.webpack=a}},[["1234"]]])["webpack"],e=Object.values(g.c),t=e.find(e=>e.exports?.a?.Chick?.set).exports.a,i=e.find(e=>e.exports.a?.Breakfast).exports.a,a=Object.entries(t).reduce((e,[t,a])=>(i[a.realSet||a.set]&&(e[t]=a),e),{});o=Object.values(document.querySelector("body div[id] > div > div"))[1].children[0]._owner["stateNode"];let s=Object.values(g.c).find(e=>e.exports?.Class).exports,p=new function(){this.scene=null,this.particles=null,this.rarity=null};class r extends s.Scene{constructor(e){super(),this.rarity=e.toLowerCase()}preload(){switch(this.rarity){case"uncommon":this.load.svg("uncommon-1","https://media.blooket.com/image/upload/v1658567787/Media/market/particles/square_green.svg",{width:25,height:25}),this.load.svg("uncommon-2","https://media.blooket.com/image/upload/v1658567787/Media/market/particles/square_light_green.svg",{width:25,height:25}),this.load.svg("uncommon-3","https://media.blooket.com/image/upload/v1658567785/Media/market/particles/circle_dark_green.svg",{width:25,height:25}),this.load.svg("uncommon-4","https://media.blooket.com/image/upload/v1658567785/Media/market/particles/serpentine_dark_green.svg",{width:30,height:30}),this.load.svg("uncommon-5","https://media.blooket.com/image/upload/v1658567785/Media/market/particles/triangle_light_green.svg",{width:30,height:30}),this.load.svg("uncommon-6","https://media.blooket.com/image/upload/v1658567785/Media/market/particles/serpentine_light_green.svg",{width:30,height:30}),this.load.svg("uncommon-7","https://media.blooket.com/image/upload/v1658567785/Media/market/particles/triangle_green.svg",{width:30,height:30});break;case"rare":this.load.svg("rare-1","https://media.blooket.com/image/upload/v1658567765/Media/market/particles/square_light_blue.svg",{width:25,height:25}),this.load.svg("rare-2","https://media.blooket.com/image/upload/v1658567765/Media/market/particles/square_dark_blue.svg",{width:25,height:25}),this.load.svg("rare-3","https://media.blooket.com/image/upload/v1658567763/Media/market/particles/triangle_blue.svg",{width:30,height:30}),this.load.svg("rare-4","https://media.blooket.com/image/upload/v1658567763/Media/market/particles/serpentine_blue.svg",{width:30,height:30}),this.load.svg("rare-5","https://media.blooket.com/image/upload/v1658567763/Media/market/particles/triangle_light_blue.svg",{width:30,height:30}),this.load.svg("rare-6","https://media.blooket.com/image/upload/v1658567763/Media/market/particles/serpentine_light_blue.svg",{width:30,height:30}),this.load.svg("rare-7","https://media.blooket.com/image/upload/v1658567763/Media/market/particles/circle_dark_blue.svg",{width:25,height:25});break;case"epic":this.load.svg("epic-1","https://media.blooket.com/image/upload/v1658790239/Media/market/particles/red.svg",{width:25,height:25}),this.load.svg("epic-2","https://media.blooket.com/image/upload/v1658790237/Media/market/particles/light_red.svg",{width:25,height:25}),this.load.svg("epic-3","https://media.blooket.com/image/upload/v1658790239/Media/market/particles/serpentine_red.svg",{width:30,height:30}),this.load.svg("epic-4","https://media.blooket.com/image/upload/v1658790239/Media/market/particles/serpentine_dark_red.svg",{width:30,height:30}),this.load.svg("epic-5","https://media.blooket.com/image/upload/v1658790237/Media/market/particles/triangle_red.svg",{width:30,height:30}),this.load.svg("epic-6","https://media.blooket.com/image/upload/v1658790237/Media/market/particles/triangle_light_red.svg",{width:30,height:30}),this.load.svg("epic-7","https://media.blooket.com/image/upload/v1658790237/Media/market/particles/circle_dark_red.svg",{width:25,height:25});break;case"legendary":this.load.svg("legendary-1","https://media.blooket.com/image/upload/v1658567740/Media/market/particles/square_orange.svg",{width:25,height:25}),this.load.svg("legendary-2","https://media.blooket.com/image/upload/v1658567740/Media/market/particles/square_light_orange.svg",{width:25,height:25}),this.load.svg("legendary-3","https://media.blooket.com/image/upload/v1658567738/Media/market/particles/circle_orange.svg",{width:25,height:25}),this.load.svg("legendary-4","https://media.blooket.com/image/upload/v1658567738/Media/market/particles/serpentine_orange.svg",{width:30,height:30}),this.load.svg("legendary-5","https://media.blooket.com/image/upload/v1658567738/Media/market/particles/serpentine_light_orange.svg",{width:30,height:30}),this.load.svg("legendary-6","https://media.blooket.com/image/upload/v1658567738/Media/market/particles/circle_dark_orange.svg",{width:25,height:25}),this.load.svg("legendary-7","https://media.blooket.com/image/upload/v1658567738/Media/market/particles/triangle_dark_orange.svg",{width:30,height:30});break;case"chroma":this.load.svg("chroma-1","https://media.blooket.com/image/upload/v1658790246/Media/market/particles/square_turquoise.svg",{width:25,height:25}),this.load.svg("chroma-2","https://media.blooket.com/image/upload/v1658790246/Media/market/particles/square_light_turquoise.svg",{width:25,height:25}),this.load.svg("chroma-3","https://media.blooket.com/image/upload/v1658790244/Media/market/particles/serpentine_dark_turquoise.svg",{width:30,height:30}),this.load.svg("chroma-4","https://media.blooket.com/image/upload/v1658790244/Media/market/particles/serpentine_turquoise.svg",{width:30,height:30}),this.load.svg("chroma-5","https://media.blooket.com/image/upload/v1658790244/Media/market/particles/triangle_turquoise.svg",{width:30,height:30}),this.load.svg("chroma-6","https://media.blooket.com/image/upload/v1658790244/Media/market/particles/triangle_light_turquoise.svg",{width:30,height:30}),this.load.svg("chroma-7","https://media.blooket.com/image/upload/v1658790244/Media/market/particles/circle_dark_turquoise.svg",{width:25,height:25})}}create(){p.scene=this,p.rarity="",p.particles=this.physics.add.group({classType:new s.Class({Extends:s.GameObjects.Image,initialize:function(){s.GameObjects.Image.call(this,p.scene,0,0,"uncommon-1"),this.setDepth(3),this.lifespan=0},spawn:function(e,t,a,i,s,o,l,r,c){this.setTexture(c),this.setActive(!0),this.setVisible(!0),this.setPosition(e,t),this.setScale(a),this.targets=[],p.scene.physics.velocityFromAngle(i,s,this.body.velocity),this.body.setGravityY(o),this.body.setAngularVelocity(l),this.lifespan=r},update:function(e,t){this.lifespan-=t,0<this.lifespan||(this.setActive(!1),this.setVisible(!1))}}),runChildUpdate:!0}),this.nextParticle=0,this.numExplosions=0,this.game.events.on("start-particles",e=>{p.rarity=e,this.numExplosions="Uncommon"===e?75:"Rare"===e?100:-1})}update(e,t){const a=g("74sb");function i(e){switch(e){case"center":var t=Object(a.l)(-115,-65);return{x:p.scene.cameras.main.worldView.width/2,y:p.scene.cameras.main.worldView.height/2,scale:Object(a.l)(.7,1),angle:t,velocity:Object(a.l)(600,750),gravity:700,angVelocity:(-90<t?1:-1)*Object(a.l)(125,175),lifespan:2500};case"right-bottom":return{x:p.scene.cameras.main.worldView.width,y:p.scene.cameras.main.worldView.height,scale:Object(a.l)(.7,1),angle:Object(a.l)(-160,-110),velocity:Object(a.l)(600,750),gravity:500,angVelocity:Object(a.l)(-175,-125),lifespan:2500};case"left-bottom":return{x:0,y:p.scene.cameras.main.worldView.height,scale:Object(a.l)(.7,1),angle:Object(a.l)(-70,-20),velocity:Object(a.l)(600,750),gravity:500,angVelocity:Object(a.l)(125,175),lifespan:2500};case"top":return{x:Object(a.l)(0,p.scene.cameras.main.worldView.width),y:-50,scale:Object(a.l)(.7,1),angle:90,velocity:Object(a.l)(0,50),gravity:700,angVelocity:Object(a.l)(-150,150),lifespan:2500};case"right-shower":return{x:p.scene.cameras.main.worldView.width,y:Object(a.l)(0,p.scene.cameras.main.worldView.height),scale:Object(a.l)(.7,1),angle:Object(a.l)(-180,-130),velocity:Object(a.l)(600,750),gravity:500,angVelocity:Object(a.l)(-175,-125),lifespan:2500};case"left-shower":return{x:0,y:Object(a.l)(0,p.scene.cameras.main.worldView.height),scale:Object(a.l)(.7,1),angle:Object(a.l)(-50,0),velocity:Object(a.l)(600,750),gravity:500,angVelocity:Object(a.l)(125,175),lifespan:2500};case"right-diamond":t=Object(a.l)(0,p.scene.cameras.main.worldView.height);return{x:p.scene.cameras.main.worldView.width,y:t,scale:Object(a.l)(.7,1),angle:t>p.scene.cameras.main.worldView.height/2?-150:-210,velocity:Object(a.l)(600,750),gravity:0,angVelocity:Object(a.l)(-175,-125),lifespan:2500};case"left-diamond":t=Object(a.l)(0,p.scene.cameras.main.worldView.height);return{x:0,y:t,scale:Object(a.l)(.7,1),angle:t>p.scene.cameras.main.worldView.height/2?-30:30,velocity:Object(a.l)(600,750),gravity:0,angVelocity:Object(a.l)(125,175),lifespan:2500};default:return{}}}if(p.rarity&&0!==this.numExplosions&&(this.nextParticle-=t,this.nextParticle<=0)){switch(p.rarity){case"Uncommon":for(let e=0;e<2;e++){var s=p.particles.get();s&&s.spawn.apply(s,Object.values(i("center")).concat("uncommon-"+Object(a.m)(1,8)))}break;case"Rare":for(var o=0;o<2;o++){var l=p.particles.get();l&&l.spawn.apply(l,Object.values(i(o%2==0?"left-bottom":"right-bottom")).concat("rare-"+Object(a.m)(1,8)))}break;case"Epic":for(var r=0;r<2;r++){var c=p.particles.get();c&&c.spawn.apply(c,Object.values(i(r%2==0?"left-shower":"right-shower")).concat("epic-"+Object(a.m)(1,8)))}break;case"Legendary":for(var h=0;h<3;h++){var d=p.particles.get();d&&d.spawn.apply(d,Object.values(i("top")).concat("legendary-"+Object(a.m)(1,8)))}break;case"Chroma":for(var n=0;n<3;n++){var m=p.particles.get();m&&m.spawn.apply(m,Object.values(i(n%2==0?"left-diamond":"right-diamond")).concat("chroma-"+Object(a.m)(1,8)))}}this.nextParticle=20,0<this.numExplosions&&(this.numExplosions=Math.max(this.numExplosions-1,0))}}}var l=prompt("What blook do you want to simulate opening? (Case Sensitive)");Object.keys(a).includes(l)?o.setState({loadingPack:!1,openPack:!0,unlockedBlook:l,tokens:o.state.tokens,newUnlock:!0,game:{type:s.WEBGL,parent:"phaser-market",width:"100%",height:"100%",scale:{mode:s.Scale.NONE,autoCenter:s.Scale.CENTER_BOTH},transparent:!0,physics:{default:"arcade"},scene:new r(a[l].rarity)},canOpen:!0}):l&&alert("Invalid blook! Make sure you spelled and capitalized it properly, the blook also needs a buyable pack in the market.")}else alert("This can only be ran on the market page!")})();

### Problem

How do you spell Mega Bot and Yeti in simulate Unlock

### Method

Pasted script into console

### Type

Obfuscated

**Comment by Realswitzer** [comment]
i think you are retarded. can probably close (skill issue)
