### ISSUE TITLE
Global:Change Daily Wheel Luck

### ISSUE THREAD

**Issue by BlOOKETan** [Minesraft2/Blooket-Cheats#925]
### Gamemode

Global

### Function

The script will change your luck for the daily wheel.

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Wilke000** [comment]
Your suggestion has already been asked for and is not possible.

**Comment by Theuprise** [comment]
Honestly I'm sure it is possible but nobody has the info on how to do it.

**Comment by Realswitzer** [comment]
it's possible if you're ben and/or have access to the backend

**Comment by Minesraft2** [comment]
Not possible
