### ISSUE TITLE
When can you make Gimkit hacks?

### ISSUE THREAD

**Issue by Blooket000** [Minesraft2/Blooket-Cheats#926]
### Gamemode

Gimkit

### Function

Gimkit Hacks

### FaQ

I have not read the FaQ

**Comment by Realswitzer** [comment]
can close (has not read faq)
![image](https://github.com/Minesraft2/Blooket-Cheats/assets/39711351/a83763a1-87eb-4b7b-a72e-c2929dc8d0da)
