### ISSUE TITLE
IDEA: Script idea name (private)

### ISSUE THREAD

**Issue by JonJonShe** [Minesraft2/Blooket-Cheats#927]
### Gamemode

Global

### Function

Uhh I only wish to spam space boxes and I wish to get them as fast as possible.
could you just quickly edit the spam boxes code to do so? I don't know js i only know python ;(

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by pazza2234** [comment]
[Screen recording 2023-05-26 10.20.35 AM.webm](https://github.com/Minesraft2/Blooket-Cheats/assets/81707002/c1bd4584-9475-4b7f-b04e-561a07e157d9)
GUI go brrr
also what do you mean by "(private)" in the title?

also sorry for being mean if it is perceived that way.

**Comment by Realswitzer** [comment]
if i had to guess, the spam unlock blooks script is probably already as fast as possible or near that (or fast without abusing api and immediately setting off every red flag)

> also what do you mean by "(private)" in the title?

^this. if it's meant to be "i want a script only for me made by minesraft", that doesnt make any sense. this isnt a youtuber (or other of high status) requesting mods, this is a random person wanting scripts.

**Comment by Minesraft2** [comment]
Going any faster than the api would normally let you increases the chance you get suspended
