### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by Consolehecker** [Minesraft2/Blooket-Cheats#929]
If the hacks you can't do are server sided, then does that mean your "hacking" isn't true hacking. Because if you could actually hack and get into the servers that would be different and these cheats are just abusing bugs in the system? And wouldn't actual hacking be illegal?

**Comment by Realswitzer** [comment]
i guess depending on what you classify as a hack or not, then this being a "hack" could go either way. it doesn't "circumvent security" (based on a simple definition), so it doesn't necessarily fit that definition if that is solely what you are concerned with.

> And wouldn't actual hacking be illegal?

accessing computers and servers without being authorized is a crime (18 U.S. Code § 1030, section (a) (1) potentially -- don't know legalspeak so this should not be taken as advice or fact)

**Comment by Thing34872** [comment]
> If the hacks you can't do are server sided, then does that mean your "hacking" isn't true hacking. Because if you could actually hack and get into the servers that would be different and these cheats are just abusing bugs in the system? And wouldn't actual hacking be illegal?

This guy can’t even distinguish what is legal and not legal.

**Comment by Minesraft2** [comment]
I mean, the repo is called Blooket *Cheats* for a reason
