### ISSUE TITLE
Fixing 99% HTML

### ISSUE THREAD

**Issue by VillainsRule4000** [Minesraft2/Blooket-Cheats#93]
Github measures the ratio of languages based on the storage space it takes up.
I think the HTML is all in the [bookmarklets](https://github.com/Minesraft2/Blooket-Cheats/blob/main/obfuscated/Bookmarklets.html) import (3.16 MB).

If you make a file that is much bigger than 3.16 MB (size of html), it should tip the scale. (idk just copy/paste a ton of `console.log()` statements in a file somewhere)

**Comment by fowntain** [comment]
i have a large file i can send you, if you'd like

**Comment by Minesraft2** [comment]
So having several, huge obfuscated files doesn't do anything?

**Comment by Minesraft2** [comment]
I think it's fine that it's 99% HTML since it doesn't really do anything, plus it makes the repo stand out.

**Comment by VillainsRule4000** [comment]
> So having several, huge obfuscated files doesn't do anything?

All of them are still in kb, not even mb. Even the GUI.
