### ISSUE TITLE
IDEA: Change other persons name,end game,be the host,be another player while kicking them...

### ISSUE THREAD

**Issue by FBIsurvalincevan15** [Minesraft2/Blooket-Cheats#930]
### Gamemode

...

### Function

...

### FaQ

I have not read the FaQ, I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Realswitzer** [comment]
are you stupid.
can close (template not filled out properly + stupid person)

**Comment by Educational-hacker** [comment]
bro dats server side i think

**Comment by Patheticlol** [comment]
@Minesraft2 tell people to stop with these gay questions

**Comment by Minesraft2** [comment]
Not possible
