### ISSUE TITLE
move right answer to slot

### ISSUE THREAD

**Issue by Educational-hacker** [Minesraft2/Blooket-Cheats#933]
### Gamemode

all

### Function

basically whatever the right answer is you can move it to a slot, eg, move right answer to bottom left. that way u could spam tht slot and if someone gets sus, you can click on a different slot

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Educational-hacker** [comment]
btw what

**Comment by Minesraft2** [comment]
just use auto answer or every answer correct
