### ISSUE TITLE
Must run "Get Daily Rewards" twice

### ISSUE THREAD

**Issue by yodaluca23** [Minesraft2/Blooket-Cheats#94]
In order to get all 500 coins and full XP per day you have to run the hack more than once, until it shows "Added 0 tokens and 0 xp!"

Also could you have it have the XP capitalized when it tells you how much was added?

**Comment by Minesraft2** [comment]
I've never had this issue before, does it say it added 500 tokens both times?

**Comment by Minesraft2** [comment]
It's probably something to do with the way manages bonuses, because my script takes what you can get and then adds that

**Comment by Minesraft2** [comment]
I'll just add something to check if you can get more or not and then add it

**Comment by CrypticLucid** [comment]
happening to me too, but i got 0, then 500 after running it twice

**Comment by Minesraft2** [comment]
I'll undo the change I made a day or 2 yesterday and we'll see if that fixes it.

**Comment by yodaluca23** [comment]
> I'll undo the change I made a day or 2 yesterday and we'll see if that fixes it.

That must have been the issue! I did it again today with the new GUI Script, and I got the 500 Tokens and 300 XP!

![Screenshot 2022-11-29 8 13 42 AM](https://user-images.githubusercontent.com/67206487/204552387-cc75b086-7c97-424d-8c38-b5515286d66e.png)

**Comment by Minesraft2** [comment]
Yea so it was ben not putting the right bonus amount in the user data

**Comment by yodaluca23** [comment]
> Yea so it was ben not putting the right bonus amount in the user data

Were you trying to grab it from the stats section?
![image](https://user-images.githubusercontent.com/67206487/204558201-3b1c17ed-813d-4cc0-8617-d9d72b7465ea.png)

**Comment by Minesraft2** [comment]
Yea I thought I could get rid of one of the requests but ig not
