### ISSUE TITLE
IDEA: Prevent suspension(again) and get all blooks(again)

### ISSUE THREAD

**Issue by ASTHEBEST** [Minesraft2/Blooket-Cheats#944]
### Gamemode

global

### Function

Prevent suspension prevents suspension. Last time it was on github but it got removed and now I got banned for 3 months.
Get all blooks lets you get all the blooks(at least make it so that you can brag and it disappears after reload). 

### FaQ

I have read the FaQ and my suggestion has not already been asked for or isn't possible

**Comment by Jiff326** [comment]
how do i do this.

**Comment by Thing34872** [comment]
https://github.com/Minesraft2/Blooket-Cheats/blob/main/unobfuscated/global/useAnyBlook.js
