### ISSUE TITLE
BUG: resetPlayersGold.js

### ISSUE THREAD

**Issue by Itsparrotdude** [Minesraft2/Blooket-Cheats#956]
### Script

resetPlayersGold.js

### Problem

Doesn't work, returns a TypeError. It appears that node.js isnt being defined properly in the function or something. resetAllGold.js seems to have a similar problem.

### Method

Pasted script into console

### Type

Obfuscated

### Extra Info

VM385:1 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at <anonymous>:1:661
    at <anonymous>:1:996

(Using the obfuscated)

**Comment by Minesraft2** [comment]
Unable to reproduce
