### ISSUE TITLE
BUG: menu not showing up

### ISSUE THREAD

**Issue by otmfyourandomize** [Minesraft2/Blooket-Cheats#958]
### Script

Both GUIs'

### Problem

When the bookmarklet is clicked it reloads or just doesnt open at all

### Method

Other (described in Extra Info section)

### Type

Unobfuscated

### Extra Info

I used this https://unknownweb.tk to bookmarklet it

**Comment by Minesraft2** [comment]
Me and the creator are having a little coding clash, I keep fixing this but he keeps breaking it. Maybe in a day or two it'll stop

**Comment by otmfyourandomize** [comment]
Thanks, and also can you please add a leaderbored and the other data? like only the 1st 2ed 3trd and the other actions done by other people?

**Comment by Minesraft2** [comment]
That's already in the gui tho

**Comment by otmfyourandomize** [comment]
> That's already in the gui tho

I mean, the leaderbored built-in and the other people like "{user} just took 96 from {user}!" and the leaderbored on the top

**Comment by Minesraft2** [comment]
That's in the gui

**Comment by otmfyourandomize** [comment]
It is? It doesnt load thats why I cant really see it

**Comment by otmfyourandomize** [comment]
![sketch1690342917021](https://github.com/Minesraft2/Blooket-Cheats/assets/127300019/e64c993d-49ca-4e8a-8459-7c90aaa69375)

**Comment by Minesraft2** [comment]
It only appears in the Alerts tab when you're in a game

**Comment by otmfyourandomize** [comment]
Can you send me it? Not the code but a screenshot pls.... If possible

**Comment by otmfyourandomize** [comment]
> It only appears in the Alerts tab when you're in a game

I know that:

![Screenshot 2023-07-26 2 52 25 PM](https://github.com/Minesraft2/Blooket-Cheats/assets/127300019/96d30e0d-d4e8-4227-9e45-8510d0535eee)

But can you readd the leaderbored built-in? like the screen on the host?

**Comment by otmfyourandomize** [comment]
btw it works loged in home page but not play.blooket loged out, Ill test loged in soon

**Comment by heisirndy** [comment]
It does not restart now but it don’t work on hosted games

**Comment by heisirndy** [comment]
Can you try to fix it pls

**Comment by heisirndy** [comment]
Now it don’t work again

**Comment by Minesraft2** [comment]
> Now it don’t work again 

when'd you last update

**Comment by heisirndy** [comment]
Yes

**Comment by heisirndy** [comment]
It don’t work

**Comment by heisirndy** [comment]
I tried the code multiple times

**Comment by Minesraft2** [comment]
> I tried the code multiple times

I asked when you last updated

**Comment by heisirndy** [comment]
Just now

**Comment by heisirndy** [comment]
Or this isn’t JavaScript?

**Comment by Minesraft2** [comment]
ok I'll look into it tmr

**Comment by heisirndy** [comment]
Thx

**Comment by otmfyourandomize** [comment]
> > I tried the code multiple times
> 
> I asked when you last updated

It works, it's just kinda slow. Just a bit and also, you miss spelled the 2 latest commit for "food game" it's ment to be flood game

**Comment by otmfyourandomize** [comment]
> > > I tried the code multiple times
> > 
> > 
> > I asked when you last updated
> 
> It works, it's just kinda slow. Just a bit and also, you miss spelled the 2 latest commit for "food game" it's ment to be flood game


This line:


    if (String(Function.prototype.call).includes('native')) {
        let call = Function.prototype.call;
        let iframe = document.createElement("iframe");
        document.body.append(iframe);
        iframe.style.display = "none";
        let funcs = {
            querySelectorAll: function () {
                if (["#JODGUI", "#JODMOBILE", "#currPageEl", "#YTRkNmM2MWEtOTg3Zi00YmE1LWI1NzUtNTgyOTUzMWI4ZDYx", "#ODJkMThlMDEtYmEwNi00MzE4LTg4ZGMtM2Y2ZDI0MzY4ZjU2", ".cheatList", ".cheatName", "bG1mYW8=", "#aXQncyBjYXQgYW5kIG1vdXNlIGF0IHRoaXMgcG9pbnQ"].includes(arguments[0]))
                    return [];
                return iframe.contentDocument.querySelectorAll.apply(document, arguments);
            },
            querySelector: iframe.contentDocument.querySelector.bind(document),
            includes: function () {
                if (["Cheats", "Global", "Global Cheats", "Discord - oneminesraft2", "Auto Answer (Toggle)", "Auto Sell Dupes On Open", "Spam Buy Blooks", "Food Game", "Change Blook Ingame", "Get Daily Rewards", "Remove Name Limit", "Simulate Unlock", "Cheat ESP", "Gold Quest Cheats", "Cafe Cheats", "Crypto Hack Cheats", "Deceptive Dinos Cheats", "Tower Defense Cheats", "Tower Defense2 Cheats", "Factory Cheats", "Fishing Frenzy Cheats", "Flappy Blook Cheats", "Tower of Doom Cheats", "Crazy Kingdom Cheats", "Racing Cheats", "Battle Royale Cheats", "Blook Rush Cheats", "Monster Brawl Cheats", "Santa's Workshop Cheats"].includes(arguments[0]))
                    return false;
                return iframe.contentWindow.String.prototype.call(this, arguments);
