### ISSUE TITLE
GUI Can't close on mac

### ISSUE THREAD

**Issue by Wilke000** [Minesraft2/Blooket-Cheats#96]
Mac doesn't have alt, so no one on mac can close it.

**Comment by fowntain** [comment]
"Just download boot camp" 🤓

**Comment by yodaluca23** [comment]
The key bind is "H"...

**Comment by VillainsRule4000** [comment]
> Just use option i think

yea

**Comment by Wilke000** [comment]
> The key bind is "H"...

thats to hide it, not close it

**Comment by Wilke000** [comment]
Go back to the old keybinds

**Comment by Wilke000** [comment]
And you can't click gold rush on the gui / the workshop cheats arent on the gui

**Comment by fowntain** [comment]
why dont we just change the keybinds to Shift+x and shift+h so theres no issues

**Comment by Wilke000** [comment]
Ya!

**Comment by Wilke000** [comment]
Or Control Shift H/X

**Comment by Wilke000** [comment]
WAIT NO WHAT IF YOU CAN SET IT!?

**Comment by Minesraft2** [comment]
looks like I'll be remodeling the gui

**Comment by VillainsRule4000** [comment]
just revert the keyboard stuff
no need to listen to Wike, a person who begs for stuff because he can't code 💀

**Comment by VillainsRule4000** [comment]
> Jod, no need to stress. Your choice, doesn't affect anyone but mac users. (there isn't many of them lol)

I take that personally.

**Comment by Wilke000** [comment]
> just revert the keyboard stuff no need to listen to Wike, a person who begs for stuff because he can't code 💀

as I said before, I code on replit.

**Comment by Wilke000** [comment]
> just revert the keyboard stuff no need to listen to Wike, a person who begs for stuff because he can't code 💀

you spelled my username wrong

**Comment by Wilke000** [comment]
Nope doesn't work update ur gui

**Comment by Wilke000** [comment]
Uh not to sound impatient, but are you working on this?

**Comment by Minesraft2** [comment]
low on priority, just use option+x

**Comment by Wilke000** [comment]
That doesn't work! Alt and option are 2 different things

**Comment by Minesraft2** [comment]
On mac option counts as altKey for keypress events, if that doesn't work just use windows fr

**Comment by Wilke000** [comment]
. Windows stinks. Just change the keybind to smth like control+shift+x and just h

**Comment by Wilke000** [comment]
> "Just download boot camp" 🤓

Also I cant. Im on a silicon chip mac
