### ISSUE TITLE
BUG: GetDaily Rewards!

### ISSUE THREAD

**Issue by JonJonShe** [Minesraft2/Blooket-Cheats#961]
### Script

GetDailyRewards

### Problem

Uhh its saying "Undefined" daily whell and not adding

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark

### Type

Unobfuscated, Obfuscated

**Comment by Minesraft2** [comment]
Sorry forgot to close, fixed.
