### ISSUE TITLE
BUG: gui.js

### ISSUE THREAD

**Issue by Red-backspider** [Minesraft2/Blooket-Cheats#962]
### Script

gui.js

### Problem

After running gui.js in a bookmarklet, it gives the following error in console: (see screenshot)

### Method

Put 'javascript:(code)' in the url bar or a bookmark

### Type

Obfuscated

### Extra Info

![image](https://github.com/Minesraft2/Blooket-Cheats/assets/66238571/b99ea3de-4c88-4380-a393-ddfa82b19a43)

**Comment by Minesraft2** [comment]
Fixed, update your GUI

**Comment by Red-backspider** [comment]
Thank you!
