### ISSUE TITLE
BUG: autoselldupes

### ISSUE THREAD

**Issue by JonJonShe** [Minesraft2/Blooket-Cheats#963]
### Script

autoselldupesonopen

### Problem

So this one is just completely broken
I tried everything.

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by JonJonShe** [comment]
are u ther its been a week

**Comment by Minesraft2** [comment]
That script shouldn't be up anymore

**Comment by Minesraft2** [comment]
[6f727b5](https://github.com/Minesraft2/Blooket-Cheats/commit/6f727b5786aaa42ff5a271bb9799ef524c05af35)
