### ISSUE TITLE
BUG: Get Daily rewards

### ISSUE THREAD

**Issue by victini-fan** [Minesraft2/Blooket-Cheats#964]
### Script

getDailyRewards.js

### Problem

whenever i use the script nothing happens, no response, no error message, nothing
I've tried everything, html on obfuscated and unobfuscated, copying and pasting obfuscated and unobfuscated with javascript: behind it, so please fix this

### Method

Imported Bookmarklets.html, Put 'javascript:(code)' in the url bar or a bookmark, Pasted script into console

### Type

Unobfuscated, Obfuscated

**Comment by Minesraft2** [comment]
Then update, I just tested it and it's working
