### ISSUE TITLE
heres a video

### ISSUE THREAD

**Issue by victini-fan** [Minesraft2/Blooket-Cheats#965]
### Script

getDailyRewards.js

### Problem

[Screen recording 2023-07-31 8.59.55 AM.webm](https://github.com/Minesraft2/Blooket-Cheats/assets/99260955/35377806-f214-420f-a102-463e7cc7f78d)

### Method

Imported Bookmarklets.html

### Type

Unobfuscated, Obfuscated

**Comment by victini-fan** [comment]
Nothing happens

**Comment by Minesraft2** [comment]
Run it on play.blooket.com

**Comment by victini-fan** [comment]
k

**Comment by Minesraft2** [comment]
Are you on a school computer?
