### ISSUE TITLE
BUG: still not working

### ISSUE THREAD

**Issue by victini-fan** [Minesraft2/Blooket-Cheats#966]
### Script

getDailyRewards.js

### Problem

[Screen recording 2023-07-31 9.04.06 AM.webm](https://github.com/Minesraft2/Blooket-Cheats/assets/99260955/8f52efcd-bb1f-4f10-b9ec-1dea5430e4bf)

### Method

Imported Bookmarklets.html

### Type

Obfuscated

**Comment by Minesraft2** [comment]
Are you on a school computer?

**Comment by Minesraft2** [comment]
Well I can't fix anything if I can't find the problem, I'm trying the exact same thing and it's working perfectly

**Comment by victini-fan** [comment]
its fine then
