### ISSUE TITLE
BUG: Website. Need help please....

### ISSUE THREAD

**Issue by otmfyourandomize** [Minesraft2/Blooket-Cheats#967]
### Script

script.js

### Problem

Can you help me with https://github.com/otmfyourandomize/Blooket-Settings/
and https://otmfyourandomize.github.io/Blooket-Settings

### Method

Imported Bookmarklets.html

### Type

Unobfuscated

### Extra Info

[Screen recording 2023-08-01 12.18.32 PM.webm](https://github.com/Minesraft2/Blooket-Cheats/assets/127300019/64698ef9-c433-4525-a78e-743a1d8c7ae2)

**Comment by otmfyourandomize** [comment]
I mean, Bookmarklets.html

**Comment by otmfyourandomize** [comment]
If you dont mind.... can you help me.

**Comment by Minesraft2** [comment]
I don't own, manage, or plan to manage that link or repository

**Comment by otmfyourandomize** [comment]
Can you help me fix it?
